// ═══════════════════════════════════════════════════════════
//  VocabMaster — C1 Advanced Vocabulary Database
// ═══════════════════════════════════════════════════════════
const TOPICS_C1 = [
  {
    id: 'c1_academic', name: 'Academic & Analysis', nameVi: 'Học thuật', icon: '🎓', color: '#8B5CF6',
    words: [
      { word: 'alleviate', phonetic: '/əˈliː.vi.eɪt/', meaning: 'Làm giảm bớt, xoa dịu', example: 'The new policy aims to alleviate poverty in rural areas.' },
      { word: 'ambiguous', phonetic: '/æmˈbɪɡ.ju.əs/', meaning: 'Mơ hồ, nhập nhằng', example: 'The contract language was deliberately ambiguous.' },
      { word: 'assert', phonetic: '/əˈsɜːt/', meaning: 'Khẳng định, quả quyết', example: 'She asserted her right to speak at the meeting.' },
      { word: 'consensus', phonetic: '/kənˈsen.səs/', meaning: 'Sự đồng thuận', example: 'The committee reached a consensus after hours of debate.' },
      { word: 'contend', phonetic: '/kənˈtend/', meaning: 'Tranh luận, cho rằng', example: 'Experts contend that the data is misleading.' },
      { word: 'discrepancy', phonetic: '/dɪˈskrep.ən.si/', meaning: 'Sự khác biệt, không nhất quán', example: 'There was a discrepancy between the two reports.' },
      { word: 'conducive', phonetic: '/kənˈdjuː.sɪv/', meaning: 'Có lợi cho, thuận lợi', example: 'A quiet environment is conducive to concentration.' },
      { word: 'paramount', phonetic: '/ˈpær.ə.maʊnt/', meaning: 'Tối quan trọng', example: 'Patient safety is of paramount importance.' },
      { word: 'scrutinize', phonetic: '/ˈskruː.tɪ.naɪz/', meaning: 'Xem xét kỹ lưỡng', example: 'The auditors scrutinized every financial transaction.' },
      { word: 'viable', phonetic: '/ˈvaɪ.ə.bəl/', meaning: 'Khả thi, có thể thực hiện', example: 'Solar energy is a viable alternative to fossil fuels.' },
      { word: 'rigorous', phonetic: '/ˈrɪɡ.ər.əs/', meaning: 'Nghiêm ngặt, chặt chẽ', example: 'The study followed a rigorous scientific methodology.' },
      { word: 'articulate', phonetic: '/ɑːˈtɪk.jə.lət/', meaning: 'Diễn đạt rõ ràng', example: 'She articulated her vision for the company clearly.' },
      { word: 'comprehensive', phonetic: '/ˌkɒm.prɪˈhen.sɪv/', meaning: 'Toàn diện, bao quát', example: 'We need a comprehensive review of the entire system.' },
      { word: 'coherent', phonetic: '/kəʊˈhɪə.rənt/', meaning: 'Mạch lạc, chặt chẽ', example: 'The essay presents a coherent argument throughout.' },
      { word: 'arbitrary', phonetic: '/ˈɑː.bɪ.trər.i/', meaning: 'Tùy tiện, độc đoán', example: 'The decision seemed completely arbitrary.' },
      { word: 'methodology', phonetic: '/ˌmeθ.əˈdɒl.ə.dʒi/', meaning: 'Phương pháp luận', example: 'The paper explains the research methodology in detail.' },
      { word: 'synthesis', phonetic: '/ˈsɪn.θə.sɪs/', meaning: 'Sự tổng hợp', example: 'The essay requires a synthesis of multiple academic sources.' },
      { word: 'assertion', phonetic: '/əˈsɜː.ʃən/', meaning: 'Sự khẳng định, tuyên bố', example: 'The assertion was backed by strong statistical evidence.' },
      { word: 'critique', phonetic: '/krɪˈtiːk/', meaning: 'Bài phân tích phê bình', example: 'The professor gave a thorough critique of the student\'s thesis.' },
      { word: 'attain', phonetic: '/əˈteɪn/', meaning: 'Đạt được (mục tiêu)', example: 'She worked hard to attain a high score on the exam.' },
    ]
  },
  {
    id: 'c1_business', name: 'Business & Economy', nameVi: 'Kinh doanh', icon: '📈', color: '#F59E0B',
    words: [
      { word: 'lucrative', phonetic: '/ˈluː.krə.tɪv/', meaning: 'Sinh lợi, có lãi', example: 'The tech industry remains a lucrative career path.' },
      { word: 'bureaucracy', phonetic: '/bjʊˈrɒk.rə.si/', meaning: 'Bộ máy hành chính', example: 'Excessive bureaucracy slows down business operations.' },
      { word: 'deficit', phonetic: '/ˈdef.ɪ.sɪt/', meaning: 'Sự thâm hụt', example: 'The country faces a growing trade deficit.' },
      { word: 'allocate', phonetic: '/ˈæl.ə.keɪt/', meaning: 'Phân bổ, cấp phát', example: 'The government allocated funds for infrastructure.' },
      { word: 'affluent', phonetic: '/ˈæf.lu.ənt/', meaning: 'Giàu có, thịnh vượng', example: 'The affluent neighborhood has excellent schools.' },
      { word: 'curtail', phonetic: '/kɜːˈteɪl/', meaning: 'Cắt giảm, hạn chế', example: 'The company curtailed spending during the recession.' },
      { word: 'deplete', phonetic: '/dɪˈpliːt/', meaning: 'Làm cạn kiệt', example: 'Overfishing has depleted stocks in the ocean.' },
      { word: 'compensate', phonetic: '/ˈkɒm.pən.seɪt/', meaning: 'Bồi thường, đền bù', example: 'The airline compensated passengers for the delay.' },
      { word: 'cumulative', phonetic: '/ˈkjuː.mjə.lə.tɪv/', meaning: 'Tích lũy, cộng dồn', example: 'The cumulative effect of small changes is significant.' },
      { word: 'autonomous', phonetic: '/ɔːˈtɒn.ə.məs/', meaning: 'Tự trị, tự chủ', example: 'Each department operates as an autonomous unit.' },
      { word: 'subsidize', phonetic: '/ˈsʌb.sɪ.daɪz/', meaning: 'Trợ cấp, tài trợ', example: 'The government subsidizes renewable energy projects.' },
      { word: 'monopoly', phonetic: '/məˈnɒp.əl.i/', meaning: 'Độc quyền', example: 'The company holds a monopoly on the market.' },
      { word: 'procurement', phonetic: '/prəˈkjʊə.mənt/', meaning: 'Sự mua sắm, thu mua', example: 'The procurement process must follow strict guidelines.' },
      { word: 'volatility', phonetic: '/ˌvɒl.əˈtɪl.ə.ti/', meaning: 'Sự biến động', example: 'Market volatility increased during the crisis.' },
      { word: 'leverage', phonetic: '/ˈliː.vər.ɪdʒ/', meaning: 'Đòn bẩy, tận dụng', example: 'We can leverage technology to improve efficiency.' },
      { word: 'audit', phonetic: '/ˈɔː.dɪt/', meaning: 'Cuộc kiểm toán', example: 'The company underwent an independent financial audit.' },
      { word: 'expenditure', phonetic: '/ɪkˈspen.dɪ.tʃər/', meaning: 'Chi tiêu, khoản chi', example: 'Government expenditure on education has increased significantly.' },
      { word: 'merger', phonetic: '/ˈmɜː.dʒər/', meaning: 'Sự sáp nhập công ty', example: 'The merger created one of the largest corporations in the world.' },
      { word: 'compliance', phonetic: '/kəmˈplaɪ.əns/', meaning: 'Sự tuân thủ quy định', example: 'All products must meet regulatory compliance standards.' },
      { word: 'franchise', phonetic: '/ˈfræn.tʃaɪz/', meaning: 'Nhượng quyền kinh doanh', example: 'She opened a fast-food franchise in the city center.' },
      { word: 'bankrupt', phonetic: '/ˈbæŋk.rʌpt/', meaning: 'Phá sản, không có khả năng trả nợ', example: 'He went bankrupt after only a year in business.' },
      { word: 'revenue', phonetic: '/ˈrev.ən.juː/', meaning: 'Doanh thu; nguồn thu lớn từ thuế hoặc kinh doanh', example: 'The company\'s revenue increased by 20% following the merger.' },
      { word: 'sector', phonetic: '/ˈsek.tər/', meaning: 'Khu vực, lĩnh vực kinh tế', example: 'The technology sector has experienced rapid growth in recent years.' },
      { word: 'workforce', phonetic: '/ˈwɜːk.fɔːs/', meaning: 'Lực lượng lao động', example: 'The factory reduced its workforce by 15% to cut costs.' },
      { word: 'commodity', phonetic: '/kəˈmɒd.ə.ti/', meaning: 'Hàng hóa, mặt hàng thương mại', example: 'Oil remains one of the most traded commodities in the world.' },
    ]
  },
  {
    id: 'c1_society', name: 'Society & Politics', nameVi: 'Xã hội & Chính trị', icon: '🏛️', color: '#EC4899',
    words: [
      { word: 'sovereignty', phonetic: '/ˈsɒv.rɪn.ti/', meaning: 'Chủ quyền', example: 'Nations must respect each other\'s sovereignty.' },
      { word: 'ideology', phonetic: '/ˌaɪ.diˈɒl.ə.dʒi/', meaning: 'Hệ tư tưởng', example: 'Political ideology shapes government policies.' },
      { word: 'referendum', phonetic: '/ˌref.əˈren.dəm/', meaning: 'Cuộc trưng cầu dân ý', example: 'The referendum on independence drew high voter turnout.' },
      { word: 'dissent', phonetic: '/dɪˈsent/', meaning: 'Sự bất đồng, phản đối', example: 'The judge expressed dissent from the majority opinion.' },
      { word: 'legislation', phonetic: '/ˌledʒ.ɪˈsleɪ.ʃən/', meaning: 'Pháp luật, luật pháp', example: 'New legislation was introduced to protect consumers.' },
      { word: 'precedent', phonetic: '/ˈpres.ɪ.dənt/', meaning: 'Tiền lệ', example: 'This ruling sets a legal precedent for future cases.' },
      { word: 'allegation', phonetic: '/ˌæl.ɪˈɡeɪ.ʃən/', meaning: 'Cáo buộc, lời buộc tội', example: 'The allegations of corruption were never proven.' },
      { word: 'censorship', phonetic: '/ˈsen.sə.ʃɪp/', meaning: 'Kiểm duyệt', example: 'Internet censorship restricts freedom of information.' },
      { word: 'demographic', phonetic: '/ˌdem.əˈɡræf.ɪk/', meaning: 'Nhân khẩu học', example: 'Demographic changes affect housing demand.' },
      { word: 'urbanization', phonetic: '/ˌɜː.bən.aɪˈzeɪ.ʃən/', meaning: 'Đô thị hóa', example: 'Rapid urbanization creates challenges for infrastructure.' },
      { word: 'accountability', phonetic: '/əˌkaʊn.təˈbɪl.ə.ti/', meaning: 'Trách nhiệm giải trình', example: 'Public officials must accept accountability for their actions.' },
      { word: 'emancipate', phonetic: '/ɪˈmæn.sɪ.peɪt/', meaning: 'Giải phóng', example: 'The movement sought to emancipate marginalized communities.' },
      { word: 'biased', phonetic: '/ˈbaɪ.əst/', meaning: 'Thiên vị, thiên lệch', example: 'The media coverage was clearly biased.' },
      { word: 'controversial', phonetic: '/ˌkɒn.trəˈvɜː.ʃəl/', meaning: 'Gây tranh cãi', example: 'The policy remains highly controversial.' },
      { word: 'mandate', phonetic: '/ˈmæn.deɪt/', meaning: 'Ủy quyền, lệnh', example: 'The president received a clear mandate from voters.' },
      { word: 'discrimination', phonetic: '/dɪˌskrɪm.ɪˈneɪ.ʃən/', meaning: 'Sự phân biệt đối xử', example: 'Workplace discrimination based on gender is illegal.' },
      { word: 'constitution', phonetic: '/ˌkɒn.stɪˈtjuː.ʃən/', meaning: 'Hiến pháp', example: 'The constitution guarantees freedom of speech for all citizens.' },
      { word: 'injustice', phonetic: '/ɪnˈdʒʌs.tɪs/', meaning: 'Sự bất công', example: 'The protesters marched against social injustice.' },
      { word: 'tolerance', phonetic: '/ˈtɒl.ər.əns/', meaning: 'Sự khoan dung, chấp nhận khác biệt', example: 'Religious tolerance is essential in a multicultural society.' },
      { word: 'electoral', phonetic: '/ɪˈlek.tər.əl/', meaning: 'Thuộc về bầu cử', example: 'Electoral reform is needed to ensure fair representation.' },
    ]
  },
  {
    id: 'c1_science', name: 'Science & Research', nameVi: 'Khoa học', icon: '🔬', color: '#06B6D4',
    words: [
      { word: 'hypothesis', phonetic: '/haɪˈpɒθ.ə.sɪs/', meaning: 'Giả thuyết', example: 'The hypothesis was supported by experimental data.' },
      { word: 'empirical', phonetic: '/ɪmˈpɪr.ɪ.kəl/', meaning: 'Thực nghiệm, dựa trên kinh nghiệm', example: 'The study provides empirical evidence for the theory.' },
      { word: 'phenomenon', phonetic: '/fɪˈnɒm.ɪ.nən/', meaning: 'Hiện tượng', example: 'Climate change is a well-documented phenomenon.' },
      { word: 'correlate', phonetic: '/ˈkɒr.ə.leɪt/', meaning: 'Tương quan, liên hệ', example: 'Income levels correlate with educational attainment.' },
      { word: 'anomaly', phonetic: '/əˈnɒm.ə.li/', meaning: 'Sự bất thường, dị thường', example: 'Scientists detected an anomaly in the data.' },
      { word: 'replicate', phonetic: '/ˈrep.lɪ.keɪt/', meaning: 'Tái tạo, nhân bản', example: 'Other labs failed to replicate the results.' },
      { word: 'paradigm', phonetic: '/ˈpær.ə.daɪm/', meaning: 'Mô hình, khuôn mẫu', example: 'AI represents a paradigm shift in computing.' },
      { word: 'synthesize', phonetic: '/ˈsɪn.θə.saɪz/', meaning: 'Tổng hợp', example: 'The researcher synthesized findings from multiple studies.' },
      { word: 'extrapolate', phonetic: '/ɪkˈstræp.ə.leɪt/', meaning: 'Ngoại suy, suy ra', example: 'We cannot extrapolate future trends from limited data.' },
      { word: 'substantiate', phonetic: '/səbˈstæn.ʃi.eɪt/', meaning: 'Chứng minh, chứng thực', example: 'He failed to substantiate his claims with evidence.' },
      { word: 'mitigate', phonetic: '/ˈmɪt.ɪ.ɡeɪt/', meaning: 'Giảm thiểu, làm dịu', example: 'We must mitigate the impact of climate change.' },
      { word: 'derive', phonetic: '/dɪˈraɪv/', meaning: 'Bắt nguồn, rút ra', example: 'The word derives from ancient Greek.' },
      { word: 'elucidate', phonetic: '/ɪˈluː.sɪ.deɪt/', meaning: 'Làm sáng tỏ', example: 'The professor elucidated the complex theory.' },
      { word: 'proliferate', phonetic: '/prəˈlɪf.ər.eɪt/', meaning: 'Sinh sôi, lan rộng', example: 'Fake news proliferates on social media.' },
      { word: 'innate', phonetic: '/ɪˈneɪt/', meaning: 'Bẩm sinh, vốn có', example: 'Humans have an innate ability to learn language.' },
      { word: 'correlation', phonetic: '/ˌkɒr.əˈleɪ.ʃən/', meaning: 'Sự tương quan', example: 'There is a strong correlation between exercise and mental health.' },
      { word: 'simulate', phonetic: '/ˈsɪm.jʊ.leɪt/', meaning: 'Mô phỏng', example: 'Scientists simulate climate conditions in laboratory experiments.' },
      { word: 'specimen', phonetic: '/ˈspes.ɪ.mɪn/', meaning: 'Mẫu vật, tiêu bản', example: 'The museum displayed rare geological specimens from around the world.' },
      { word: 'evolutionary', phonetic: '/ˌiː.vəˈluː.ʃən.ər.i/', meaning: 'Thuộc về tiến hóa', example: 'Evolutionary biology explains the diversity of life on Earth.' },
      { word: 'equation', phonetic: '/ɪˈkweɪ.ʒən/', meaning: 'Phương trình', example: 'Einstein\'s famous equation changed the way we understand energy.' },
      { word: 'cutting-edge', phonetic: '/ˌkʌt.ɪŋˈedʒ/', meaning: 'Hiện đại nhất, tiên tiến nhất', example: 'This laboratory uses cutting-edge technology to sequence DNA.' },
      { word: 'state-of-the-art', phonetic: '/ˌsteɪt.əv.ðiˈɑːt/', meaning: 'Công nghệ tiên tiến và hiện đại nhất hiện có', example: 'The hospital has a state-of-the-art scanning facility.' },
      { word: 'genetically modified', phonetic: '/dʒəˌnet.ɪ.kliˈmɒd.ɪˌfaɪd/', meaning: 'Biến đổi gen bằng quy trình khoa học', example: 'Many countries restrict the import of genetically modified crops.' },
      { word: 'radiation', phonetic: '/ˌreɪ.diˈeɪ.ʃən/', meaning: 'Bức xạ năng lượng từ vật liệu hạt nhân', example: 'Workers in nuclear plants must be protected from dangerous radiation.' },
    ]
  },
  {
    id: 'c1_communication', name: 'Communication & Media', nameVi: 'Truyền thông', icon: '📡', color: '#F97316',
    words: [
      { word: 'eloquent', phonetic: '/ˈel.ə.kwənt/', meaning: 'Hùng biện, lưu loát', example: 'She gave an eloquent speech at the conference.' },
      { word: 'distort', phonetic: '/dɪˈstɔːt/', meaning: 'Bóp méo, xuyên tạc', example: 'The media distorted the facts of the case.' },
      { word: 'disseminate', phonetic: '/dɪˈsem.ɪ.neɪt/', meaning: 'Phổ biến, truyền bá', example: 'Social media helps disseminate information rapidly.' },
      { word: 'elicit', phonetic: '/ɪˈlɪs.ɪt/', meaning: 'Khơi gợi, moi ra', example: 'The question elicited a surprising response.' },
      { word: 'concise', phonetic: '/kənˈsaɪs/', meaning: 'Ngắn gọn, súc tích', example: 'Keep your presentation concise and focused.' },
      { word: 'fabricate', phonetic: '/ˈfæb.rɪ.keɪt/', meaning: 'Bịa đặt, ngụy tạo', example: 'The journalist was fired for fabricating stories.' },
      { word: 'advocate', phonetic: '/ˈæd.və.keɪt/', meaning: 'Ủng hộ, người biện hộ', example: 'She advocates for equal rights in education.' },
      { word: 'insinuate', phonetic: '/ɪnˈsɪn.ju.eɪt/', meaning: 'Ám chỉ, bóng gió', example: 'He insinuated that the results were falsified.' },
      { word: 'refute', phonetic: '/rɪˈfjuːt/', meaning: 'Bác bỏ, phản bác', example: 'The scientist refuted the outdated theory with new data.' },
      { word: 'undermine', phonetic: '/ˌʌn.dəˈmaɪn/', meaning: 'Làm suy yếu, phá hoại', example: 'Fake news undermines public trust in institutions.' },
      { word: 'corroborate', phonetic: '/kəˈrɒb.ə.reɪt/', meaning: 'Xác nhận, chứng thực', example: 'Witnesses corroborated the victim\'s account.' },
      { word: 'convey', phonetic: '/kənˈveɪ/', meaning: 'Truyền đạt, chuyển tải', example: 'Art can convey powerful emotions without words.' },
      { word: 'denounce', phonetic: '/dɪˈnaʊns/', meaning: 'Lên án, tố cáo', example: 'World leaders denounced the act of aggression.' },
      { word: 'impartial', phonetic: '/ɪmˈpɑː.ʃəl/', meaning: 'Công bằng, vô tư', example: 'A judge must remain impartial during a trial.' },
      { word: 'ubiquitous', phonetic: '/juːˈbɪk.wɪ.təs/', meaning: 'Có mặt khắp nơi', example: 'Smartphones have become ubiquitous in modern life.' },
      { word: 'credibility', phonetic: '/ˌkred.ɪˈbɪl.ɪ.ti/', meaning: 'Uy tín, tính đáng tin cậy', example: 'Fake news damages the credibility of legitimate journalism.' },
      { word: 'endorsement', phonetic: '/ɪnˈdɔːs.mənt/', meaning: 'Sự chứng thực, ủng hộ công khai', example: 'The celebrity\'s endorsement boosted product sales significantly.' },
      { word: 'discourse', phonetic: '/ˈdɪs.kɔːs/', meaning: 'Diễn ngôn, cuộc thảo luận', example: 'Public discourse on climate change has become increasingly polarized.' },
      { word: 'investigator', phonetic: '/ɪnˈves.tɪ.ɡeɪ.tər/', meaning: 'Điều tra viên', example: 'The investigator uncovered key evidence at the crime scene.' },
      { word: 'transparency', phonetic: '/trænsˈpær.ən.si/', meaning: 'Sự minh bạch', example: 'Transparency in government builds public trust.' },
    ]
  },
  {
    id: 'c1_psychology', name: 'Mind & Behavior', nameVi: 'Tâm lý & Hành vi', icon: '🧠', color: '#10B981',
    words: [
      { word: 'perceive', phonetic: '/pəˈsiːv/', meaning: 'Nhận thức, cảm nhận', example: 'People perceive risk differently based on experience.' },
      { word: 'cognitive', phonetic: '/ˈkɒɡ.nɪ.tɪv/', meaning: 'Nhận thức, thuộc về tư duy', example: 'Cognitive decline can begin in middle age.' },
      { word: 'resilient', phonetic: '/rɪˈzɪl.i.ənt/', meaning: 'Kiên cường, dẻo dai', example: 'Children are remarkably resilient after setbacks.' },
      { word: 'compel', phonetic: '/kəmˈpel/', meaning: 'Thúc ép, buộc phải', example: 'His story compelled the audience to take action.' },
      { word: 'inhibit', phonetic: '/ɪnˈhɪb.ɪt/', meaning: 'Ức chế, kìm hãm', example: 'Fear can inhibit creative thinking.' },
      { word: 'contemplate', phonetic: '/ˈkɒn.təm.pleɪt/', meaning: 'Suy ngẫm, chiêm nghiệm', example: 'She contemplated the meaning of the artwork.' },
      { word: 'empathy', phonetic: '/ˈem.pə.θi/', meaning: 'Sự đồng cảm', example: 'Empathy is essential for building strong relationships.' },
      { word: 'conform', phonetic: '/kənˈfɔːm/', meaning: 'Tuân theo, hòa nhập', example: 'Teenagers often feel pressure to conform to peer norms.' },
      { word: 'intrinsic', phonetic: '/ɪnˈtrɪn.zɪk/', meaning: 'Nội tại, vốn có', example: 'Intrinsic motivation leads to deeper learning.' },
      { word: 'susceptible', phonetic: '/səˈsep.tɪ.bəl/', meaning: 'Dễ bị ảnh hưởng', example: 'Young children are more susceptible to peer pressure.' },
      { word: 'stigma', phonetic: '/ˈstɪɡ.mə/', meaning: 'Sự kỳ thị, dấu vết ô nhục', example: 'There is still stigma surrounding mental health issues.' },
      { word: 'ambivalent', phonetic: '/æmˈbɪv.ə.lənt/', meaning: 'Mâu thuẫn, nửa muốn nửa không', example: 'She felt ambivalent about accepting the job offer.' },
      { word: 'predispose', phonetic: '/ˌpriː.dɪˈspəʊz/', meaning: 'Khiến có khuynh hướng', example: 'Genetics can predispose individuals to certain diseases.' },
      { word: 'tenacious', phonetic: '/təˈneɪ.ʃəs/', meaning: 'Kiên trì, bền bỉ', example: 'Her tenacious spirit helped her overcome obstacles.' },
      { word: 'pragmatic', phonetic: '/præɡˈmæt.ɪk/', meaning: 'Thực dụng, thực tế', example: 'We need a pragmatic approach to solve this problem.' },
      { word: 'trauma', phonetic: '/ˈtrɔː.mə/', meaning: 'Sang chấn tâm lý, chấn thương', example: 'Childhood trauma can have lasting effects on mental health.' },
      { word: 'consciousness', phonetic: '/ˈkɒn.ʃəs.nəs/', meaning: 'Ý thức, sự tỉnh táo', example: 'The study of consciousness remains one of philosophy\'s greatest mysteries.' },
      { word: 'obsession', phonetic: '/əbˈseʃ.ən/', meaning: 'Sự ám ảnh', example: 'His obsession with perfection made him difficult to work with.' },
      { word: 'frustration', phonetic: '/frʌˈstreɪ.ʃən/', meaning: 'Sự thất vọng, bực bội', example: 'The constant technical problems caused great frustration.' },
      { word: 'distress', phonetic: '/dɪˈstres/', meaning: 'Nỗi đau khổ, khổ sở', example: 'The sudden news caused significant emotional distress.' },
      { word: 'narrow-minded', phonetic: '/ˌnær.əʊˈmaɪn.dɪd/', meaning: 'Thiển cận, không chấp nhận ý kiến mới', example: 'Narrow-minded thinking prevents creative solutions to complex problems.' },
      { word: 'open-minded', phonetic: '/ˌəʊ.pənˈmaɪn.dɪd/', meaning: 'Cởi mở, sẵn sàng tiếp nhận ý kiến mới', example: 'Scientists must remain open-minded when evaluating new theories.' },
      { word: 'stamina', phonetic: '/ˈstæm.ɪ.nə/', meaning: 'Sức bền thể chất hoặc tinh thần', example: 'Long-distance runners need remarkable stamina to complete a marathon.' },
      { word: 'discipline', phonetic: '/ˈdɪs.ə.plɪn/', meaning: 'Khả năng kiểm soát hành vi của bản thân; kỷ luật', example: 'Academic success requires dedication and a great deal of self-discipline.' },
    ]
  },
  {
    id: 'c1_urban', name: 'Urban Life', nameVi: 'Cuộc sống thành thị',
    icon: '🏙️', color: '#64748B',
    words: [
      { word: 'metropolis', phonetic: '/mɪˈtrɒp.ə.lɪs/', meaning: 'Đô thị lớn, trung tâm', example: 'Tokyo is one of the world\'s most vibrant metropolises.' },
      { word: 'commuter', phonetic: '/kəˈmjuː.tər/', meaning: 'Người đi làm từ xa hàng ngày', example: 'Millions of commuters use the subway system every day.' },
      { word: 'congestion', phonetic: '/kənˈdʒes.tʃən/', meaning: 'Sự tắc nghẽn giao thông', example: 'Traffic congestion costs cities billions in lost productivity each year.' },
      { word: 'cosmopolitan', phonetic: '/ˌkɒz.məˈpɒl.ɪ.tən/', meaning: 'Mang tính quốc tế, đa văn hóa', example: 'London is one of the most cosmopolitan cities in the world.' },
      { word: 'gentrification', phonetic: '/ˌdʒen.trɪ.fɪˈkeɪ.ʃən/', meaning: 'Sự biến đổi khu dân cư theo hướng thượng lưu', example: 'Gentrification has driven up rents and displaced long-time residents.' },
      { word: 'infrastructure', phonetic: '/ˈɪn.frəˌstrʌk.tʃər/', meaning: 'Cơ sở hạ tầng', example: 'The city needs to invest heavily in its crumbling infrastructure.' },
      { word: 'skyscraper', phonetic: '/ˈskaɪ.skreɪ.pər/', meaning: 'Nhà chọc trời', example: 'The city\'s skyline is dominated by glass and steel skyscrapers.' },
      { word: 'suburb', phonetic: '/ˈsʌb.ɜːb/', meaning: 'Vùng ngoại ô', example: 'Many families move to the suburbs for better schools and open space.' },
      { word: 'municipal', phonetic: '/mjuːˈnɪs.ɪ.pəl/', meaning: 'Thuộc về thành phố, đô thị', example: 'The municipal government launched a citywide recycling program.' },
      { word: 'surveillance', phonetic: '/səˈveɪ.ləns/', meaning: 'Sự giám sát', example: 'CCTV surveillance cameras now cover nearly every street corner.' },
      { word: 'amenity', phonetic: '/əˈmiː.nɪ.ti/', meaning: 'Tiện nghi, cơ sở dịch vụ', example: 'The new development offers premium amenities including a rooftop garden.' },
      { word: 'renovation', phonetic: '/ˌren.əˈveɪ.ʃən/', meaning: 'Sự cải tạo, tu bổ', example: 'The historic building underwent a complete renovation last year.' },
      { word: 'pedestrian', phonetic: '/pəˈdes.tri.ən/', meaning: 'Người đi bộ; dành cho người đi bộ', example: 'The new pedestrian zone has revitalized the city center.' },
      { word: 'affordable', phonetic: '/əˈfɔː.də.bəl/', meaning: 'Giá cả phải chăng', example: 'Affordable housing remains a major challenge in most big cities.' },
      { word: 'deteriorate', phonetic: '/dɪˈtɪər.i.ə.reɪt/', meaning: 'Xuống cấp, trở nên tồi tệ hơn', example: 'The quality of public transport has deteriorated significantly over the years.' },
      { word: 'residential', phonetic: '/ˌrez.ɪˈden.ʃəl/', meaning: 'Thuộc khu dân cư', example: 'The residential area is quiet and family-friendly.' },
      { word: 'density', phonetic: '/ˈden.sɪ.ti/', meaning: 'Mật độ (dân số)', example: 'Population density in major cities continues to increase.' },
      { word: 'suburban', phonetic: '/səˈbɜː.bən/', meaning: 'Thuộc vùng ngoại ô', example: 'Suburban sprawl has replaced farmland around the city.' },
      { word: 'landmark', phonetic: '/ˈlænd.mɑːk/', meaning: 'Công trình mang tính biểu tượng', example: 'The Eiffel Tower is Paris\'s most iconic landmark.' },
      { word: 'transit', phonetic: '/ˈtræn.zɪt/', meaning: 'Giao thông công cộng, vận chuyển', example: 'The city invested heavily in rapid transit to ease congestion.' },
      { word: 'commute', phonetic: '/kəˈmjuːt/', meaning: 'Đi lại thường xuyên giữa nhà và nơi làm việc', example: 'She commutes two hours each day by train to reach her office.' },
      { word: 'congestion', phonetic: '/kənˈdʒes.tʃən/', meaning: 'Sự tắc nghẽn giao thông hoặc kênh truyền', example: 'Traffic congestion in the city centre is becoming increasingly problematic.' },
      { word: 'infrastructure', phonetic: '/ˈɪn.frəˌstrʌk.tʃər/', meaning: 'Cơ sở hạ tầng: giao thông, điện, nước...', example: 'The government plans to invest billions in modernising transport infrastructure.' },
      { word: 'furnished', phonetic: '/ˈfɜː.nɪʃt/', meaning: 'Có trang bị đầy đủ nội thất', example: 'He\'s renting a fully furnished apartment near the city centre.' },
    ]
  },
  {
    id: 'c1_culture', name: 'Culture & Traditions', nameVi: 'Văn hóa & Truyền thống',
    icon: '🎌', color: '#A855F7',
    words: [
      { word: 'acculturation', phonetic: '/əˌkʌl.tʃərˈeɪ.ʃən/', meaning: 'Sự giao lưu, tiếp biến văn hóa', example: 'Acculturation occurs naturally when immigrant communities interact with locals over time.' },
      { word: 'stereotype', phonetic: '/ˈster.i.ə.taɪp/', meaning: 'Khuôn mẫu, định kiến', example: 'Stereotypes can prevent us from seeing people as unique individuals.' },
      { word: 'multiculturalism', phonetic: '/ˌmʌl.tiˈkʌl.tʃər.ə.lɪ.z(ə)m/', meaning: 'Chủ nghĩa đa văn hóa', example: 'Multiculturalism enriches society through the celebration of diversity.' },
      { word: 'heritage', phonetic: '/ˈher.ɪ.tɪdʒ/', meaning: 'Di sản văn hóa', example: 'The ancient temple is a UNESCO World Heritage Site.' },
      { word: 'indigenous', phonetic: '/ɪnˈdɪdʒ.ɪ.nəs/', meaning: 'Bản địa, thuộc địa phương', example: 'Indigenous languages are endangered in many regions of the world.' },
      { word: 'assimilate', phonetic: '/əˈsɪm.ɪ.leɪt/', meaning: 'Đồng hóa, hòa nhập văn hóa', example: 'Immigrants often assimilate into the local culture over generations.' },
      { word: 'nostalgia', phonetic: '/nɒˈstæl.dʒə/', meaning: 'Nỗi nhớ nhà, tâm trạng hoài cổ', example: 'The old photographs filled her with a deep sense of nostalgia.' },
      { word: 'taboo', phonetic: '/təˈbuː/', meaning: 'Điều cấm kỵ trong văn hóa', example: 'Discussing money openly is considered taboo in some cultures.' },
      { word: 'etiquette', phonetic: '/ˈet.ɪ.kɪt/', meaning: 'Phép tắc, lễ nghi xã giao', example: 'Business etiquette varies significantly across different countries.' },
      { word: 'subculture', phonetic: '/ˈsʌbˌkʌl.tʃər/', meaning: 'Văn hóa phụ, nhóm xã hội riêng', example: 'Hip-hop began as an urban subculture in New York City in the 1970s.' },
      { word: 'reverence', phonetic: '/ˈrev.ər.əns/', meaning: 'Sự tôn kính sâu sắc', example: 'The ancient shrine is treated with great reverence by local communities.' },
      { word: 'homogeneous', phonetic: '/ˌhɒm.əˈdʒiː.ni.əs/', meaning: 'Đồng nhất, thuần nhất', example: 'Japan has a relatively homogeneous cultural and ethnic identity.' },
      { word: 'ritual', phonetic: '/ˈrɪtʃ.u.əl/', meaning: 'Nghi lễ, nghi thức', example: 'Wedding rituals vary greatly across different cultures and religions.' },
      { word: 'folklore', phonetic: '/ˈfəʊk.lɔːr/', meaning: 'Văn hóa dân gian, truyền thuyết', example: 'Local folklore preserves the history and values of rural communities.' },
      { word: 'patronage', phonetic: '/ˈpeɪ.trə.nɪdʒ/', meaning: 'Sự bảo trợ nghệ thuật', example: 'The arts have always depended on generous patronage for their survival.' },
      { word: 'legacy', phonetic: '/ˈleɡ.ə.si/', meaning: 'Di sản, ảnh hưởng lâu dài', example: 'The artist\'s legacy continues to inspire generations of creators.' },
      { word: 'secular', phonetic: '/ˈsek.jʊ.lər/', meaning: 'Thế tục, không tôn giáo', example: 'France maintains a strictly secular approach to government.' },
      { word: 'symbolic', phonetic: '/sɪmˈbɒl.ɪk/', meaning: 'Mang tính biểu tượng', example: 'The gesture was largely symbolic but still meaningful to many.' },
      { word: 'colonial', phonetic: '/kəˈloʊ.ni.əl/', meaning: 'Thuộc địa, liên quan đến thực dân', example: 'Colonial architecture still dominates parts of the old city.' },
      { word: 'sacred', phonetic: '/ˈseɪ.krɪd/', meaning: 'Thiêng liêng, được tôn thờ', example: 'The river is considered sacred by local religious communities.' },
    ]
  },
  {
    id: 'c1_global', name: 'Global Issues', nameVi: 'Vấn đề toàn cầu',
    icon: '🌐', color: '#059669',
    words: [
      { word: 'inequality', phonetic: '/ˌɪn.ɪˈkwɒl.ɪ.ti/', meaning: 'Sự bất bình đẳng', example: 'Economic inequality has widened significantly in many developed countries.' },
      { word: 'desertification', phonetic: '/dɪˌzɜː.tɪ.fɪˈkeɪ.ʃən/', meaning: 'Sự sa mạc hóa đất đai', example: 'Desertification is turning fertile land into barren desert across large parts of Africa.' },
      { word: 'displacement', phonetic: '/dɪsˈpleɪs.mənt/', meaning: 'Sự di dời, tị nạn', example: 'Climate change is causing the displacement of entire coastal communities.' },
      { word: 'sanitation', phonetic: '/ˌsæn.ɪˈteɪ.ʃən/', meaning: 'Vệ sinh môi trường, hệ thống thoát nước', example: 'Poor sanitation is a major cause of preventable diseases worldwide.' },
      { word: 'famine', phonetic: '/ˈfæm.ɪn/', meaning: 'Nạn đói', example: 'Famine continues to devastate regions affected by prolonged conflict.' },
      { word: 'exploitation', phonetic: '/ˌek.splɔɪˈteɪ.ʃən/', meaning: 'Sự bóc lột', example: 'The exploitation of natural resources must be regulated more strictly.' },
      { word: 'humanitarian', phonetic: '/hjuːˌmæn.ɪˈteər.i.ən/', meaning: 'Nhân đạo, từ thiện', example: 'The humanitarian crisis required an immediate international response.' },
      { word: 'pandemic', phonetic: '/pænˈdem.ɪk/', meaning: 'Đại dịch toàn cầu', example: 'The pandemic exposed deep vulnerabilities in global health systems.' },
      { word: 'refugee', phonetic: '/ˌref.juˈdʒiː/', meaning: 'Người tị nạn', example: 'Millions of refugees fled the war-torn country seeking safety abroad.' },
      { word: 'malnutrition', phonetic: '/ˌmæl.njuːˈtrɪʃ.ən/', meaning: 'Suy dinh dưỡng', example: 'Malnutrition stunts both physical and cognitive development in children.' },
      { word: 'trafficking', phonetic: '/ˈtræf.ɪ.kɪŋ/', meaning: 'Buôn người, buôn lậu', example: 'Human trafficking is a global crime that affects millions of victims.' },
      { word: 'epidemic', phonetic: '/ˌep.ɪˈdem.ɪk/', meaning: 'Dịch bệnh trong một khu vực', example: 'An epidemic of obesity is now affecting many Western nations.' },
      { word: 'impoverish', phonetic: '/ɪmˈpɒv.ər.ɪʃ/', meaning: 'Làm nghèo đi, suy kiệt', example: 'War impoverishes entire generations in the regions it affects.' },
      { word: 'brain drain', phonetic: '/breɪn dreɪn/', meaning: 'Chảy máu chất xám', example: 'Brain drain affects developing nations as skilled workers emigrate abroad.' },
      { word: 'terrorism', phonetic: '/ˈter.ər.ɪ.z(ə)m/', meaning: 'Chủ nghĩa khủng bố', example: 'International cooperation is essential in the global fight against terrorism.' },
      { word: 'asylum', phonetic: '/əˈsaɪ.ləm/', meaning: 'Quyền tị nạn, nơi ẩn náu an toàn', example: 'The family applied for political asylum after fleeing their country.' },
      { word: 'migration', phonetic: '/maɪˈɡreɪ.ʃən/', meaning: 'Sự di cư', example: 'Climate-driven migration is expected to increase in the coming decades.' },
      { word: 'sanction', phonetic: '/ˈsæŋk.ʃən/', meaning: 'Lệnh trừng phạt kinh tế', example: 'International sanctions were imposed on the country following the conflict.' },
      { word: 'cooperate', phonetic: '/koʊˈɒp.ər.eɪt/', meaning: 'Hợp tác', example: 'Nations must cooperate to address global environmental challenges.' },
      { word: 'sustainable', phonetic: '/səˈsteɪ.nə.bl̩/', meaning: 'Bền vững, không gây tổn hại lâu dài cho môi trường', example: 'We need to develop sustainable solutions to reduce our carbon footprint.' },
      { word: 'conservation', phonetic: '/ˌkɒn.səˈveɪ.ʃən/', meaning: 'Bảo tồn thiên nhiên và tài nguyên', example: 'Conservation efforts have helped several endangered species recover.' },
      { word: 'naive', phonetic: '/naɪˈiːv/', meaning: 'Ngây thơ, thiếu kinh nghiệm về thế giới', example: 'It would be naive to think that global problems can be solved overnight.' },
    ]
  },
  {
    id: 'c1_books', name: 'Literature & Books', nameVi: 'Sách & Văn học',
    icon: '📖', color: '#F43F5E',
    words: [
      { word: 'protagonist', phonetic: '/prəˈtæɡ.ə.nɪst/', meaning: 'Nhân vật chính', example: 'The protagonist faces a series of moral dilemmas throughout the story.' },
      { word: 'narrative', phonetic: '/ˈnær.ə.tɪv/', meaning: 'Câu chuyện kể, hình thức tường thuật', example: 'The narrative shifts between past and present throughout the novel.' },
      { word: 'genre', phonetic: '/ˈʒɒ̃.rə/', meaning: 'Thể loại văn học', example: 'Science fiction is a genre that explores future technological possibilities.' },
      { word: 'synopsis', phonetic: '/sɪˈnɒp.sɪs/', meaning: 'Bản tóm tắt nội dung', example: 'Read the synopsis before deciding whether to purchase the book.' },
      { word: 'metaphor', phonetic: '/ˈmet.ə.fər/', meaning: 'Ẩn dụ', example: '"Life is a journey" is one of the most enduring metaphors in literature.' },
      { word: 'anthology', phonetic: '/ænˈθɒl.ə.dʒi/', meaning: 'Tuyển tập', example: 'The anthology brings together fifty years of groundbreaking short stories.' },
      { word: 'rhetoric', phonetic: '/ˈret.ər.ɪk/', meaning: 'Tu từ học, nghệ thuật hùng biện', example: 'His speech was filled with powerful and emotionally persuasive rhetoric.' },
      { word: 'prose', phonetic: '/prəʊz/', meaning: 'Văn xuôi', example: 'She writes elegant prose that flows naturally and is easy to read.' },
      { word: 'satire', phonetic: '/ˈsæt.aɪər/', meaning: 'Văn châm biếm', example: 'The novel is a sharp satire of modern consumer culture and social media.' },
      { word: 'manuscript', phonetic: '/ˈmæn.jʊ.skrɪpt/', meaning: 'Bản thảo', example: 'The author submitted the manuscript to several publishers before it was accepted.' },
      { word: 'foreshadowing', phonetic: '/fɔːˈʃæd.əʊ.ɪŋ/', meaning: 'Sự báo trước trong tác phẩm', example: 'The author used clever foreshadowing to hint at the tragic ending.' },
      { word: 'allusion', phonetic: '/əˈluː.ʒən/', meaning: 'Sự ám chỉ đến tác phẩm/sự kiện khác', example: 'The poem contains a clear allusion to Shakespeare\'s Hamlet.' },
      { word: 'stanza', phonetic: '/ˈstæn.zə/', meaning: 'Khổ thơ', example: 'The poem consists of four stanzas of six lines each.' },
      { word: 'characterization', phonetic: '/ˌkær.ɪk.tər.aɪˈzeɪ.ʃən/', meaning: 'Sự xây dựng nhân vật', example: 'The author\'s vivid characterization made every character feel real.' },
      { word: 'autobiography', phonetic: '/ˌɔː.tə.baɪˈɒɡ.rə.fi/', meaning: 'Tự truyện', example: 'The politician wrote a candid autobiography about his rise to power.' },
      { word: 'memoir', phonetic: '/ˈmem.wɑːr/', meaning: 'Hồi ký', example: 'The former president published a compelling memoir last year.' },
      { word: 'verse', phonetic: '/vɜːs/', meaning: 'Thơ ca, khổ thơ', example: 'The poem is written in free verse without a fixed rhyme scheme.' },
      { word: 'portray', phonetic: '/pɔːˈtreɪ/', meaning: 'Miêu tả, khắc họa', example: 'The novel portrays life in rural Vietnam with great sensitivity.' },
      { word: 'characterize', phonetic: '/ˈkær.ɪk.tər.aɪz/', meaning: 'Mô tả đặc điểm, đặc trưng hóa', example: 'Critics characterized the book as a masterpiece of modern fiction.' },
      { word: 'debut', phonetic: '/ˈdeɪ.bjuː/', meaning: 'Sự ra mắt lần đầu', example: 'Her debut novel won several prestigious literary awards.' },
    ]
  },
  {
    id: 'c1_personality', name: 'Human Characteristics', nameVi: 'Tính cách con người',
    icon: '😊', color: '#EAB308',
    words: [
      { word: 'affable', phonetic: '/ˈæf.ə.bəl/', meaning: 'Niềm nở, thân thiện, dễ gần', example: 'The affable host made all the guests feel welcome immediately.' },
      { word: 'cynical', phonetic: '/ˈsɪn.ɪ.kəl/', meaning: 'Hoài nghi, coi thường người khác', example: 'His cynical outlook on life made it hard to enjoy simple pleasures.' },
      { word: 'eccentric', phonetic: '/ɪkˈsen.trɪk/', meaning: 'Lập dị, kỳ quặc', example: 'The eccentric scientist kept unusual hours and had very strange habits.' },
      { word: 'gregarious', phonetic: '/ɡrɪˈɡeər.i.əs/', meaning: 'Hòa đồng, thích giao tiếp xã hội', example: 'Her gregarious nature made her instantly popular at every social event.' },
      { word: 'volatile', phonetic: '/ˈvɒl.ə.taɪl/', meaning: 'Hay thay đổi thất thường, bốc đồng', example: 'His volatile temper made working with him extremely challenging.' },
      { word: 'astute', phonetic: '/əˈstjuːt/', meaning: 'Sắc sảo, tinh tế, nhạy bén', example: 'She made an astute observation that completely changed everyone\'s perspective.' },
      { word: 'meticulous', phonetic: '/mɪˈtɪk.jʊ.ləs/', meaning: 'Tỉ mỉ, cẩn thận đến từng chi tiết', example: 'He was meticulous in his approach to every task he undertook.' },
      { word: 'impulsive', phonetic: '/ɪmˈpʌl.sɪv/', meaning: 'Bốc đồng, hành động theo cảm tính', example: 'Impulsive decisions made in anger are often deeply regretted.' },
      { word: 'complacent', phonetic: '/kəmˈpleɪ.sənt/', meaning: 'Tự mãn, quá thỏa mãn với hiện trạng', example: 'Don\'t become complacent just because things are going well right now.' },
      { word: 'versatile', phonetic: '/ˈvɜː.sə.taɪl/', meaning: 'Đa năng, linh hoạt, nhiều tài', example: 'She is a versatile performer, excelling in both drama and comedy.' },
      { word: 'charismatic', phonetic: '/ˌkær.ɪzˈmæt.ɪk/', meaning: 'Có sức hút cá nhân, lôi cuốn', example: 'The charismatic leader quickly attracted a large and devoted following.' },
      { word: 'pedantic', phonetic: '/pɪˈdæn.tɪk/', meaning: 'Máy móc, quá cầu kỳ về chi tiết nhỏ', example: 'The pedantic professor corrected every minor grammatical error in the essay.' },
      { word: 'assertive', phonetic: '/əˈsɜː.tɪv/', meaning: 'Quyết đoán, tự tin bày tỏ quan điểm', example: 'Being assertive means expressing yourself confidently without being aggressive.' },
      { word: 'diligent', phonetic: '/ˈdɪl.ɪ.dʒənt/', meaning: 'Chăm chỉ, siêng năng, cần cù', example: 'Her diligent effort throughout the year paid off at the final exam.' },
      { word: 'scrupulous', phonetic: '/ˈskruː.pjʊ.ləs/', meaning: 'Ngay thẳng, có lương tâm nghề nghiệp', example: 'The scrupulous accountant never cut corners on any financial report.' },
      { word: 'compassion', phonetic: '/kəmˈpæʃ.ən/', meaning: 'Lòng trắc ẩn, sự cảm thông', example: 'True leadership requires both strength and compassion.' },
      { word: 'dedicated', phonetic: '/ˈded.ɪ.keɪ.tɪd/', meaning: 'Tận tâm, cống hiến', example: 'She is a dedicated teacher who goes above and beyond for her students.' },
      { word: 'integrity', phonetic: '/ɪnˈteɡ.rɪ.ti/', meaning: 'Sự liêm chính, tính chính trực', example: 'A leader with integrity earns the trust of their team.' },
      { word: 'loyalty', phonetic: '/ˈlɔɪ.əl.ti/', meaning: 'Lòng trung thành', example: 'His loyalty to the company never wavered, even during difficult times.' },
      { word: 'humble', phonetic: '/ˈhʌm.bəl/', meaning: 'Khiêm tốn, khiêm nhường', example: 'Despite her success, she remained genuinely humble and approachable.' },
    ]
  },
  {
    id: 'c1_space', name: 'Universe & Space', nameVi: 'Vũ trụ & Không gian',
    icon: '🌌', color: '#3B82F6',
    words: [
      { word: 'constellation', phonetic: '/ˌkɒn.stəˈleɪ.ʃən/', meaning: 'Chòm sao', example: 'Orion is one of the most recognizable constellations in the night sky.' },
      { word: 'asteroid', phonetic: '/ˈæs.tər.ɔɪd/', meaning: 'Tiểu hành tinh', example: 'A massive asteroid struck Earth 65 million years ago, causing mass extinction.' },
      { word: 'exoplanet', phonetic: '/ˈek.soʊ.plæn.ɪt/', meaning: 'Ngoại hành tinh', example: 'Scientists have discovered thousands of exoplanets orbiting distant stars.' },
      { word: 'eclipse', phonetic: '/ɪˈklɪps/', meaning: 'Nhật thực hoặc nguyệt thực', example: 'A total solar eclipse plunged the region into temporary darkness.' },
      { word: 'nebula', phonetic: '/ˈneb.jʊ.lə/', meaning: 'Tinh vân', example: 'The Orion Nebula is a stellar nursery where new stars are born.' },
      { word: 'orbit', phonetic: '/ˈɔː.bɪt/', meaning: 'Quỹ đạo', example: 'The Moon\'s orbit around Earth takes approximately 27 days to complete.' },
      { word: 'supernova', phonetic: '/ˌsuː.pəˈnəʊ.və/', meaning: 'Vụ nổ sao siêu tân tinh', example: 'A supernova is one of the most energetic explosions in the universe.' },
      { word: 'gravity', phonetic: '/ˈɡræv.ɪ.ti/', meaning: 'Lực hấp dẫn', example: 'Einstein revolutionized our understanding of space, time, and gravity.' },
      { word: 'interstellar', phonetic: '/ˌɪn.təˈstel.ər/', meaning: 'Liên sao, giữa các ngôi sao', example: 'Interstellar travel remains a theoretical concept for current technology.' },
      { word: 'cosmos', phonetic: '/ˈkɒz.mɒs/', meaning: 'Vũ trụ bao la', example: 'The cosmos is estimated to be approximately 13.8 billion years old.' },
      { word: 'meteorite', phonetic: '/ˈmiː.ti.ər.aɪt/', meaning: 'Thiên thạch đã rơi xuống Trái Đất', example: 'A meteorite crater was discovered in the remote desert region.' },
      { word: 'propulsion', phonetic: '/prəˈpʌl.ʃən/', meaning: 'Lực đẩy, hệ thống đẩy', example: 'Ion propulsion could enable faster travel to distant planets in the future.' },
      { word: 'zenith', phonetic: '/ˈzen.ɪθ/', meaning: 'Đỉnh đầu trên bầu trời; đỉnh cao', example: 'The sun reached its zenith at noon during the summer solstice.' },
      { word: 'solstice', phonetic: '/ˈsɒl.stɪs/', meaning: 'Điểm chí (hạ chí/đông chí)', example: 'The summer solstice marks the longest day of the year.' },
      { word: 'luminosity', phonetic: '/ˌluː.mɪˈnɒs.ɪ.ti/', meaning: 'Độ sáng của ngôi sao', example: 'Astronomers measure a star\'s luminosity to determine its size and age.' },
    ]
  },

  // ── 6 topics from Cambridge C1 Word List PDF ─────────────

  {
    id: 'c1_health_med', name: 'Health & Medical', nameVi: 'Sức khỏe & Y tế',
    icon: '🩺', color: '#E11D48',
    words: [
      { word: 'clinical', phonetic: '/ˈklɪn.ɪ.kəl/', meaning: 'Thuộc y tế lâm sàng, thực hành y tế', example: 'A clinical trial tested the new medicine on five hundred patients.' },
      { word: 'surgeon', phonetic: '/ˈsɜː.dʒən/', meaning: 'Bác sĩ phẫu thuật', example: 'The surgeon performed a six-hour operation to remove the tumour.' },
      { word: 'infect', phonetic: '/ɪnˈfekt/', meaning: 'Lây nhiễm bệnh cho người khác', example: 'A single infected person can infect dozens of others in a crowded space.' },
      { word: 'hygiene', phonetic: '/ˈhaɪ.dʒiːn/', meaning: 'Vệ sinh, sự sạch sẽ để phòng bệnh', example: 'Good personal hygiene is essential to prevent the spread of infection.' },
      { word: 'nutritional', phonetic: '/njuːˈtrɪʃ.ən.əl/', meaning: 'Thuộc về dinh dưỡng', example: 'The nutritional value of processed food is often lower than fresh food.' },
      { word: 'protein', phonetic: '/ˈprəʊ.tiːn/', meaning: 'Chất đạm, protein', example: 'Athletes need a diet rich in protein to build and repair muscle tissue.' },
      { word: 'discomfort', phonetic: '/dɪˈskʌm.fət/', meaning: 'Sự khó chịu, cảm giác đau nhẹ', example: 'Patients sometimes experience mild discomfort after the procedure.' },
      { word: 'pulse', phonetic: '/pʌls/', meaning: 'Mạch đập, nhịp tim', example: 'The nurse checked the patient\'s pulse and found it was unusually slow.' },
      { word: 'donate', phonetic: '/dəʊˈneɪt/', meaning: 'Hiến tặng (máu, nội tạng)', example: 'Many lives could be saved if more people chose to donate their organs.' },
      { word: 'side effect', phonetic: '/ˈsaɪd.ɪ.fekt/', meaning: 'Tác dụng phụ của thuốc', example: 'Nausea is a common side effect of this particular medication.' },
      { word: 'digest', phonetic: '/daɪˈdʒest/', meaning: 'Tiêu hóa thức ăn trong dạ dày', example: 'The stomach takes longer to digest fatty foods than simple carbohydrates.' },
      { word: 'bacteria', phonetic: '/bækˈtɪə.ri.ə/', meaning: 'Vi khuẩn', example: 'Some bacteria are harmless, but others can cause serious illness.' },
      { word: 'genetic', phonetic: '/dʒəˈnet.ɪk/', meaning: 'Thuộc về di truyền, gen', example: 'Researchers identified a genetic mutation linked to the risk of cancer.' },
      { word: 'abnormal', phonetic: '/æbˈnɔː.məl/', meaning: 'Bất thường, khác mức bình thường', example: 'The scan revealed abnormal cell growth that required further testing.' },
      { word: 'fibre', phonetic: '/ˈfaɪ.bər/', meaning: 'Chất xơ, giúp hệ tiêu hóa hoạt động', example: 'A diet rich in fibre can reduce the risk of digestive problems.' },
      { word: 'well-being', phonetic: '/ˌwelˈbiː.ɪŋ/', meaning: 'Sức khỏe và hạnh phúc tổng thể', example: 'Regular exercise contributes greatly to both physical and mental well-being.' },
      { word: 'undergo', phonetic: '/ˌʌn.dəˈgəʊ/', meaning: 'Trải qua (điều trị, phẫu thuật, thay đổi)', example: 'She had to undergo major surgery to correct the problem.' },
      { word: 'obesity', phonetic: '/əʊˈbiː.sɪ.ti/', meaning: 'Tình trạng béo phì ảnh hưởng đến sức khỏe', example: 'Childhood obesity has become a serious public health concern worldwide.' },
      { word: 'self-esteem', phonetic: '/ˌself.ɪˈstiːm/', meaning: 'Lòng tự trọng, sự tự tin về bản thân', example: 'Low self-esteem can significantly affect both academic performance and social relationships.' },
    ]
  },

  {
    id: 'c1_law_justice', name: 'Law & Justice', nameVi: 'Pháp luật & Công lý',
    icon: '⚖️', color: '#1D4ED8',
    words: [
      { word: 'accusation', phonetic: '/ˌæk.jʊˈzeɪ.ʃən/', meaning: 'Sự cáo buộc, buộc tội ai đó', example: 'He denied the accusation and insisted on his innocence.' },
      { word: 'smuggle', phonetic: '/ˈsmʌg.l/', meaning: 'Vận chuyển trái phép, buôn lậu', example: 'Customs officials discovered drugs being smuggled inside the vehicle.' },
      { word: 'sue', phonetic: '/suː/', meaning: 'Kiện tụng, đưa ra tòa', example: 'She decided to sue the company for unfair dismissal.' },
      { word: 'imprison', phonetic: '/ɪmˈprɪz.ən/', meaning: 'Tống giam, bỏ tù', example: 'He was imprisoned for five years for committing fraud.' },
      { word: 'magistrate', phonetic: '/ˈmædʒ.ɪ.streɪt/', meaning: 'Thẩm phán tòa sơ thẩm', example: 'The magistrate sentenced him to two hundred hours of community service.' },
      { word: 'injustice', phonetic: '/ɪnˈdʒʌs.tɪs/', meaning: 'Sự bất công, đối xử phi lý', example: 'The protesters took to the streets to highlight the injustice of the system.' },
      { word: 'solicitor', phonetic: '/səˈlɪs.ɪ.tər/', meaning: 'Luật sư cố vấn (hệ thống luật Anh)', example: 'She consulted a solicitor before signing the legal agreement.' },
      { word: 'suspicion', phonetic: '/səˈspɪʃ.ən/', meaning: 'Sự nghi ngờ, tình nghi phạm tội', example: 'Police arrested him on suspicion of theft.' },
      { word: 'innocence', phonetic: '/ˈɪn.ə.sənts/', meaning: 'Sự vô tội', example: 'The new evidence helped prove his innocence after years in prison.' },
      { word: 'enforce', phonetic: '/ɪnˈfɔːs/', meaning: 'Cưỡng chế, bắt buộc thi hành pháp luật', example: 'It is the police\'s job to enforce the laws passed by parliament.' },
      { word: 'impose', phonetic: '/ɪmˈpəʊz/', meaning: 'Áp đặt hình phạt hoặc luật lệ', example: 'The judge imposed a heavy fine on the corporation for environmental violations.' },
      { word: 'defend', phonetic: '/dɪˈfend/', meaning: 'Bào chữa, biện hộ trước tòa', example: 'The lawyer worked hard to defend his client against the charges.' },
      { word: 'wrongly', phonetic: '/ˈrɒŋ.li/', meaning: 'Oan sai, bị xử lý sai trái', example: 'He was wrongly convicted and spent twelve years in prison before being freed.' },
      { word: 'charge', phonetic: '/tʃɑːdʒ/', meaning: 'Cáo trạng, tội danh bị buộc tội', example: 'She was released without charge after questioning by police.' },
      { word: 'serial', phonetic: '/ˈsɪə.ri.əl/', meaning: 'Liên hoàn, lặp đi lặp lại nhiều lần', example: 'Police were hunting a serial offender responsible for a series of break-ins.' },
    ]
  },

  {
    id: 'c1_commerce', name: 'Business & Commerce', nameVi: 'Kinh doanh & Thương mại',
    icon: '📈', color: '#0369A1',
    words: [
      { word: 'executive', phonetic: '/ɪgˈzek.jə.tɪv/', meaning: 'Cấp điều hành, quản lý cấp cao', example: 'Senior executives earn far more than the average worker.' },
      { word: 'enterprise', phonetic: '/ˈen.tə.praɪz/', meaning: 'Doanh nghiệp, cơ sở kinh doanh', example: 'The government launched a scheme to support small enterprises.' },
      { word: 'corporate', phonetic: '/ˈkɔː.pər.ət/', meaning: 'Thuộc tập đoàn lớn, mang tính doanh nghiệp', example: 'Corporate responsibility requires businesses to act ethically, not just profitably.' },
      { word: 'turnover', phonetic: '/ˈtɜːnˌəʊ.vər/', meaning: 'Doanh thu trong kỳ kinh doanh', example: 'The company reported a turnover of two million pounds last year.' },
      { word: 'takeover', phonetic: '/ˈteɪkˌəʊ.vər/', meaning: 'Mua lại, thâu tóm công ty khác', example: 'The hostile takeover bid was rejected by the company\'s board.' },
      { word: 'strategic', phonetic: '/strəˈtiː.dʒɪk/', meaning: 'Mang tính chiến lược, có kế hoạch dài hạn', example: 'The two firms formed a strategic partnership to develop new markets.' },
      { word: 'retail', phonetic: '/ˈriː.teɪl/', meaning: 'Bán lẻ trực tiếp đến người tiêu dùng', example: 'Online retail has grown dramatically at the expense of physical stores.' },
      { word: 'recruitment', phonetic: '/rɪˈkruːt.mənt/', meaning: 'Quy trình tuyển dụng nhân sự', example: 'The recruitment process for senior management roles can take months.' },
      { word: 'gross', phonetic: '/grəʊs/', meaning: 'Tổng (lợi nhuận trước khi trừ chi phí)', example: 'The company\'s gross profit was impressive despite rising costs.' },
      { word: 'establishment', phonetic: '/ɪˈstæb.lɪʃ.mənt/', meaning: 'Cơ sở kinh doanh, tổ chức đã được thành lập', example: 'Several food establishments were closed after failing hygiene inspections.' },
      { word: 'premises', phonetic: '/ˈprem.ɪ.sɪz/', meaning: 'Mặt bằng, cơ sở vật chất của doanh nghiệp', example: 'Smoking is not permitted on company premises at any time.' },
      { word: 'renewal', phonetic: '/rɪˈnjuː.əl/', meaning: 'Gia hạn hợp đồng, thỏa thuận', example: 'The contract is up for renewal at the end of the financial year.' },
      { word: 'producer', phonetic: '/prəˈdjuː.sər/', meaning: 'Nhà sản xuất, đơn vị chế tạo hàng hóa', example: 'Brazil is the world\'s largest producer of coffee.' },
      { word: 'proposition', phonetic: '/ˌprɒp.əˈzɪʃ.ən/', meaning: 'Đề xuất, lời mời hợp tác kinh doanh', example: 'The investor made a business proposition that the team found difficult to refuse.' },
      { word: 'speciality', phonetic: '/ˌspeʃ.iˈæl.ə.ti/', meaning: 'Sản phẩm đặc trưng, thế mạnh nổi bật', example: 'Traditional pottery is the speciality of this mountain village.' },
    ]
  },

  {
    id: 'c1_emotions', name: 'Emotions & Wellbeing', nameVi: 'Cảm xúc & Sức khỏe Tâm thần',
    icon: '💭', color: '#7C3AED',
    words: [
      { word: 'hatred', phonetic: '/ˈheɪ.trɪd/', meaning: 'Lòng căm ghét mãnh liệt', example: 'Years of injustice can turn frustration into deep-seated hatred.' },
      { word: 'loneliness', phonetic: '/ˈləʊn.li.nəs/', meaning: 'Sự cô đơn, trạng thái cô lập về mặt cảm xúc', example: 'Urban loneliness is a growing mental health issue in modern cities.' },
      { word: 'annoyance', phonetic: '/əˈnɔɪ.ənts/', meaning: 'Sự bực bội, khó chịu', example: 'She tried to hide her annoyance when the meeting was postponed again.' },
      { word: 'jealousy', phonetic: '/ˈdʒel.ə.si/', meaning: 'Sự ghen tuông, ghen tị với người khác', example: 'Jealousy can damage even the closest of friendships.' },
      { word: 'self-esteem', phonetic: '/ˌself.ɪˈstiːm/', meaning: 'Lòng tự trọng, sự tự tin vào bản thân', example: 'Low self-esteem is often a key factor in depression and anxiety.' },
      { word: 'harassment', phonetic: '/ˈhær.əs.mənt/', meaning: 'Sự quấy rối, hành vi gây phiền nhiễu', example: 'The company introduced strict policies against workplace harassment.' },
      { word: 'insecure', phonetic: '/ˌɪn.sɪˈkjʊər/', meaning: 'Thiếu tự tin, không chắc về bản thân', example: 'She felt insecure about her performance despite her manager\'s praise.' },
      { word: 'aggression', phonetic: '/əˈgreʃ.ən/', meaning: 'Sự hung hăng, tính gây hấn', example: 'Aggression in young children is often a sign of emotional distress.' },
      { word: 'sensitivity', phonetic: '/ˌsent.sɪˈtɪv.ə.ti/', meaning: 'Sự nhạy cảm, khả năng cảm nhận cảm xúc', example: 'Cultural sensitivity is essential when working in international environments.' },
      { word: 'fright', phonetic: '/fraɪt/', meaning: 'Cơn hoảng sợ bất ngờ', example: 'The sudden noise gave everyone in the room a terrible fright.' },
      { word: 'considerate', phonetic: '/kənˈsɪd.ə.rət/', meaning: 'Ân cần, quan tâm đến cảm xúc người khác', example: 'A considerate colleague always thinks about how their actions affect the team.' },
      { word: 'insensitive', phonetic: '/ɪnˈsen.sə.tɪv/', meaning: 'Thiếu tế nhị, vô cảm với nỗi đau người khác', example: 'His insensitive comment upset several members of the audience.' },
      { word: 'prejudiced', phonetic: '/ˈpredʒ.ə.dɪst/', meaning: 'Mang thành kiến, định kiến bất công', example: 'A prejudiced employer may unconsciously favour certain types of candidates.' },
      { word: 'reinforce', phonetic: '/ˌriː.ɪnˈfɔːs/', meaning: 'Củng cố, làm mạnh thêm cảm xúc hoặc niềm tin', example: 'Praise from parents reinforces a child\'s confidence and motivation.' },
      { word: 'subjective', phonetic: '/səbˈdʒek.tɪv/', meaning: 'Mang tính chủ quan, bị ảnh hưởng bởi cảm xúc', example: 'Opinions about art are highly subjective and vary from person to person.' },
    ]
  },

  {
    id: 'c1_institutions', name: 'Society & Institutions', nameVi: 'Xã hội & Thể chế',
    icon: '🏛️', color: '#0891B2',
    words: [
      { word: 'authority', phonetic: '/ɔːˈθɒr.ə.ti/', meaning: 'Cơ quan chức năng có quyền lực', example: 'The local authority announced plans to improve public transport.' },
      { word: 'elite', phonetic: '/ɪˈliːt/', meaning: 'Tầng lớp ưu tú, nhóm nắm quyền lực nhất', example: 'Access to top universities remains dominated by the social elite.' },
      { word: 'empire', phonetic: '/ˈem.paɪər/', meaning: 'Đế chế, tập hợp lãnh thổ dưới một quyền kiểm soát', example: 'The Roman Empire stretched from Britain to the Middle East at its peak.' },
      { word: 'foundation', phonetic: '/faʊnˈdeɪ.ʃən/', meaning: 'Nền tảng, sự thành lập tổ chức', example: 'The foundation of the United Nations was a landmark moment in history.' },
      { word: 'funding', phonetic: '/ˈfʌnd.ɪŋ/', meaning: 'Nguồn tài trợ, kinh phí từ chính phủ hoặc tổ chức', example: 'Government funding for arts programmes was cut significantly this year.' },
      { word: 'industrialization', phonetic: '/ɪnˌdʌs.tri.ə.laɪˈzeɪ.ʃən/', meaning: 'Quá trình công nghiệp hóa', example: 'Rapid industrialization in the 19th century transformed European society.' },
      { word: 'leadership', phonetic: '/ˈliː.də.ʃɪp/', meaning: 'Năng lực lãnh đạo, vị trí lãnh đạo', example: 'Strong leadership is critical during times of national crisis.' },
      { word: 'military', phonetic: '/ˈmɪl.ɪ.tri/', meaning: 'Quân đội, lực lượng vũ trang', example: 'The government increased the military budget in response to regional tensions.' },
      { word: 'ministry', phonetic: '/ˈmɪn.ɪ.stri/', meaning: 'Bộ (cơ quan nhà nước)', example: 'The Ministry of Education launched a new literacy programme in rural schools.' },
      { word: 'civil', phonetic: '/ˈsɪv.əl/', meaning: 'Dân sự, không thuộc quân sự', example: 'Civil unrest spread across the country following the disputed election results.' },
      { word: 'anti-social', phonetic: '/ˌæn.tɪˈsəʊ.ʃəl/', meaning: 'Gây hại cho cộng đồng, chống lại xã hội', example: 'Vandalism and graffiti are considered anti-social behaviour under the law.' },
      { word: 'customary', phonetic: '/ˈkʌs.təm.ər.i/', meaning: 'Theo phong tục, thông lệ của xã hội', example: 'It is customary in many cultures to bring a gift when visiting someone\'s home.' },
      { word: 'conquer', phonetic: '/ˈkɒŋ.kər/', meaning: 'Chinh phục, giành quyền kiểm soát bằng vũ lực', example: 'Alexander the Great conquered much of the known world by the age of thirty.' },
      { word: 'primitive', phonetic: '/ˈprɪm.ɪ.tɪv/', meaning: 'Nguyên thủy, thuộc giai đoạn phát triển sớm', example: 'Primitive societies relied on hunting and gathering for their food supply.' },
      { word: 'peasant', phonetic: '/ˈpez.ənt/', meaning: 'Nông dân nghèo, thường ở nước đang phát triển', example: 'The peasants had little land and depended on wealthy landowners for survival.' },
      { word: 'subsidy', phonetic: '/ˈsʌb.sɪ.di/', meaning: 'Tiền trợ cấp từ chính phủ hoặc tổ chức', example: 'Government subsidies help farmers who face losses due to bad harvests.' },
      { word: 'regulation', phonetic: '/ˌreg.jʊˈleɪ.ʃən/', meaning: 'Quy định, luật lệ chính thức', example: 'Strict financial regulations were introduced after the banking crisis.' },
      { word: 'personnel', phonetic: '/ˌpɜː.sənˈel/', meaning: 'Nhân viên, nhân sự của tổ chức', example: 'All personnel must complete the mandatory health and safety training.' },
    ]
  },

  {
    id: 'c1_language', name: 'Language & Learning', nameVi: 'Ngôn ngữ & Học thuật',
    icon: '📖', color: '#F59E0B',
    words: [
      { word: 'bilingual', phonetic: '/baɪˈlɪŋg.wəl/', meaning: 'Thông thạo hai ngôn ngữ', example: 'Bilingual children often develop stronger problem-solving and cognitive skills.' },
      { word: 'slang', phonetic: '/slæŋ/', meaning: 'Tiếng lóng, ngôn ngữ không chính thức', example: 'Teenagers often develop their own slang that parents cannot understand.' },
      { word: 'linguistic', phonetic: '/lɪŋˈgwɪs.tɪk/', meaning: 'Thuộc về ngôn ngữ, ngôn ngữ học', example: 'The study identified interesting linguistic differences between urban and rural communities.' },
      { word: 'register', phonetic: '/ˈredʒ.ɪ.stər/', meaning: 'Phong cách ngôn ngữ phù hợp với từng hoàn cảnh', example: 'Students must learn to switch register between formal essays and casual conversation.' },
      { word: 'analytical', phonetic: '/ˌæn.əlˈɪt.ɪ.kəl/', meaning: 'Mang tính phân tích, tư duy phân tích', example: 'IELTS writing tasks require candidates to demonstrate strong analytical skills.' },
      { word: 'dissertation', phonetic: '/ˌdɪs.əˈteɪ.ʃən/', meaning: 'Luận văn tốt nghiệp, nghiên cứu học thuật dài', example: 'She spent two years writing her doctoral dissertation on ancient languages.' },
      { word: 'gifted', phonetic: '/ˈgɪf.tɪd/', meaning: 'Có năng khiếu bẩm sinh, tài năng thiên bẩm', example: 'The gifted student received a full scholarship to study at Oxford.' },
      { word: 'insight', phonetic: '/ˈɪn.saɪt/', meaning: 'Sự thấu hiểu sâu sắc, cái nhìn thấu đáo', example: 'Reading widely gives students valuable insight into different cultures and ideas.' },
      { word: 'formal', phonetic: '/ˈfɔː.məl/', meaning: 'Chính quy, theo hệ thống giáo dục chính thức', example: 'Many successful entrepreneurs lack formal education but have strong practical skills.' },
      { word: 'workshop', phonetic: '/ˈwɜːk.ʃɒp/', meaning: 'Hội thảo thực hành, buổi học theo nhóm', example: 'The writing workshop gave participants feedback on their drafts from experienced authors.' },
      { word: 'simulation', phonetic: '/ˌsɪm.jəˈleɪ.ʃən/', meaning: 'Mô phỏng tình huống thực tế để học tập', example: 'A flight simulation allowed trainee pilots to practise emergency procedures safely.' },
      { word: 'well-educated', phonetic: '/ˌwelˈedʒ.ʊ.keɪ.tɪd/', meaning: 'Có học vấn cao, được đào tạo bài bản', example: 'Being well-educated does not guarantee success without social skills and drive.' },
      { word: 'trainee', phonetic: '/treɪˈniː/', meaning: 'Học viên, người đang trong giai đoạn đào tạo', example: 'All trainees are required to complete a written assessment at the end of the programme.' },
      { word: 'comprehensively', phonetic: '/ˌkɒm.prɪˈhent.sɪv.li/', meaning: 'Một cách toàn diện, đầy đủ không thiếu sót', example: 'The report comprehensively addressed all aspects of the education system.' },
      { word: 'qualification', phonetic: '/ˌkwɒl.ɪ.fəˈkeɪ.ʃən/', meaning: 'Bằng cấp, chứng chỉ chuyên môn', example: 'Employers often require a degree-level qualification for managerial positions.' },
    ]
  },

  // ── 4 new C1 topics ───────────────────────────────────────────
  {
    id: 'c1_journalism', name: 'Media & Journalism', nameVi: 'Truyền thông & Báo chí',
    icon: '📰', color: '#26A69A',
    words: [
      { word: 'investigative', phonetic: '/ɪnˈves.tɪ.ɡə.tɪv/', meaning: 'Mang tính điều tra (báo chí)', example: 'Investigative journalism uncovered widespread corruption within the government.' },
      { word: 'impartiality', phonetic: '/ɪmˌpɑː.ʃiˈæl.ɪ.ti/', meaning: 'Tính khách quan, vô tư', example: 'The broadcaster has a legal obligation to maintain impartiality in its reporting.' },
      { word: 'editorial', phonetic: '/ˌed.ɪˈtɔː.ri.əl/', meaning: 'Xã luận, bài bình luận của ban biên tập', example: 'The newspaper published an editorial criticising the government\'s handling of the crisis.' },
      { word: 'censorship', phonetic: '/ˈsen.sə.ʃɪp/', meaning: 'Kiểm duyệt', example: 'Critics accused the authorities of imposing censorship on online content.' },
      { word: 'circulation', phonetic: '/ˌsɜː.kjʊˈleɪ.ʃən/', meaning: 'Số lượng phát hành (báo)', example: 'Print newspaper circulation has declined sharply with the rise of digital media.' },
      { word: 'propaganda', phonetic: '/ˌprɒp.əˈɡæn.də/', meaning: 'Tuyên truyền một chiều, thiên vị', example: 'State-controlled media is often used to spread propaganda.' },
      { word: 'correspondent', phonetic: '/ˌkɒr.ɪˈspɒn.dənt/', meaning: 'Phóng viên đặc biệt ở nước ngoài', example: 'The foreign correspondent reported live from the conflict zone.' },
      { word: 'sensationalism', phonetic: '/senˈseɪ.ʃən.əl.ɪz.əm/', meaning: 'Tính giật gân, thổi phồng tin tức', example: 'Sensationalism in tabloid journalism prioritises shock value over factual accuracy.' },
      { word: 'press freedom', phonetic: '/ˈpres ˌfriː.dəm/', meaning: 'Tự do báo chí', example: 'Press freedom is considered a cornerstone of democratic societies.' },
      { word: 'disinformation', phonetic: '/ˌdɪs.ɪn.fəˈmeɪ.ʃən/', meaning: 'Thông tin sai lệch cố ý', example: 'Governments are struggling to combat the spread of disinformation online.' },
      { word: 'paywall', phonetic: '/ˈpeɪ.wɔːl/', meaning: 'Hàng rào trả phí truy cập nội dung', example: 'Many newspapers have introduced a paywall to generate revenue from online readers.' },
      { word: 'libel', phonetic: '/ˈlaɪ.bəl/', meaning: 'Tội phỉ báng bằng văn bản', example: 'The politician threatened to sue the magazine for libel.' },
      { word: 'syndication', phonetic: '/ˌsɪn.dɪˈkeɪ.ʃən/', meaning: 'Phân phối nội dung cho nhiều kênh', example: 'The article was sold through syndication to newspapers across the country.' },
      { word: 'media literacy', phonetic: '/ˈmiː.di.ə ˈlɪt.ər.ə.si/', meaning: 'Năng lực đọc hiểu và đánh giá thông tin truyền thông', example: 'Schools are incorporating media literacy into the curriculum to help students evaluate sources.' },
      { word: 'op-ed', phonetic: '/ˌɒpˈed/', meaning: 'Bài viết bình luận độc lập (không phải xã luận)', example: 'She wrote an op-ed for a national newspaper about climate policy.' },
    ]
  },
  {
    id: 'c1_arts_music', name: 'Art & Music Appreciation', nameVi: 'Nghệ thuật & Âm nhạc',
    icon: '🎨', color: '#FF7043',
    words: [
      { word: 'connoisseur', phonetic: '/ˌkɒn.əˈsɜːr/', meaning: 'Người am hiểu, chuyên gia thẩm định nghệ thuật', example: 'A connoisseur of modern art, she recognised the painting\'s immense value immediately.' },
      { word: 'renaissance', phonetic: '/rɪˈneɪ.səns/', meaning: 'Thời kỳ Phục Hưng; sự hồi sinh', example: 'The Renaissance produced some of the world\'s greatest artistic achievements.' },
      { word: 'symphony', phonetic: '/ˈsɪm.fə.ni/', meaning: 'Bản giao hưởng', example: 'Beethoven\'s Ninth Symphony is considered one of the greatest musical compositions.' },
      { word: 'genre', phonetic: '/ˈʒɒn.rə/', meaning: 'Thể loại nghệ thuật, âm nhạc', example: 'Jazz is a genre that blends African rhythms with European musical structures.' },
      { word: 'abstract', phonetic: '/ˈæb.strækt/', meaning: 'Trừu tượng (nghệ thuật)', example: 'Abstract art does not attempt to represent an accurate depiction of reality.' },
      { word: 'portraiture', phonetic: '/ˈpɔː.trɪ.tʃər/', meaning: 'Nghệ thuật vẽ chân dung', example: 'Portraiture was the dominant art form for wealthy patrons during the 18th century.' },
      { word: 'improvisation', phonetic: '/ɪmˌprɒv.ɪˈzeɪ.ʃən/', meaning: 'Ứng tấu, ứng diễn', example: 'Jazz musicians are famous for their skill at improvisation during live performances.' },
      { word: 'aesthetics', phonetic: '/iːsˈθet.ɪks/', meaning: 'Mỹ học, triết học về cái đẹp', example: 'The course explored the aesthetics of Modernism across painting and sculpture.' },
      { word: 'patronage', phonetic: '/ˈpeɪ.trən.ɪdʒ/', meaning: 'Sự bảo trợ nghệ thuật', example: 'Without wealthy patronage, many Renaissance artists could not have created their masterpieces.' },
      { word: 'curator', phonetic: '/kjʊˈreɪ.tər/', meaning: 'Người quản lý bộ sưu tập bảo tàng', example: 'The museum curator organised a touring exhibition of Impressionist paintings.' },
      { word: 'composition', phonetic: '/ˌkɒm.pəˈzɪʃ.ən/', meaning: 'Bố cục hội họa, tác phẩm âm nhạc', example: 'The painting\'s composition draws the viewer\'s eye towards the central figure.' },
      { word: 'motif', phonetic: '/məʊˈtiːf/', meaning: 'Chủ đề, họa tiết lặp lại', example: 'The floral motif appears throughout the artist\'s later works.' },
      { word: 'tempo', phonetic: '/ˈtem.pəʊ/', meaning: 'Nhịp độ âm nhạc', example: 'The orchestra shifted to a faster tempo as the piece reached its climax.' },
      { word: 'retrospective', phonetic: '/ˌret.rəˈspek.tɪv/', meaning: 'Triển lãm nhìn lại toàn bộ sự nghiệp', example: 'The gallery held a retrospective of the sculptor\'s 40-year career.' },
      { word: 'avant-garde', phonetic: '/ˌæv.ɒ̃ˈɡɑːd/', meaning: 'Nghệ thuật tiên phong, thử nghiệm', example: 'The exhibition featured avant-garde works that challenged traditional artistic conventions.' },
      { word: 'audition', phonetic: '/ɔːˈdɪ.ʃən/', meaning: 'Buổi thử giọng hoặc thử vai diễn', example: 'She spent weeks preparing for her audition at the national theatre.' },
      { word: 'cinema', phonetic: '/ˈsɪn.ə.mə/', meaning: 'Điện ảnh, nghệ thuật làm phim', example: 'Italian cinema of the 1960s had a profound influence on world film.' },
      { word: 'musical', phonetic: '/ˈmjuː.zɪ.kəl/', meaning: 'Có năng khiếu âm nhạc; liên quan đến âm nhạc', example: 'She has always had a great musical talent and began composing at age ten.' },
    ]
  },
  {
    id: 'c1_mental_health', name: 'Psychology & Mental Health', nameVi: 'Tâm lý học & Sức khỏe tâm thần',
    icon: '🧠', color: '#7E57C2',
    words: [
      { word: 'cognitive', phonetic: '/ˈkɒɡ.nɪ.tɪv/', meaning: 'Thuộc về nhận thức', example: 'Cognitive behavioural therapy is widely used to treat anxiety disorders.' },
      { word: 'resilience', phonetic: '/rɪˈzɪl.i.əns/', meaning: 'Khả năng phục hồi, sức bật tâm lý', example: 'Building emotional resilience helps individuals cope with stress and adversity.' },
      { word: 'stigma', phonetic: '/ˈstɪɡ.mə/', meaning: 'Kỳ thị xã hội', example: 'There remains a significant stigma attached to mental illness in many societies.' },
      { word: 'trauma', phonetic: '/ˈtrɔː.mə/', meaning: 'Chấn thương tâm lý', example: 'Unresolved childhood trauma can manifest in anxiety and depression in adulthood.' },
      { word: 'phobia', phonetic: '/ˈfəʊ.bi.ə/', meaning: 'Nỗi ám ảnh, chứng sợ hãi bất hợp lý', example: 'Her phobia of flying prevented her from accepting several job opportunities abroad.' },
      { word: 'compulsive', phonetic: '/kəmˈpʌl.sɪv/', meaning: 'Bị thôi thúc bởi xung động tâm lý, không kiểm soát được', example: 'Compulsive behaviour can disrupt a person\'s daily life and relationships.' },
      { word: 'empathy', phonetic: '/ˈem.pə.θi/', meaning: 'Sự đồng cảm, khả năng cảm nhận cảm xúc người khác', example: 'Empathy is a crucial skill for anyone working in a caring profession.' },
      { word: 'subconscious', phonetic: '/ˌsʌbˈkɒn.ʃəs/', meaning: 'Tiềm thức', example: 'Many of our daily decisions are influenced by subconscious biases.' },
      { word: 'therapeutic', phonetic: '/ˌθer.əˈpjuː.tɪk/', meaning: 'Có tác dụng trị liệu', example: 'Spending time in nature can have a deeply therapeutic effect on mental wellbeing.' },
      { word: 'burnout', phonetic: '/ˈbɜːn.aʊt/', meaning: 'Kiệt sức do làm việc quá mức', example: 'Burnout is increasingly common among healthcare workers following the pandemic.' },
      { word: 'mindfulness', phonetic: '/ˈmaɪnd.fəl.nəs/', meaning: 'Chánh niệm, chú ý có ý thức vào hiện tại', example: 'Practising mindfulness meditation can reduce stress and improve concentration.' },
      { word: 'narcissism', phonetic: '/ˈnɑː.sɪ.sɪz.əm/', meaning: 'Chứng tự ái thái quá', example: 'Research suggests that social media can reinforce tendencies towards narcissism.' },
      { word: 'dissociation', phonetic: '/dɪˌsəʊ.si.ˈeɪ.ʃən/', meaning: 'Sự phân ly tâm lý, tách rời khỏi thực tại', example: 'Dissociation is a psychological defence mechanism triggered by extreme stress.' },
      { word: 'intervention', phonetic: '/ˌɪn.təˈven.ʃən/', meaning: 'Sự can thiệp trị liệu, y tế', example: 'Early intervention is key to preventing mild mental health issues from worsening.' },
      { word: 'anxiety disorder', phonetic: '/æŋˈzaɪ.ə.ti dɪsˌɔː.dər/', meaning: 'Rối loạn lo âu', example: 'Anxiety disorders are among the most common mental health conditions worldwide.' },
    ]
  },
  {
    id: 'c1_sport_science', name: 'Sport Science & Physiology', nameVi: 'Khoa học thể thao & Sinh lý học',
    icon: '🏃', color: '#EF5350',
    words: [
      { word: 'endurance', phonetic: '/ɪnˈdjʊər.əns/', meaning: 'Sức bền', example: 'Marathon running requires exceptional cardiovascular endurance.' },
      { word: 'metabolism', phonetic: '/məˈtæb.ə.lɪz.əm/', meaning: 'Quá trình trao đổi chất', example: 'Regular exercise boosts the metabolism and helps maintain a healthy body weight.' },
      { word: 'cardiovascular', phonetic: '/ˌkɑː.di.əʊˈvæs.kjʊ.lər/', meaning: 'Thuộc về tim mạch', example: 'Cardiovascular fitness is a key component of overall health and athletic performance.' },
      { word: 'biomechanics', phonetic: '/ˌbaɪ.əʊ.mɪˈkæn.ɪks/', meaning: 'Cơ sinh học ứng dụng trong thể thao', example: 'Sports scientists use biomechanics to analyse and improve an athlete\'s technique.' },
      { word: 'doping', phonetic: '/ˈdəʊ.pɪŋ/', meaning: 'Sử dụng chất kích thích cấm trong thể thao', example: 'Doping scandals have damaged the reputation of professional cycling.' },
      { word: 'ligament', phonetic: '/ˈlɪɡ.ə.mənt/', meaning: 'Dây chằng', example: 'She suffered a torn ligament during the football match and required surgery.' },
      { word: 'aerobic', phonetic: '/eəˈrəʊ.bɪk/', meaning: 'Hiếu khí, bài tập cường độ vừa cần oxy', example: 'Aerobic exercise such as jogging improves lung capacity and stamina.' },
      { word: 'hydration', phonetic: '/haɪˈdreɪ.ʃən/', meaning: 'Sự cấp nước cho cơ thể', example: 'Proper hydration is essential for maintaining peak athletic performance.' },
      { word: 'overtraining', phonetic: '/ˌəʊ.vəˈtreɪ.nɪŋ/', meaning: 'Tập luyện quá mức', example: 'Overtraining can lead to injury, fatigue and a decline in performance.' },
      { word: 'anaerobic', phonetic: '/ˌæn.eəˈrəʊ.bɪk/', meaning: 'Kỵ khí, bài tập cường độ cao không cần oxy', example: 'Sprinting is an anaerobic activity that demands short bursts of maximum power.' },
      { word: 'lactic acid', phonetic: '/ˌlæk.tɪk ˈæs.ɪd/', meaning: 'Axit lactic gây mỏi cơ', example: 'Lactic acid builds up in muscles during intense exercise, causing a burning sensation.' },
      { word: 'periodisation', phonetic: '/ˌpɪər.i.ə.daɪˈzeɪ.ʃən/', meaning: 'Chu kỳ hóa tập luyện, phân chia giai đoạn huấn luyện', example: 'Periodisation allows athletes to peak in performance at the time of major competitions.' },
      { word: 'proprioception', phonetic: '/ˌprəʊ.pri.əˈsep.ʃən/', meaning: 'Cảm giác vị thế cơ thể', example: 'Proprioception training helps athletes improve balance and coordination.' },
      { word: 'rehabilitation', phonetic: '/ˌriː.həˌbɪl.ɪˈteɪ.ʃən/', meaning: 'Phục hồi chức năng sau chấn thương', example: 'The footballer underwent six months of rehabilitation before returning to the pitch.' },
      { word: 'kinesthesia', phonetic: '/ˌkɪn.ɪsˈθiː.zi.ə/', meaning: 'Cảm giác vận động, nhận biết chuyển động cơ thể', example: 'Gymnasts develop exceptional kinesthesia through years of disciplined training.' },
    ]
  },
  {
    id: 'c1_other', name: 'General Academic Vocabulary', nameVi: 'Từ vựng học thuật tổng hợp',
    icon: '📖', color: '#64748B',
    words: [
      { word: 'accomplish', phonetic: '/əˈkʌm.plɪʃ/', meaning: 'Hoàn thành, đạt được điều gì đó khó', example: 'She managed to accomplish all her goals within the first year of the project.' },
      { word: 'acknowledge', phonetic: '/əkˈnɒl.ɪdʒ/', meaning: 'Thừa nhận sự thật hoặc sự tồn tại của điều gì đó', example: 'He refused to acknowledge that he had made a serious mistake.' },
      { word: 'authentic', phonetic: '/ɔːˈθen.tɪk/', meaning: 'Thật sự, chính xác, không giả mạo', example: 'The restaurant serves authentic Thai food prepared using traditional recipes.' },
      { word: 'burden', phonetic: '/ˈbɜː.dən/', meaning: 'Gánh nặng, thứ khó khăn phải chịu đựng', example: 'The financial burden of student loans can follow graduates for many years.' },
      { word: 'consent', phonetic: '/kənˈsent/', meaning: 'Sự cho phép, đồng ý chính thức', example: 'Patients must give their written consent before any medical procedure.' },
      { word: 'counterpart', phonetic: '/ˈkaʊn.tə.pɑːt/', meaning: 'Người hoặc vật có vai trò tương đương', example: 'The prime minister met her French counterpart to discuss trade relations.' },
      { word: 'drawback', phonetic: '/ˈdrɔː.bæk/', meaning: 'Bất lợi, nhược điểm của kế hoạch hoặc tình huống', example: 'The main drawback of remote working is the lack of face-to-face collaboration.' },
      { word: 'duration', phonetic: '/djʊəˈreɪ.ʃən/', meaning: 'Khoảng thời gian kéo dài của sự việc', example: 'The total duration of the training course is six months.' },
      { word: 'eligible', phonetic: '/ˈel.ɪ.dʒə.bl̩/', meaning: 'Đủ điều kiện, đủ tiêu chuẩn để làm gì đó', example: 'You must be over 18 to be eligible to vote in a general election.' },
      { word: 'diminish', phonetic: '/dɪˈmɪn.ɪʃ/', meaning: 'Giảm dần về kích thước, tầm quan trọng hoặc sức mạnh', example: 'His influence within the party began to diminish after the scandal broke.' },
      { word: 'campaign', phonetic: '/kæmˈpeɪn/', meaning: 'Chiến dịch có tổ chức nhằm đạt mục tiêu cụ thể', example: 'The charity launched a major campaign to raise awareness about food poverty.' },
      { word: 'boundary', phonetic: '/ˈbaʊn.dər.i/', meaning: 'Ranh giới, giới hạn giữa hai vùng hoặc hai khái niệm', example: 'Scientists are constantly pushing the boundaries of what is technically possible.' },
      { word: 'deficiency', phonetic: '/dɪˈfɪʃ.ən.si/', meaning: 'Sự thiếu hụt về chất lượng hoặc số lượng', example: 'A vitamin D deficiency can cause fatigue, bone pain, and weakened immunity.' },
      { word: 'downside', phonetic: '/ˈdaʊn.saɪd/', meaning: 'Mặt bất lợi, nhược điểm của tình huống', example: 'The downside of living in the city centre is the constant noise and high rent.' },
      { word: 'amateur', phonetic: '/ˈæm.ə.tər/', meaning: 'Người làm gì đó vì sở thích, không chuyên nghiệp', example: 'As an amateur photographer, he enters local competitions but does not earn money from it.' },
    ]
  },

];
