const TOPICS_IELTS = [
  {
    id: 'ielts_writing', name: 'Academic Writing', nameVi: 'Viết Học thuật',
    icon: '📝', color: '#8B5CF6',
    words: [
      { word: 'paraphrase', phonetic: '/ˈpær.ə.freɪz/', meaning: 'Diễn đạt lại bằng từ ngữ khác', example: 'Students must paraphrase the source material rather than copy it directly.' },
      { word: 'coherent', phonetic: '/kəʊˈhɪər.ənt/', meaning: 'Mạch lạc, có sự liên kết chặt chẽ', example: 'A coherent argument requires clear evidence and logical transitions.' },
      { word: 'substantiate', phonetic: '/səbˈstæn.ʃi.eɪt/', meaning: 'Chứng minh bằng bằng chứng cụ thể', example: 'The researcher failed to substantiate her claims with reliable data.' },
      { word: 'discrepancy', phonetic: '/dɪˈskrep.ən.si/', meaning: 'Sự mâu thuẫn, không nhất quán', example: 'There is a discrepancy between the reported figures and the actual results.' },
      { word: 'concise', phonetic: '/kənˈsaɪs/', meaning: 'Ngắn gọn, súc tích', example: 'IELTS essays must be concise yet comprehensive within the word limit.' },
      { word: 'implication', phonetic: '/ˌɪm.plɪˈkeɪ.ʃən/', meaning: 'Hàm ý, tác động tiềm ẩn', example: 'The study has important implications for public health policy.' },
      { word: 'contention', phonetic: '/kənˈten.ʃən/', meaning: 'Luận điểm, quan điểm tranh luận', example: 'The author\'s central contention is that technology reduces human connection.' },
      { word: 'corroborate', phonetic: '/kəˈrɒb.ər.eɪt/', meaning: 'Xác nhận, củng cố thêm bằng chứng', example: 'Multiple studies corroborate the link between diet and mental health.' },
      { word: 'exemplify', phonetic: '/ɪɡˈzem.plɪ.faɪ/', meaning: 'Minh họa bằng ví dụ cụ thể', example: 'Japan exemplifies how a nation can balance tradition with modernity.' },
      { word: 'contradict', phonetic: '/ˌkɒn.trəˈdɪkt/', meaning: 'Mâu thuẫn, phủ nhận lập luận', example: 'The new findings contradict earlier assumptions about climate patterns.' },
      { word: 'acknowledge', phonetic: '/əkˈnɒl.ɪdʒ/', meaning: 'Thừa nhận, công nhận điều gì đó', example: 'The essay acknowledges the limitations of the proposed solution.' },
      { word: 'tentative', phonetic: '/ˈten.tə.tɪv/', meaning: 'Tạm thời, chưa dứt khoát', example: 'Researchers drew tentative conclusions pending further investigation.' },
      { word: 'premise', phonetic: '/ˈprem.ɪs/', meaning: 'Tiền đề, cơ sở của lập luận', example: 'The argument rests on the premise that economic growth benefits all.' },
      { word: 'succinct', phonetic: '/səkˈsɪŋkt/', meaning: 'Ngắn gọn, đúng trọng tâm', example: 'Her succinct introduction clearly outlined the scope of the essay.' },
      { word: 'hedging', phonetic: '/ˈhedʒ.ɪŋ/', meaning: 'Dùng ngôn ngữ thận trọng, tránh khẳng định tuyệt đối', example: 'Academic writing often uses hedging language such as "it appears" or "may suggest".' },
    ]
  },
  {
    id: 'ielts_urban', name: 'Urban Planning', nameVi: 'Quy hoạch Đô thị',
    icon: '🏙️', color: '#0369A1',
    words: [
      { word: 'amenity', phonetic: '/əˈmiː.nɪ.ti/', meaning: 'Tiện nghi, tiện ích công cộng', example: 'The new district lacks basic amenities such as parks and libraries.' },
      { word: 'commute', phonetic: '/kəˈmjuːt/', meaning: 'Đi lại hàng ngày giữa nhà và nơi làm việc', example: 'Long commutes reduce employees\' quality of life and productivity.' },
      { word: 'congestion', phonetic: '/kənˈdʒes.tʃən/', meaning: 'Tắc nghẽn giao thông', example: 'Congestion charging has reduced traffic in many city centres.' },
      { word: 'regeneration', phonetic: '/rɪˌdʒen.əˈreɪ.ʃən/', meaning: 'Tái phát triển, hồi sinh khu đô thị', example: 'Urban regeneration transformed the abandoned docklands into a cultural hub.' },
      { word: 'blueprint', phonetic: '/ˈbluː.prɪnt/', meaning: 'Bản kế hoạch tổng thể chi tiết', example: 'The government released a blueprint for sustainable urban development.' },
      { word: 'retrofit', phonetic: '/ˈret.rəʊ.fɪt/', meaning: 'Nâng cấp, cải tạo công trình cũ', example: 'Retrofitting old buildings with solar panels can cut energy costs significantly.' },
      { word: 'corridor', phonetic: '/ˈkɒr.ɪ.dɔːr/', meaning: 'Hành lang giao thông, trục kết nối đô thị', example: 'A new transport corridor will link the airport to the city centre.' },
      { word: 'precinct', phonetic: '/ˈpriː.sɪŋkt/', meaning: 'Khu vực đô thị, phân khu hành chính', example: 'The shopping precinct was redesigned to allow pedestrian access only.' },
      { word: 'allocate', phonetic: '/ˈæl.ə.keɪt/', meaning: 'Phân bổ, phân phối nguồn lực', example: 'The council allocated funds specifically for low-income housing.' },
      { word: 'tenure', phonetic: '/ˈten.jər/', meaning: 'Quyền sở hữu hoặc sử dụng đất nhà', example: 'Secure land tenure encourages communities to invest in local infrastructure.' },
      { word: 'encroach', phonetic: '/ɪnˈkrəʊtʃ/', meaning: 'Lấn chiếm, xâm phạm không gian', example: 'Urban development continues to encroach on protected green spaces.' },
      { word: 'aesthetic', phonetic: '/esˈθet.ɪk/', meaning: 'Thuộc về thẩm mỹ, vẻ đẹp kiến trúc', example: 'The architect prioritised aesthetic harmony between old and new buildings.' },
      { word: 'proximity', phonetic: '/prɒkˈsɪm.ɪ.ti/', meaning: 'Khoảng cách gần, vị trí lân cận', example: 'Property values rise with proximity to public transport hubs.' },
      { word: 'hinterland', phonetic: '/ˈhɪn.tə.lænd/', meaning: 'Vùng ngoại ô, vùng phụ cận đô thị', example: 'Businesses in the hinterland depend on urban centres for services.' },
      { word: 'thoroughfare', phonetic: '/ˈθʌr.ə.feər/', meaning: 'Đường giao thông chính, phố lớn', example: 'The main thoroughfare was closed for the weekend festival.' },
    ]
  },
  {
    id: 'ielts_global_trade', name: 'Global Trade', nameVi: 'Thương mại Toàn cầu',
    icon: '🌐', color: '#0891B2',
    words: [
      { word: 'tariff', phonetic: '/ˈtær.ɪf/', meaning: 'Thuế quan, biểu thuế nhập khẩu', example: 'High tariffs on imported goods protect domestic manufacturers.' },
      { word: 'quota', phonetic: '/ˈkwəʊ.tə/', meaning: 'Hạn ngạch, giới hạn số lượng thương mại', example: 'Import quotas limit the volume of foreign goods entering the market.' },
      { word: 'outsource', phonetic: '/ˌaʊtˈsɔːs/', meaning: 'Thuê ngoài, chuyển công việc ra bên ngoài', example: 'Many companies outsource manufacturing to countries with lower labour costs.' },
      { word: 'bilateral', phonetic: '/ˌbaɪˈlæt.ər.əl/', meaning: 'Mang tính song phương, giữa hai bên', example: 'The two nations signed a bilateral trade agreement.' },
      { word: 'subsidy', phonetic: '/ˈsʌb.sɪ.di/', meaning: 'Trợ cấp tài chính của chính phủ', example: 'Agricultural subsidies help farmers compete in global markets.' },
      { word: 'embargo', phonetic: '/ɪmˈbɑː.ɡəʊ/', meaning: 'Lệnh cấm vận thương mại', example: 'The trade embargo severely restricted the country\'s imports and exports.' },
      { word: 'consortium', phonetic: '/kənˈsɔː.ti.əm/', meaning: 'Liên doanh, tập đoàn đa quốc gia', example: 'A consortium of firms won the contract to build the new railway.' },
      { word: 'liberalize', phonetic: '/ˈlɪb.ər.əl.aɪz/', meaning: 'Tự do hóa thương mại, kinh tế', example: 'Efforts to liberalize trade have reduced barriers between member states.' },
      { word: 'remittance', phonetic: '/rɪˈmɪt.əns/', meaning: 'Kiều hối, tiền lao động gửi về nước', example: 'Remittances from abroad are a vital source of income for many developing economies.' },
      { word: 'disparity', phonetic: '/dɪˈspær.ɪ.ti/', meaning: 'Sự chênh lệch, bất bình đẳng', example: 'Economic disparities between regions have widened in recent decades.' },
      { word: 'homogeneous', phonetic: '/ˌhɒm.əˈdʒiː.ni.əs/', meaning: 'Đồng nhất, thuần nhất', example: 'Globalisation risks creating a homogeneous world culture that erases diversity.' },
      { word: 'diversify', phonetic: '/daɪˈvɜː.sɪ.faɪ/', meaning: 'Đa dạng hóa nguồn thu, thị trường', example: 'Developing nations must diversify their economies to reduce dependence on commodities.' },
      { word: 'prevalent', phonetic: '/ˈprev.ə.lənt/', meaning: 'Phổ biến, lan rộng', example: 'The use of mobile payment systems is now prevalent across Asia.' },
      { word: 'emulate', phonetic: '/ˈem.jʊ.leɪt/', meaning: 'Noi gương, bắt chước mô hình thành công', example: 'Several countries seek to emulate Singapore\'s economic development model.' },
      { word: 'procurement', phonetic: '/prəˈkjʊər.mənt/', meaning: 'Mua sắm, đấu thầu chính phủ', example: 'Transparent public procurement reduces corruption in government contracts.' },
    ]
  },
  {
    id: 'ielts_research', name: 'Research & Data', nameVi: 'Nghiên cứu & Dữ liệu',
    icon: '📊', color: '#7C3AED',
    words: [
      { word: 'quantify', phonetic: '/ˈkwɒn.tɪ.faɪ/', meaning: 'Định lượng, đo lường bằng số liệu', example: 'It is difficult to quantify the social impact of poverty reduction programmes.' },
      { word: 'fluctuate', phonetic: '/ˈflʌk.tʃu.eɪt/', meaning: 'Dao động, biến động không ổn định', example: 'Oil prices fluctuated dramatically throughout the decade.' },
      { word: 'plateau', phonetic: '/ˈplæt.əʊ/', meaning: 'Ổn định, đi ngang sau thời kỳ tăng', example: 'Growth in smartphone sales has plateaued in developed markets.' },
      { word: 'surge', phonetic: '/sɜːdʒ/', meaning: 'Tăng đột biến, tăng vọt nhanh chóng', example: 'There was a surge in demand for home office equipment during the pandemic.' },
      { word: 'trajectory', phonetic: '/trəˈdʒek.tər.i/', meaning: 'Xu hướng, chiều hướng phát triển', example: 'The trajectory of renewable energy adoption has steepened in recent years.' },
      { word: 'anomaly', phonetic: '/əˈnɒm.ə.li/', meaning: 'Dị thường, trường hợp bất thường', example: 'The 2020 data shows an anomaly that requires further investigation.' },
      { word: 'benchmark', phonetic: '/ˈbentʃ.mɑːk/', meaning: 'Tiêu chuẩn đối sánh, mốc đánh giá', example: 'Finland\'s education system serves as a global benchmark.' },
      { word: 'parameter', phonetic: '/pəˈræm.ɪ.tər/', meaning: 'Thông số, yếu tố giới hạn phạm vi', example: 'The study defined clear parameters before collecting data.' },
      { word: 'aggregate', phonetic: '/ˈæɡ.rɪ.ɡeɪt/', meaning: 'Tổng hợp, gộp lại từ nhiều nguồn', example: 'Aggregate data from all regions showed an overall decline in crime.' },
      { word: 'longitudinal', phonetic: '/ˌlɒŋ.ɡɪˈtjuː.dɪ.nəl/', meaning: 'Dài hạn, theo dõi theo chiều thời gian', example: 'A longitudinal study tracked participants over a period of twenty years.' },
      { word: 'discernible', phonetic: '/dɪˈsɜː.nɪ.bəl/', meaning: 'Có thể nhận thấy rõ ràng', example: 'There is no discernible difference between the two treatment groups.' },
      { word: 'interrelate', phonetic: '/ˌɪn.tər.rɪˈleɪt/', meaning: 'Có mối liên hệ qua lại, tương tác nhau', example: 'Poverty and poor health outcomes closely interrelate and reinforce each other.' },
      { word: 'variable', phonetic: '/ˈveər.i.ə.bəl/', meaning: 'Biến số, yếu tố có thể thay đổi', example: 'Income level is the most significant variable affecting health outcomes.' },
      { word: 'viable', phonetic: '/ˈvaɪ.ə.bəl/', meaning: 'Khả thi, có thể thực hiện thành công', example: 'Solar energy is now a commercially viable alternative to fossil fuels.' },
      { word: 'replicate', phonetic: '/ˈrep.lɪ.keɪt/', meaning: 'Tái lặp, sao chép thí nghiệm để kiểm chứng', example: 'Scientists failed to replicate the original experiment\'s results.' },
    ]
  },
  {
    id: 'ielts_climate', name: 'Climate & Energy', nameVi: 'Khí hậu & Năng lượng',
    icon: '⚡', color: '#15803D',
    words: [
      { word: 'mitigation', phonetic: '/ˌmɪt.ɪˈɡeɪ.ʃən/', meaning: 'Giảm thiểu tác động tiêu cực', example: 'Climate mitigation strategies aim to reduce greenhouse gas emissions.' },
      { word: 'adaptation', phonetic: '/ˌæd.æpˈteɪ.ʃən/', meaning: 'Sự thích nghi với điều kiện mới', example: 'Coastal communities need adaptation measures to cope with rising sea levels.' },
      { word: 'geothermal', phonetic: '/ˌdʒiː.əʊˈθɜː.məl/', meaning: 'Thuộc về năng lượng địa nhiệt', example: 'Iceland relies heavily on geothermal energy for heating and electricity.' },
      { word: 'tidal', phonetic: '/ˈtaɪ.dəl/', meaning: 'Thuộc về thủy triều, năng lượng thủy triều', example: 'Tidal power stations harness the movement of ocean tides to generate electricity.' },
      { word: 'consumption', phonetic: '/kənˈsʌmp.ʃən/', meaning: 'Mức tiêu thụ năng lượng hoặc tài nguyên', example: 'Per capita energy consumption has risen steadily in emerging economies.' },
      { word: 'threshold', phonetic: '/ˈθreʃ.həʊld/', meaning: 'Ngưỡng giới hạn, mức tới hạn', example: 'Scientists warn that a 1.5°C warming threshold must not be exceeded.' },
      { word: 'depletion', phonetic: '/dɪˈpliː.ʃən/', meaning: 'Sự cạn kiệt, suy giảm nguồn tài nguyên', example: 'The depletion of groundwater reserves poses serious risks to agriculture.' },
      { word: 'subsidence', phonetic: '/ˈsʌb.sɪ.dəns/', meaning: 'Sự sụt lún mặt đất', example: 'Land subsidence caused by excessive groundwater extraction threatens many cities.' },
      { word: 'volatility', phonetic: '/ˌvɒl.əˈtɪl.ɪ.ti/', meaning: 'Sự biến động, không ổn định', example: 'Price volatility in the oil market disrupts national economic planning.' },
      { word: 'feasible', phonetic: '/ˈfiː.zɪ.bəl/', meaning: 'Khả thi, có thể thực hiện được', example: 'A fully renewable energy grid is technically feasible within this decade.' },
      { word: 'adverse', phonetic: '/ˈæd.vɜːs/', meaning: 'Bất lợi, có tác động tiêu cực', example: 'Adverse weather events are increasing in frequency due to climate change.' },
      { word: 'exacerbate', phonetic: '/ɪɡˈzæs.ə.beɪt/', meaning: 'Làm tồi tệ hơn, làm trầm trọng thêm', example: 'Deforestation exacerbates the effects of flooding and soil erosion.' },
      { word: 'irreversible', phonetic: '/ˌɪr.ɪˈvɜː.sɪ.bəl/', meaning: 'Không thể đảo ngược', example: 'Some forms of ecosystem damage caused by climate change may be irreversible.' },
      { word: 'cascading', phonetic: '/kæˈskeɪ.dɪŋ/', meaning: 'Liên hoàn, xảy ra theo dây chuyền', example: 'Climate change triggers cascading effects across ecosystems and economies.' },
      { word: 'abatement', phonetic: '/əˈbeɪt.mənt/', meaning: 'Sự giảm nhẹ, hạ bớt ô nhiễm', example: 'Pollution abatement measures have significantly improved air quality in major cities.' },
    ]
  },
  {
    id: 'ielts_public_health', name: 'Public Health', nameVi: 'Y tế Công cộng',
    icon: '🏥', color: '#DC2626',
    words: [
      { word: 'mortality', phonetic: '/mɔːˈtæl.ɪ.ti/', meaning: 'Tỷ lệ tử vong trong cộng đồng', example: 'Infant mortality rates have fallen dramatically in developing countries.' },
      { word: 'morbidity', phonetic: '/mɔːˈbɪd.ɪ.ti/', meaning: 'Tỷ lệ mắc bệnh trong dân số', example: 'High morbidity from preventable diseases places strain on healthcare systems.' },
      { word: 'sanitation', phonetic: '/ˌsæn.ɪˈteɪ.ʃən/', meaning: 'Vệ sinh môi trường, xử lý nước thải', example: 'Access to clean water and sanitation is essential for public health.' },
      { word: 'malnutrition', phonetic: '/ˌmæl.njuːˈtrɪʃ.ən/', meaning: 'Suy dinh dưỡng, thiếu chất dinh dưỡng', example: 'Malnutrition in early childhood has lasting effects on cognitive development.' },
      { word: 'quarantine', phonetic: '/ˈkwɒr.ən.tiːn/', meaning: 'Cách ly kiểm dịch, ngăn chặn lây lan', example: 'Strict quarantine measures were enforced to contain the outbreak.' },
      { word: 'endemic', phonetic: '/enˈdem.ɪk/', meaning: 'Bệnh đặc hữu, xuất hiện thường xuyên ở địa phương', example: 'Malaria remains endemic in many sub-Saharan African nations.' },
      { word: 'pandemic', phonetic: '/pænˈdem.ɪk/', meaning: 'Đại dịch lan rộng trên toàn thế giới', example: 'The 2020 pandemic exposed significant weaknesses in global health systems.' },
      { word: 'immunization', phonetic: '/ˌɪm.jʊ.naɪˈzeɪ.ʃən/', meaning: 'Tiêm chủng, tạo miễn dịch cộng đồng', example: 'Mass immunization campaigns eradicated smallpox by the 1970s.' },
      { word: 'prevalence', phonetic: '/ˈprev.ə.ləns/', meaning: 'Tỷ lệ phổ biến của bệnh trong cộng đồng', example: 'The prevalence of type-2 diabetes is rising in low-income countries.' },
      { word: 'determinant', phonetic: '/dɪˈtɜː.mɪ.nənt/', meaning: 'Yếu tố quyết định tình trạng sức khỏe', example: 'Social determinants such as income and education strongly affect health outcomes.' },
      { word: 'intervention', phonetic: '/ˌɪn.təˈven.ʃən/', meaning: 'Biện pháp can thiệp y tế, chính sách y tế', example: 'Early intervention programmes reduce the long-term costs of treating chronic illness.' },
      { word: 'surveillance', phonetic: '/sɜːˈveɪ.ləns/', meaning: 'Giám sát, theo dõi dịch bệnh', example: 'Disease surveillance systems provide early warning of potential outbreaks.' },
      { word: 'inoculate', phonetic: '/ɪˈnɒk.jʊ.leɪt/', meaning: 'Chủng ngừa, tiêm phòng bệnh', example: 'Children are inoculated against polio as part of national health programmes.' },
      { word: 'dispensary', phonetic: '/dɪˈspen.sər.i/', meaning: 'Phòng cấp phát thuốc, trạm y tế cơ sở', example: 'Mobile dispensaries bring essential medicines to remote rural communities.' },
      { word: 'alleviate', phonetic: '/əˈliː.vi.eɪt/', meaning: 'Giảm nhẹ, làm vơi bớt gánh nặng', example: 'New treatments aim to alleviate chronic pain without causing dependency.' },
    ]
  },

  // ── 3 new IELTS topics ────────────────────────────────────────
  {
    id: 'ielts_housing', name: 'Housing & Architecture', nameVi: 'Nhà ở & Kiến trúc',
    icon: '🏛️', color: '#8D6E63',
    words: [
      { word: 'gentrification', phonetic: '/ˌdʒen.trɪ.fɪˈkeɪ.ʃən/', meaning: 'Đô thị hóa làm tăng giá nhà, đẩy cư dân nghèo ra ngoài', example: 'Gentrification transformed the neighbourhood but displaced many long-term residents.' },
      { word: 'renovation', phonetic: '/ˌren.əˈveɪ.ʃən/', meaning: 'Cải tạo, sửa chữa công trình', example: 'The historic building underwent extensive renovation to restore its original features.' },
      { word: 'mortgage', phonetic: '/ˈmɔː.ɡɪdʒ/', meaning: 'Khoản vay thế chấp mua nhà', example: 'Rising interest rates made it difficult for first-time buyers to secure a mortgage.' },
      { word: 'derelict', phonetic: '/ˈder.ɪ.lɪkt/', meaning: 'Bị bỏ hoang, xuống cấp nghiêm trọng', example: 'The council planned to demolish the derelict warehouse and build affordable housing.' },
      { word: 'rezoning', phonetic: '/ˌriːˈzəʊ.nɪŋ/', meaning: 'Quy hoạch lại vùng sử dụng đất', example: 'Rezoning the industrial area allowed for new residential developments.' },
      { word: 'heritage', phonetic: '/ˈher.ɪ.tɪdʒ/', meaning: 'Di sản kiến trúc, văn hóa', example: 'The government listed the building as a heritage site to prevent demolition.' },
      { word: 'tenement', phonetic: '/ˈten.ɪ.mənt/', meaning: 'Căn hộ chung cư cũ nát, nhà trọ xuống cấp', example: 'Many families lived in cramped tenements in the industrial city.' },
      { word: 'vernacular', phonetic: '/vəˈnæk.jʊ.lər/', meaning: 'Kiến trúc bản địa, phong cách địa phương', example: 'The vernacular architecture of the village used local stone and timber.' },
      { word: 'façade', phonetic: '/fəˈsɑːd/', meaning: 'Mặt tiền công trình', example: 'The building\'s ornate façade was designed in the Gothic style.' },
      { word: 'aesthetic', phonetic: '/iːsˈθet.ɪk/', meaning: 'Tính thẩm mỹ', example: 'The aesthetic of the new library blends modern design with traditional materials.' },
      { word: 'suburb', phonetic: '/ˈsʌb.ɜːb/', meaning: 'Vùng ngoại ô', example: 'Many families moved to the suburbs to escape the noise of the city centre.' },
      { word: 'landlord', phonetic: '/ˈlænd.lɔːd/', meaning: 'Chủ nhà cho thuê', example: 'The landlord was responsible for maintaining the property in good condition.' },
      { word: 'affordable housing', phonetic: '/əˈfɔː.də.bəl ˈhaʊ.zɪŋ/', meaning: 'Nhà ở giá rẻ phù hợp với thu nhập thấp', example: 'The shortage of affordable housing has forced many workers to live far from their jobs.' },
      { word: 'infrastructure', phonetic: '/ˈɪn.frəˌstrʌk.tʃər/', meaning: 'Cơ sở hạ tầng', example: 'The government invested heavily in infrastructure to support the growing population.' },
      { word: 'sustainable building', phonetic: '/səˈsteɪ.nə.bəl ˈbɪl.dɪŋ/', meaning: 'Công trình xây dựng bền vững, thân thiện môi trường', example: 'Sustainable buildings use solar panels and insulation to minimise energy consumption.' },
    ]
  },
  {
    id: 'ielts_agriculture', name: 'Agriculture & Food Production', nameVi: 'Nông nghiệp & Sản xuất thực phẩm',
    icon: '🌾', color: '#8BC34A',
    words: [
      { word: 'cultivation', phonetic: '/ˌkʌl.tɪˈveɪ.ʃən/', meaning: 'Sự canh tác, trồng trọt', example: 'The cultivation of rice in flooded paddies dates back thousands of years.' },
      { word: 'yield', phonetic: '/jiːld/', meaning: 'Sản lượng nông nghiệp', example: 'New seed varieties have dramatically increased crop yields in developing regions.' },
      { word: 'irrigation', phonetic: '/ˌɪr.ɪˈɡeɪ.ʃən/', meaning: 'Hệ thống tưới tiêu', example: 'Without adequate irrigation, farming in dry regions would be impossible.' },
      { word: 'pesticide', phonetic: '/ˈpes.tɪ.saɪd/', meaning: 'Thuốc trừ sâu', example: 'Overuse of pesticides can contaminate soil and harm beneficial insects.' },
      { word: 'arable', phonetic: '/ˈær.ə.bəl/', meaning: 'Đất có thể canh tác được', example: 'Only a fraction of the country\'s land is classified as arable farmland.' },
      { word: 'subsistence farming', phonetic: '/səbˈsɪs.təns ˌfɑː.mɪŋ/', meaning: 'Nông nghiệp tự cung tự cấp', example: 'Subsistence farming cannot produce the surplus needed to feed urban populations.' },
      { word: 'mechanisation', phonetic: '/ˌmek.ə.naɪˈzeɪ.ʃən/', meaning: 'Cơ giới hóa nông nghiệp', example: 'Mechanisation has reduced the need for manual labour on large farms.' },
      { word: 'monoculture', phonetic: '/ˈmɒn.əˌkʌl.tʃər/', meaning: 'Độc canh, trồng một loại cây duy nhất', example: 'Monoculture farming increases vulnerability to disease and reduces soil health.' },
      { word: 'fertiliser', phonetic: '/ˈfɜː.tɪ.laɪ.zər/', meaning: 'Phân bón', example: 'Synthetic fertilisers boost short-term crop growth but can damage soil ecosystems.' },
      { word: 'organic farming', phonetic: '/ɔːˌɡæn.ɪk ˈfɑː.mɪŋ/', meaning: 'Nông nghiệp hữu cơ', example: 'Organic farming avoids the use of synthetic chemicals and genetically modified organisms.' },
      { word: 'food security', phonetic: '/ˈfuːd sɪˌkjʊər.ɪ.ti/', meaning: 'An ninh lương thực', example: 'Climate change poses a serious threat to global food security.' },
      { word: 'crop rotation', phonetic: '/ˈkrɒp rəʊˌteɪ.ʃən/', meaning: 'Luân canh cây trồng', example: 'Crop rotation helps maintain soil fertility and reduce pest pressure.' },
      { word: 'agribusiness', phonetic: '/ˈæɡ.rɪˌbɪz.nɪs/', meaning: 'Kinh doanh nông nghiệp quy mô lớn', example: 'Large agribusiness corporations now control much of the world\'s food supply chain.' },
      { word: 'genetically modified', phonetic: '/dʒəˌnet.ɪ.kli ˈmɒd.ɪ.faɪd/', meaning: 'Biến đổi gen', example: 'Genetically modified crops are designed to be more resistant to pests and disease.' },
      { word: 'drought', phonetic: '/draʊt/', meaning: 'Hạn hán', example: 'A prolonged drought devastated cereal crops across the region.' },
    ]
  },
  {
    id: 'ielts_transport', name: 'Transport & Infrastructure', nameVi: 'Giao thông & Cơ sở hạ tầng',
    icon: '🚆', color: '#42A5F5',
    words: [
      { word: 'congestion', phonetic: '/kənˈdʒes.tʃən/', meaning: 'Ùn tắc giao thông', example: 'Traffic congestion in the city centre costs the economy millions each year.' },
      { word: 'commute', phonetic: '/kəˈmjuːt/', meaning: 'Hành trình đi làm hàng ngày', example: 'The average commute in London takes nearly 45 minutes each way.' },
      { word: 'emission', phonetic: '/ɪˈmɪʃ.ən/', meaning: 'Khí thải', example: 'Electric vehicles produce zero direct emissions during operation.' },
      { word: 'modal shift', phonetic: '/ˈməʊ.dəl ʃɪft/', meaning: 'Chuyển đổi phương tiện từ xe hơi sang giao thông công cộng', example: 'Policies aimed at modal shift encourage commuters to use public transport.' },
      { word: 'gridlock', phonetic: '/ˈɡrɪd.lɒk/', meaning: 'Tắc đường hoàn toàn', example: 'A broken traffic signal caused complete gridlock at the city\'s main junction.' },
      { word: 'subsidy', phonetic: '/ˈsʌb.sɪ.di/', meaning: 'Trợ cấp nhà nước cho giao thông công cộng', example: 'The government provides subsidies to keep bus fares affordable.' },
      { word: 'hub', phonetic: '/hʌb/', meaning: 'Trung tâm giao thông, đầu mối', example: 'The airport serves as a major international hub for connecting flights.' },
      { word: 'toll', phonetic: '/təʊl/', meaning: 'Phí cầu đường', example: 'Drivers must pay a toll when crossing the bridge.' },
      { word: 'thoroughfare', phonetic: '/ˈθʌr.ə.feər/', meaning: 'Đường phố chính, đường trục', example: 'The high street is the main thoroughfare through the historic market town.' },
      { word: 'intermodal', phonetic: '/ˌɪn.tə.ˈməʊ.dəl/', meaning: 'Đa phương thức, kết hợp nhiều loại giao thông', example: 'Intermodal transport hubs allow passengers to switch between train, bus and cycle.' },
      { word: 'pedestrian', phonetic: '/pəˈdes.tri.ən/', meaning: 'Người đi bộ', example: 'The council invested in wider pedestrian zones to improve safety.' },
      { word: 'carriageway', phonetic: '/ˈkær.ɪdʒ.weɪ/', meaning: 'Làn đường xe chạy', example: 'The dual carriageway was widened to ease traffic flow.' },
      { word: 'viaduct', phonetic: '/ˈvaɪ.ə.dʌkt/', meaning: 'Cầu cạn, cầu vượt', example: 'The Victorian viaduct carried the railway line across the valley.' },
      { word: 'feeder route', phonetic: '/ˈfiː.dər ruːt/', meaning: 'Tuyến đường nhánh kết nối với tuyến chính', example: 'Several feeder routes connect the small villages to the main motorway.' },
      { word: 'retrofit', phonetic: '/ˈret.rəʊˌfɪt/', meaning: 'Cải tạo, lắp đặt thêm thiết bị mới vào công trình cũ', example: 'The government plans to retrofit older vehicles with cleaner engine technology.' },
    ]
  },
];
