// ═══════════════════════════════════════════════════════════
//  VocabMaster — C2 Vocabulary Database (Mastery Level)
// ═══════════════════════════════════════════════════════════
const TOPICS_C2 = [
  {
    id: 'c2_philosophy', name: 'Philosophy & Ethics', nameVi: 'Triết học & Đạo đức',
    icon: '💭', color: '#6366F1',
    words: [
      { word: 'epistemology', phonetic: '/ɪˌpɪs.tɪˈmɒl.ə.dʒi/', meaning: 'Nhận thức luận', example: 'Epistemology asks how we can acquire knowledge about the world.' },
      { word: 'ontology', phonetic: '/ɒnˈtɒl.ə.dʒi/', meaning: 'Bản thể luận', example: 'Ontology is the branch of philosophy concerned with the nature of being.' },
      { word: 'dialectic', phonetic: '/ˌdaɪ.əˈlek.tɪk/', meaning: 'Biện chứng pháp', example: "Hegel's dialectic involves thesis, antithesis, and synthesis." },
      { word: 'nihilism', phonetic: '/ˈnaɪ.ɪ.lɪ.z(ə)m/', meaning: 'Chủ nghĩa hư vô', example: 'Nihilism holds that life has no inherent meaning or value.' },
      { word: 'determinism', phonetic: '/dɪˈtɜː.mɪ.nɪ.z(ə)m/', meaning: 'Thuyết tất định', example: 'Determinism argues that all events are caused by prior conditions.' },
      { word: 'solipsism', phonetic: '/ˈsɒl.ɪp.sɪ.z(ə)m/', meaning: 'Chủ nghĩa duy ngã', example: "Solipsism is the view that only one's own mind is certain to exist." },
      { word: 'axiom', phonetic: '/ˈæk.si.əm/', meaning: 'Tiên đề', example: '"All men are mortal" is a philosophical axiom used in classic syllogisms.' },
      { word: 'hegemony', phonetic: '/hɪˈɡem.ə.ni/', meaning: 'Bá quyền', example: 'The hegemony of Western culture influenced global philosophical thought.' },
      { word: 'pragmatism', phonetic: '/ˈpræɡ.mə.tɪ.z(ə)m/', meaning: 'Chủ nghĩa thực dụng', example: 'American pragmatism judges ideas by their practical consequences.' },
      { word: 'empiricism', phonetic: '/ɪmˈpɪr.ɪ.sɪ.z(ə)m/', meaning: 'Chủ nghĩa kinh nghiệm', example: 'Empiricism holds that knowledge comes primarily from sensory experience.' },
      { word: 'teleology', phonetic: '/ˌtel.iˈɒl.ə.dʒi/', meaning: 'Mục đích luận', example: 'Teleology studies the purpose or design behind natural phenomena.' },
      { word: 'altruism', phonetic: '/ˈæl.tru.ɪ.z(ə)m/', meaning: 'Chủ nghĩa vị tha', example: 'True altruism involves acting for others without personal benefit.' },
      { word: 'relativism', phonetic: '/ˈrel.ə.tɪ.vɪ.z(ə)m/', meaning: 'Chủ nghĩa tương đối', example: 'Moral relativism holds that ethical judgments vary across cultures.' },
      { word: 'reductionism', phonetic: '/rɪˈdʌk.ʃən.ɪ.z(ə)m/', meaning: 'Chủ nghĩa giản lược', example: 'Reductionism explains complex phenomena through simpler components.' },
      { word: 'conjecture', phonetic: '/kənˈdʒek.tʃər/', meaning: 'Suy đoán chưa được chứng minh', example: 'His conjecture about consciousness remains hotly debated in philosophy.' },
      { word: 'syllogism', phonetic: '/ˈsɪl.ə.dʒɪ.z(ə)m/', meaning: 'Tam đoạn luận', example: '"All men are mortal; Socrates is a man; therefore Socrates is mortal" is a classic syllogism.' },
      { word: 'metaphysics', phonetic: '/ˌmet.əˈfɪz.ɪks/', meaning: 'Siêu hình học', example: 'Metaphysics addresses questions about reality that lie beyond the scope of physical science.' },
      { word: 'deontology', phonetic: '/ˌdiː.ɒnˈtɒl.ə.dʒi/', meaning: 'Đạo đức học về nghĩa vụ', example: 'Deontology holds that the morality of an action depends on whether it follows a moral rule.' },
      { word: 'utilitarianism', phonetic: '/juːˌtɪl.ɪˈteər.i.ə.nɪ.z(ə)m/', meaning: 'Thuyết công lợi', example: 'Utilitarianism judges actions by the greatest happiness they produce for the greatest number.' },
      { word: 'sophistry', phonetic: '/ˈsɒf.ɪ.stri/', meaning: 'Ngụy biện tinh vi', example: 'His argument sounded convincing but was ultimately a piece of clever sophistry.' },
      { word: 'ethical', phonetic: '/ˈeθ.ɪ.kəl/', meaning: 'Liên quan đến đúng sai về đạo đức', example: 'The book raises some serious ethical questions about genetic research.' },
      { word: 'unethical', phonetic: '/ʌnˈeθ.ɪ.kəl/', meaning: 'Sai về mặt đạo đức', example: 'The company was accused of unethical business methods.' },
      { word: 'philosophical', phonetic: '/ˌfɪl.əˈsɒf.ɪ.kəl/', meaning: 'Liên quan đến triết học; điềm tĩnh', example: 'She took a philosophical view of her misfortune and moved on.' },
      { word: 'virtue', phonetic: '/ˈvɜː.tjuː/', meaning: 'Đức hạnh; bởi vì (by virtue of)', example: 'She succeeded by virtue of hard work rather than natural talent.' },
      { word: 'analogy', phonetic: '/əˈnæl.ə.dʒi/', meaning: 'Sự so sánh để làm rõ điểm tương đồng', example: 'She draws an analogy between life\'s events and a game of chess.' },
      { word: 'analogous', phonetic: '/əˈnæl.ə.gəs/', meaning: 'Tương tự về một khía cạnh nào đó', example: 'The brain is analogous to a computer in some respects.' },
      { word: 'speculate', phonetic: '/ˈspek.jə.leɪt/', meaning: 'Phỏng đoán khi không có đủ thông tin', example: 'Philosophers speculate about the nature of consciousness and reality.' },
      { word: 'inherent', phonetic: '/ɪnˈher.ənt/', meaning: 'Vốn có, tồn tại tự nhiên như một phần cơ bản', example: 'The desire for freedom is inherent in all people.' },
    ]
  },
  {
    id: 'c2_law', name: 'Law & Justice', nameVi: 'Pháp luật & Công lý',
    icon: '⚖️', color: '#DC2626',
    words: [
      { word: 'jurisprudence', phonetic: '/ˌdʒʊər.ɪsˈpruː.dəns/', meaning: 'Pháp lý học', example: 'Jurisprudence is the theory and philosophy of law.' },
      { word: 'litigation', phonetic: '/ˌlɪt.ɪˈɡeɪ.ʃən/', meaning: 'Tố tụng', example: 'The company faced lengthy litigation over the patent dispute.' },
      { word: 'indictment', phonetic: '/ɪnˈdaɪt.mənt/', meaning: 'Cáo trạng', example: 'The grand jury issued an indictment against the suspect.' },
      { word: 'subpoena', phonetic: '/səˈpiː.nə/', meaning: 'Trát triệu tập hầu tòa', example: 'The witness received a subpoena to testify in court.' },
      { word: 'acquittal', phonetic: '/əˈkwɪt.əl/', meaning: 'Tuyên trắng án', example: "The jury's acquittal surprised many legal observers." },
      { word: 'exculpate', phonetic: '/ˈek.skʌl.peɪt/', meaning: 'Minh oan', example: 'New DNA evidence helped exculpate the wrongly convicted man.' },
      { word: 'habeas corpus', phonetic: '/ˌheɪ.bi.əs ˈkɔː.pəs/', meaning: 'Lệnh đưa người ra tòa', example: 'Habeas corpus prevents unlawful and indefinite imprisonment.' },
      { word: 'injunction', phonetic: '/ɪnˈdʒʌŋk.ʃən/', meaning: 'Lệnh của tòa án', example: 'The court issued an injunction to stop the construction.' },
      { word: 'affidavit', phonetic: '/ˌæf.ɪˈdeɪ.vɪt/', meaning: 'Tuyên thệ thư', example: 'She submitted an affidavit detailing what she witnessed.' },
      { word: 'culpable', phonetic: '/ˈkʌl.pə.bəl/', meaning: 'Có lỗi, đáng bị trách phạt', example: 'The manager was found culpable for the safety violation.' },
      { word: 'arbitration', phonetic: '/ˌɑː.bɪˈtreɪ.ʃən/', meaning: 'Trọng tài phán xử', example: 'The dispute was resolved through binding arbitration.' },
      { word: 'extradition', phonetic: '/ˌek.strəˈdɪʃ.ən/', meaning: 'Dẫn độ', example: 'The suspect fled abroad to avoid extradition.' },
      { word: 'tort', phonetic: '/tɔːt/', meaning: 'Hành vi vi phạm dân sự gây thiệt hại', example: 'She filed a tort claim for damages caused by the company\'s negligence.' },
      { word: 'perjury', phonetic: '/ˈpɜː.dʒər.i/', meaning: 'Tội khai man dưới lời thề', example: 'He was charged with perjury after lying under oath.' },
      { word: 'probate', phonetic: '/ˈprəʊ.beɪt/', meaning: 'Thủ tục chứng thực di chúc', example: 'The estate went through probate before assets were distributed.' },
      { word: 'malfeasance', phonetic: '/mælˈfiː.zəns/', meaning: 'Hành vi sai trái của công chức', example: 'The official was charged with malfeasance for misusing public funds.' },
      { word: 'statute', phonetic: '/ˈstætʃ.uːt/', meaning: 'Đạo luật thành văn', example: 'The statute clearly defines the penalties for tax evasion.' },
      { word: 'clemency', phonetic: '/ˈklem.ən.si/', meaning: 'Sự khoan hồng', example: 'The convicted man appealed to the governor for clemency.' },
      { word: 'deposition', phonetic: '/ˌdep.əˈzɪʃ.ən/', meaning: 'Lời khai có tuyên thệ', example: 'Her deposition was submitted as key evidence before the trial began.' },
      { word: 'plaintiff', phonetic: '/ˈpleɪn.tɪf/', meaning: 'Nguyên đơn', example: 'The plaintiff filed a lawsuit claiming damages of one million dollars.' },
      { word: 'convict', phonetic: '/kənˈvɪkt/', meaning: 'Kết tội chính thức trong tòa án', example: 'He was convicted of murder and sentenced to life imprisonment.' },
      { word: 'conviction', phonetic: '/kənˈvɪk.ʃən/', meaning: 'Bản án kết tội; sự tin tưởng mạnh mẽ', example: 'He already had two convictions for burglary before this offence.' },
      { word: 'crackdown', phonetic: '/ˈkræk.daʊn/', meaning: 'Biện pháp mạnh tay xử lý hành vi xấu', example: 'The police are having a crackdown on drug trafficking.' },
      { word: 'constitutional', phonetic: '/ˌkɒn.stɪˈtjuː.ʃən.əl/', meaning: 'Liên quan đến hiến pháp', example: 'The proposed law sparked a major constitutional crisis.' },
      { word: 'execute', phonetic: '/ˈek.sɪ.kjuːt/', meaning: 'Hành quyết như hình phạt hợp pháp', example: 'He was executed for murder after a lengthy legal process.' },
      { word: 'dubious', phonetic: '/ˈdjuː.bi.əs/', meaning: 'Đáng ngờ về tính trung thực hoặc hợp pháp', example: 'The defence team questioned the dubious evidence presented at trial.' },
      { word: 'allege', phonetic: '/əˈledʒ/', meaning: 'Khẳng định điều gì là thật mà không có bằng chứng', example: 'The teacher is alleged to have struck a student.' },
      { word: 'allegedly', phonetic: '/əˈledʒ.ɪd.li/', meaning: 'Được cho là thật nhưng chưa được chứng minh', example: 'He allegedly accepted bribes from several corporations.' },
      { word: 'prosecute', phonetic: '/ˈprɒs.ɪ.kjuːt/', meaning: 'Truy tố chính thức tại tòa án', example: 'Shoplifters will be prosecuted to the full extent of the law.' },
      { word: 'scrutiny', phonetic: '/ˈskruː.tɪn.i/', meaning: 'Sự xem xét, kiểm tra cẩn thận', example: 'The new legislation came under intense scrutiny from legal experts.' },
    ]
  },
  {
    id: 'c2_literature', name: 'Literature & Linguistics', nameVi: 'Văn học & Ngôn ngữ',
    icon: '📚', color: '#D97706',
    words: [
      { word: 'juxtaposition', phonetic: '/ˌdʒʌk.stə.pəˈzɪʃ.ən/', meaning: 'Sự đặt kề nhau để đối chiếu', example: 'The author used juxtaposition to contrast wealth and poverty.' },
      { word: 'soliloquy', phonetic: '/səˈlɪl.ə.kwi/', meaning: 'Độc thoại nội tâm', example: "Hamlet's famous soliloquy explores his contemplation of death." },
      { word: 'verisimilitude', phonetic: '/ˌver.ɪ.sɪˈmɪl.ɪ.tjuːd/', meaning: 'Tính chân thực trong tác phẩm', example: "The novel's verisimilitude made readers feel they were truly there." },
      { word: 'catharsis', phonetic: '/kəˈθɑː.sɪs/', meaning: 'Sự thanh lọc cảm xúc', example: 'Greek tragedy was designed to produce catharsis in the audience.' },
      { word: 'aphorism', phonetic: '/ˈæf.ə.rɪ.z(ə)m/', meaning: 'Cách ngôn, châm ngôn', example: '"Less is more" is an aphorism that applies to both art and writing.' },
      { word: 'denouement', phonetic: '/deɪˈnuː.mɒ̃/', meaning: 'Phần giải quyết cuối câu chuyện', example: 'The denouement revealed the true identity of the mysterious stranger.' },
      { word: 'anachronism', phonetic: '/əˈnæk.rə.nɪ.z(ə)m/', meaning: 'Sự nhầm lẫn hoặc lỗi thời đại', example: 'The smartphone in the historical drama was an obvious anachronism.' },
      { word: 'cacophony', phonetic: '/kæˈkɒf.ə.ni/', meaning: 'Âm thanh hỗn loạn chói tai', example: 'The cacophony of voices in the market overwhelmed the traveler.' },
      { word: 'epitome', phonetic: '/ɪˈpɪt.ə.mi/', meaning: 'Hiện thân điển hình', example: 'She was the epitome of grace under pressure.' },
      { word: 'euphemism', phonetic: '/ˈjuː.fə.mɪ.z(ə)m/', meaning: 'Lời nói giảm nói tránh', example: '"Passed away" is a common euphemism for death.' },
      { word: 'hyperbole', phonetic: '/haɪˈpɜː.bə.li/', meaning: 'Phép thậm xưng', example: '"I\'ve told you a million times" is an example of hyperbole.' },
      { word: 'allegory', phonetic: '/ˈæl.ɪ.ɡər.i/', meaning: 'Ẩn dụ kéo dài/ngụ ngôn', example: 'Orwell\'s "Animal Farm" is an allegory of Soviet totalitarianism.' },
      { word: 'pathos', phonetic: '/ˈpeɪ.θɒs/', meaning: 'Yếu tố gợi lên lòng thương xót', example: "The film's final scene was filled with profound pathos." },
      { word: 'didactic', phonetic: '/daɪˈdæk.tɪk/', meaning: 'Có tính giáo huấn', example: 'The story is didactic, teaching moral lessons through its characters.' },
      { word: 'paradox', phonetic: '/ˈpær.ə.dɒks/', meaning: 'Nghịch lý', example: '"Less is more" is a paradox that contains a deep truth.' },
      { word: 'bathos', phonetic: '/ˈbeɪ.θɒs/', meaning: 'Sự xuống cấp đột ngột của phong cách', example: 'The speech ended in bathos, shifting from tragedy to a joke about the weather.' },
      { word: 'oxymoron', phonetic: '/ˌɒk.sɪˈmɔː.rɒn/', meaning: 'Kết hợp hai từ mâu thuẫn', example: '"Deafening silence" is a powerful oxymoron used by many poets.' },
      { word: 'periphrasis', phonetic: '/pəˈrɪf.rə.sɪs/', meaning: 'Diễn đạt vòng vo, dài dòng', example: 'The author\'s use of periphrasis was deliberate, drawing out the moment for dramatic effect.' },
      { word: 'synecdoche', phonetic: '/sɪˈnek.də.ki/', meaning: 'Phép hoán dụ bộ phận', example: '"The crown" as a synecdoche for the monarchy is common in political writing.' },
      { word: 'bildungsroman', phonetic: '/ˈbɪl.dʊŋz.roʊ.mɑːn/', meaning: 'Thể loại tiểu thuyết trưởng thành', example: '"Great Expectations" is a classic bildungsroman tracing the moral growth of its hero.' },
      { word: 'irony', phonetic: '/ˈaɪə.rən.i/', meaning: 'Sự mỉa mai; điều trái ngược với mong đợi', example: 'The irony is that now he has retired, he is busier than ever.' },
      { word: 'poetic', phonetic: '/pəʊˈet.ɪk/', meaning: 'Liên quan đến thơ ca; mang tính thơ', example: 'The novel is written in a poetic style full of vivid imagery.' },
      { word: 'quotation', phonetic: '/kwəʊˈteɪ.ʃən/', meaning: 'Câu trích dẫn từ sách, thơ hoặc kịch', example: 'She opened her essay with a quotation from Shakespeare.' },
      { word: 'conceive', phonetic: '/kənˈsiːv/', meaning: 'Hình thành ý tưởng hoặc kế hoạch trong đầu', example: 'The original idea for the novel was conceived in Rome.' },
      { word: 'novelty', phonetic: '/ˈnɒv.əl.ti/', meaning: 'Tính mới lạ, độc đáo', example: 'Great literature transcends novelty and speaks to timeless truths.' },
      { word: 'portrayal', phonetic: '/pɔːˈtreɪ.əl/', meaning: 'Cách miêu tả, khắc họa nhân vật hoặc sự việc', example: 'He won several awards for his portrayal of the tragic hero.' },
      { word: 'wretched', phonetic: '/ˈretʃ.ɪd/', meaning: '(Văn học) Cực kỳ bất hạnh hoặc khổ sở', example: 'The wretched protagonist endures one misfortune after another.' },
    ]
  },
  {
    id: 'c2_arts', name: 'Arts & Criticism', nameVi: 'Nghệ thuật & Phê bình',
    icon: '🎭', color: '#BE185D',
    words: [
      { word: 'avant-garde', phonetic: '/ˌæv.ɒ̃ˈɡɑːrd/', meaning: 'Tiên phong nghệ thuật', example: 'The avant-garde movement challenged all traditional artistic conventions.' },
      { word: 'iconoclast', phonetic: '/aɪˈkɒn.ə.klæst/', meaning: 'Người phá vỡ quan niệm truyền thống', example: 'Picasso was an iconoclast who revolutionized modern painting.' },
      { word: 'chiaroscuro', phonetic: '/kiˌɑːr.əˈskjʊər.əʊ/', meaning: 'Kỹ thuật sáng tối trong hội họa', example: 'Caravaggio mastered chiaroscuro to create dramatic visual contrasts.' },
      { word: 'oeuvre', phonetic: '/ˈɜː.vrə/', meaning: 'Toàn bộ tác phẩm của nghệ sĩ', example: "Beethoven's oeuvre includes nine symphonies and numerous concertos." },
      { word: 'vernacular', phonetic: '/vəˈnæk.jʊ.lər/', meaning: 'Phong cách dân gian địa phương', example: 'The artist drew on the local vernacular tradition for inspiration.' },
      { word: 'provenance', phonetic: '/ˈprɒv.ə.nəns/', meaning: 'Nguồn gốc xuất xứ tác phẩm', example: "The painting's provenance was traced back to a 17th-century collection." },
      { word: 'pastiche', phonetic: '/pæˈstiːʃ/', meaning: 'Tác phẩm phỏng theo/nhái lại', example: 'The film is a deliberate pastiche of 1950s Hollywood noir.' },
      { word: 'zeitgeist', phonetic: '/ˈzaɪt.ɡaɪst/', meaning: 'Tinh thần/xu hướng của thời đại', example: 'The artist perfectly captured the zeitgeist of post-war anxiety.' },
      { word: 'ekphrasis', phonetic: '/ˈek.frə.sɪs/', meaning: 'Mô tả tác phẩm nghệ thuật bằng văn bản', example: 'Keats\'s "Ode on a Grecian Urn" is a classic example of ekphrasis.' },
      { word: 'subliminal', phonetic: '/sʌbˈlɪm.ɪ.nəl/', meaning: 'Dưới ngưỡng ý thức', example: 'Advertisers sometimes use subliminal imagery to influence consumers.' },
      { word: 'aesthetic', phonetic: '/iːsˈθet.ɪk/', meaning: 'Thuộc về thẩm mỹ', example: 'Her aesthetic sensibility was shaped by Japanese minimalism.' },
      { word: 'motif', phonetic: '/məʊˈtiːf/', meaning: 'Chủ đề lặp lại trong tác phẩm', example: 'The recurring motif of water symbolizes change throughout the novel.' },
      { word: 'surrealism', phonetic: '/səˈrɪə.lɪ.z(ə)m/', meaning: 'Chủ nghĩa siêu thực', example: "Salvador Dalí's melting clocks are icons of surrealism." },
      { word: 'posthumous', phonetic: '/ˈpɒs.tʃʊ.məs/', meaning: 'Sau khi mất (được công nhận/xuất bản)', example: 'The posthumous release of her diaries revealed a tormented inner life.' },
      { word: 'trompe-l\'oeil', phonetic: '/ˌtrɒmp ˈlɔɪ/', meaning: 'Kỹ thuật vẽ tạo ảo giác thị giác', example: 'The ceiling painting was a stunning trompe-l\'oeil that appeared open to the sky.' },
      { word: 'impasto', phonetic: '/ɪmˈpɑːs.toʊ/', meaning: 'Kỹ thuật vẽ dày màu', example: 'Van Gogh\'s impasto technique created rich, textured surfaces on his canvases.' },
      { word: 'fresco', phonetic: '/ˈfres.kəʊ/', meaning: 'Tranh bích họa vẽ trên tường', example: 'Michelangelo painted the Sistine Chapel ceiling as a monumental fresco.' },
      { word: 'triptych', phonetic: '/ˈtrɪp.tɪk/', meaning: 'Bộ tranh ba tấm', example: 'The altar featured a stunning medieval triptych depicting the life of the Virgin Mary.' },
      { word: 'patina', phonetic: '/ˈpæt.ɪ.nə/', meaning: 'Lớp màu thời gian trên cổ vật', example: 'The bronze statue had developed a beautiful green patina over centuries.' },
      { word: 'iconography', phonetic: '/ˌaɪ.kəˈnɒɡ.rə.fi/', meaning: 'Ngôn ngữ biểu tượng trong nghệ thuật', example: 'The iconography of the painting draws on both Christian and classical traditions.' },
      { word: 'accompany', phonetic: '/əˈkʌm.pə.ni/', meaning: 'Chơi nhạc để hỗ trợ người biểu diễn khác', example: 'He accompanied the soprano on the piano throughout the recital.' },
      { word: 'blend', phonetic: '/blend/', meaning: 'Sự kết hợp hài hòa của nhiều yếu tố', example: 'Their music is a blend of jazz, soul and African rhythms.' },
      { word: 'aspiring', phonetic: '/əˈspaɪə.rɪŋ/', meaning: 'Đang nuôi tham vọng, mơ ước trở thành', example: 'The workshop is ideal for aspiring artists and designers.' },
      { word: 'brass', phonetic: '/brɑːs/', meaning: 'Nhạc cụ hơi làm bằng đồng', example: 'The brass section of the orchestra played with tremendous power.' },
      { word: 'balcony', phonetic: '/ˈbæl.kə.ni/', meaning: 'Hàng ghế trên tầng cao trong nhà hát', example: 'We had seats in the balcony, which gave a great view of the stage.' },
      { word: 'masterpiece', phonetic: '/ˈmɑː.stə.piːs/', meaning: 'Tác phẩm nghệ thuật xuất sắc nhất', example: 'The Mona Lisa is widely regarded as Leonardo da Vinci\'s masterpiece.' },
      { word: 'arouse', phonetic: '/əˈraʊz/', meaning: 'Khơi dậy cảm xúc, sự quan tâm', example: 'The exhibition aroused huge interest among critics and the public.' },
    ]
  },
  {
    id: 'c2_governance', name: 'Governance & Diplomacy', nameVi: 'Ngoại giao & Quản trị',
    icon: '🏛️', color: '#0891B2',
    words: [
      { word: 'geopolitics', phonetic: '/ˌdʒiː.əʊˈpɒl.ɪ.tɪks/', meaning: 'Địa chính trị', example: 'Geopolitics shapes international relations and trade agreements.' },
      { word: 'ratification', phonetic: '/ˌræt.ɪ.fɪˈkeɪ.ʃən/', meaning: 'Sự phê chuẩn chính thức', example: 'The treaty required ratification by two-thirds of the senate.' },
      { word: 'détente', phonetic: '/deɪˈtɒnt/', meaning: 'Sự hòa hoãn giữa các quốc gia', example: 'The 1970s saw a period of détente between the US and USSR.' },
      { word: 'gerrymander', phonetic: '/ˈdʒer.i.mæn.dər/', meaning: 'Phân chia địa bàn bầu cử bất công', example: 'Critics accused the party of gerrymandering to gain electoral advantage.' },
      { word: 'communiqué', phonetic: '/kəˈmjuː.nɪ.keɪ/', meaning: 'Thông cáo chính thức', example: 'The summit ended with a joint communiqué on climate policy.' },
      { word: 'realpolitik', phonetic: '/ˈreɪ.əl.pɒ.lɪ.tiːk/', meaning: 'Chính trị thực dụng dựa trên sức mạnh', example: 'Realpolitik prioritizes national interest over moral ideals in diplomacy.' },
      { word: 'multilateral', phonetic: '/ˌmʌl.tiˈlæt.ər.əl/', meaning: 'Đa phương', example: 'The multilateral agreement involved thirty countries on five continents.' },
      { word: 'sanctions', phonetic: '/ˈsæŋk.ʃənz/', meaning: 'Biện pháp trừng phạt kinh tế', example: 'International sanctions were imposed on the regime after the invasion.' },
      { word: 'incumbent', phonetic: '/ɪnˈkʌm.bənt/', meaning: 'Đương chức, đang giữ quyền', example: 'The incumbent president faced a strong challenge in the election.' },
      { word: 'propaganda', phonetic: '/ˌprɒp.əˈɡæn.də/', meaning: 'Thông tin tuyên truyền', example: 'The regime used propaganda to control public perception of the war.' },
      { word: 'caucus', phonetic: '/ˈkɔː.kəs/', meaning: 'Cuộc họp nội bộ đảng phái', example: 'Party members gathered in a closed caucus to select their nominee.' },
      { word: 'quorum', phonetic: '/ˈkwɔː.rəm/', meaning: 'Số đại biểu tối thiểu để họp hợp lệ', example: 'The session was cancelled because there was no quorum present.' },
      { word: 'coalition', phonetic: '/ˌkəʊ.əˈlɪʃ.ən/', meaning: 'Liên minh chính trị', example: 'Three parties formed a coalition government after the inconclusive election.' },
      { word: 'unilateral', phonetic: '/ˌjuː.nɪˈlæt.ər.əl/', meaning: 'Đơn phương', example: 'The unilateral decision to withdraw troops drew international criticism.' },
      { word: 'oligarchy', phonetic: '/ˈɒl.ɪ.ɡɑː.ki/', meaning: 'Chế độ đầu sỏ chính trị', example: 'The country was effectively run as an oligarchy by a handful of wealthy elites.' },
      { word: 'rapprochement', phonetic: '/ræˈprɒʃ.mɒ̃/', meaning: 'Sự hòa giải ngoại giao', example: 'The summit marked a historic rapprochement between the two rival nations.' },
      { word: 'filibuster', phonetic: '/ˈfɪl.ɪ.bʌs.tər/', meaning: 'Chiến thuật trì hoãn lập pháp', example: 'The senator used a filibuster to delay the vote for over twelve hours.' },
      { word: 'junta', phonetic: '/ˈdʒʌn.tə/', meaning: 'Hội đồng quân sự cầm quyền', example: 'The military junta suspended the constitution after seizing power.' },
      { word: 'veto', phonetic: '/ˈviː.toʊ/', meaning: 'Quyền phủ quyết', example: 'The president used the veto to block the controversial legislation.' },
      { word: 'démarche', phonetic: '/deɪˈmɑːʃ/', meaning: 'Bước đi ngoại giao chính thức', example: 'The ambassador delivered a formal démarche protesting the border violation.' },
      { word: 'agenda', phonetic: '/əˈdʒen.də/', meaning: 'Các vấn đề quan trọng cần được giải quyết', example: 'The issue of climate policy is back at the top of the political agenda.' },
      { word: 'chancellor', phonetic: '/ˈtʃɑːn.səl.ər/', meaning: 'Thủ tướng hoặc lãnh đạo chính phủ ở một số nước', example: 'The German chancellor hosted a summit of EU leaders in Berlin.' },
      { word: 'charisma', phonetic: '/kəˈrɪz.mə/', meaning: 'Sức hút tự nhiên giúp ảnh hưởng đến người khác', example: 'He is a respected politician but he lacks charisma on the campaign trail.' },
      { word: 'coherence', phonetic: '/kəʊˈhɪə.rənts/', meaning: 'Sự mạch lạc, nhất quán trong lập luận hoặc chính sách', example: 'The party\'s policy lacks coherence and has confused many voters.' },
      { word: 'continuity', phonetic: '/ˌkɒn.tɪˈnjuː.ə.ti/', meaning: 'Sự tiếp nối, liên tục không bị gián đoạn', example: 'The election result ensured continuity of economic policy.' },
      { word: 'contradictory', phonetic: '/ˌkɒn.trəˈdɪk.tər.i/', meaning: 'Mâu thuẫn nhau, không thể cùng đúng', example: 'The ministers gave contradictory statements to the press.' },
      { word: 'deprivation', phonetic: '/ˌdep.rɪˈveɪ.ʃən/', meaning: 'Tình trạng thiếu thốn những thứ cần thiết', example: 'Urban deprivation remains a key challenge for the government.' },
      { word: 'devastation', phonetic: '/ˌdev.əˈsteɪ.ʃən/', meaning: 'Sự tàn phá nghiêm trọng do sự kiện bạo lực', example: 'The hurricane left a trail of devastation across the coastal region.' },
      { word: 'conversion', phonetic: '/kənˈvɜː.ʒən/', meaning: 'Sự chuyển đổi hình thức, mục đích hoặc chế độ', example: 'The country\'s conversion to democracy was a long and difficult process.' },
      { word: 'allege', phonetic: '/əˈledʒ/', meaning: 'Tuyên bố điều gì là thật mà không có bằng chứng', example: 'Several officials are alleged to have accepted bribes.' },
    ]
  },
  {
    id: 'c2_innovation', name: 'Innovation & The Future', nameVi: 'Đổi mới & Tương lai',
    icon: '🚀', color: '#16A34A',
    words: [
      { word: 'singularity', phonetic: '/ˌsɪŋ.ɡjʊˈlær.ɪ.ti/', meaning: 'Điểm kỳ dị công nghệ', example: 'Futurists debate when the technological singularity will occur.' },
      { word: 'transhumanism', phonetic: '/trænzˈhjuː.mə.nɪ.z(ə)m/', meaning: 'Chủ nghĩa siêu nhân học', example: 'Transhumanism advocates using technology to enhance human capabilities beyond biological limits.' },
      { word: 'obsolescence', phonetic: '/ˌɒb.sə.ˈles.əns/', meaning: 'Sự lỗi thời, lạc hậu', example: 'Planned obsolescence encourages consumers to replace devices more frequently.' },
      { word: 'proliferation', phonetic: '/prəˌlɪf.əˈreɪ.ʃən/', meaning: 'Sự lan rộng nhanh chóng', example: 'The proliferation of AI tools has transformed many industries.' },
      { word: 'interoperability', phonetic: '/ˌɪn.tər.ɒp.ər.ə.bɪl.ɪ.ti/', meaning: 'Khả năng tương tác giữa các hệ thống', example: 'Interoperability between healthcare systems is essential for patient safety.' },
      { word: 'paradigm shift', phonetic: '/ˈpær.ə.daɪm ʃɪft/', meaning: 'Sự thay đổi mô hình tư duy căn bản', example: 'The internet represented a paradigm shift in how information is shared.' },
      { word: 'exponential', phonetic: '/ˌek.spəˈnen.ʃəl/', meaning: 'Theo cấp số nhân', example: 'Computing power has grown at an exponential rate for decades.' },
      { word: 'decentralization', phonetic: '/ˌdiː.senˌtrəl.aɪˈzeɪ.ʃən/', meaning: 'Phi tập trung hóa', example: 'Blockchain enables the decentralization of financial transactions.' },
      { word: 'biometric', phonetic: '/ˌbaɪ.əˈmet.rɪk/', meaning: 'Sinh trắc học', example: 'Biometric authentication uses fingerprints or facial recognition to verify identity.' },
      { word: 'algorithmic', phonetic: '/ˌæl.ɡəˈrɪð.mɪk/', meaning: 'Theo thuật toán', example: 'Algorithmic bias can perpetuate social inequalities in AI systems.' },
      { word: 'nanotechnology', phonetic: '/ˌnæn.əʊ.tekˈnɒl.ə.dʒi/', meaning: 'Công nghệ nano', example: 'Nanotechnology could revolutionize drug delivery in medicine.' },
      { word: 'disruptive', phonetic: '/dɪsˈrʌp.tɪv/', meaning: 'Mang tính đột phá, phá vỡ hiện trạng', example: 'Ride-sharing apps proved to be a disruptive force in transportation.' },
      { word: 'omnipresent', phonetic: '/ˌɒm.nɪˈprez.ənt/', meaning: 'Hiện diện khắp nơi, phổ biến tuyệt đối', example: 'Social media has become omnipresent in every aspect of modern life.' },
      { word: 'convergence', phonetic: '/kənˈvɜː.dʒəns/', meaning: 'Sự hội tụ của các công nghệ', example: 'The convergence of AI, biotech, and robotics is reshaping the future.' },
      { word: 'quantitative', phonetic: '/ˈkwɒn.tɪ.tə.tɪv/', meaning: 'Thuộc về định lượng', example: 'Researchers rely on quantitative data to measure the impact of policies.' },
      { word: 'cryptography', phonetic: '/krɪpˈtɒɡ.rə.fi/', meaning: 'Mật mã học', example: 'Modern cryptography underpins the security of all online transactions.' },
      { word: 'cybernetics', phonetic: '/ˌsaɪ.bəˈnet.ɪks/', meaning: 'Điều khiển học', example: 'Cybernetics studies regulatory systems in both machines and living organisms.' },
      { word: 'superintelligence', phonetic: '/ˌsuː.pər.ɪnˈtel.ɪ.dʒəns/', meaning: 'Siêu trí tuệ nhân tạo', example: 'Researchers debate whether superintelligence poses an existential risk to humanity.' },
      { word: 'tokenization', phonetic: '/ˌtəʊ.kən.aɪˈzeɪ.ʃən/', meaning: 'Mã hóa token, token hóa', example: 'Tokenization of real-world assets is transforming how ownership is recorded and traded.' },
      { word: 'generative', phonetic: '/ˈdʒen.ər.ə.tɪv/', meaning: 'Tạo sinh (AI); có khả năng sáng tạo', example: 'Generative AI models can produce text, images, and music from simple prompts.' },
      { word: 'artificial intelligence', phonetic: '/ˌɑː.tɪˌfɪʃ.əl.ɪnˈtel.ɪ.dʒənts/', meaning: 'Trí tuệ nhân tạo', example: 'Artificial intelligence is transforming industries from medicine to finance.' },
      { word: 'unprecedented', phonetic: '/ʌnˈpres.ɪ.dən.tɪd/', meaning: 'Chưa từng xảy ra trước đây', example: 'The internet has given people unprecedented access to information.' },
      { word: 'refine', phonetic: '/rɪˈfaɪn/', meaning: 'Cải tiến bằng cách thực hiện các thay đổi nhỏ', example: 'The engineers spent months refining the software before release.' },
      { word: 'dominance', phonetic: '/ˈdɒm.ɪ.nənts/', meaning: 'Quyền lực, ảnh hưởng và sự kiểm soát', example: 'The company\'s dominance in the software industry is unchallenged.' },
    ]
  },
  {
    id: 'c2_linguistics', name: 'Linguistics & Semantics', nameVi: 'Ngôn ngữ học',
    icon: '🔤', color: '#7C3AED',
    words: [
      { word: 'morphology', phonetic: '/mɔːˈfɒl.ə.dʒi/', meaning: 'Hình thái học', example: 'Morphology studies how words are constructed from smaller meaningful units called morphemes.' },
      { word: 'phonology', phonetic: '/fəˈnɒl.ə.dʒi/', meaning: 'Âm vị học', example: 'Phonology analyzes the sound system and phoneme patterns of a given language.' },
      { word: 'semantics', phonetic: '/sɪˈmæn.tɪks/', meaning: 'Ngữ nghĩa học', example: 'Semantics investigates how meaning is encoded and interpreted in language.' },
      { word: 'pragmatics', phonetic: '/præɡˈmæt.ɪks/', meaning: 'Dụng học ngôn ngữ', example: 'Pragmatics examines how context shapes the interpretation of utterances.' },
      { word: 'syntax', phonetic: '/ˈsɪn.tæks/', meaning: 'Cú pháp học', example: 'Syntax describes the rules governing sentence structure within a language.' },
      { word: 'lexicon', phonetic: '/ˈlek.sɪ.kɒn/', meaning: 'Vốn từ vựng, từ điển', example: 'The mental lexicon is the organized store of words that a speaker knows.' },
      { word: 'etymology', phonetic: '/ˌet.ɪˈmɒl.ə.dʒi/', meaning: 'Từ nguyên học', example: 'Etymology traces the historical origins and evolution of words.' },
      { word: 'polysemy', phonetic: '/pɒˈlɪs.ɪ.mi/', meaning: 'Tính đa nghĩa', example: 'Polysemy occurs when a single word carries multiple related meanings.' },
      { word: 'cognate', phonetic: '/ˈkɒɡ.neɪt/', meaning: 'Từ đồng gốc', example: 'English "night" and German "Nacht" are cognates derived from a common ancestor.' },
      { word: 'diachronic', phonetic: '/ˌdaɪ.əˈkrɒn.ɪk/', meaning: 'Lịch đại (xuyên thời gian)', example: 'Diachronic linguistics studies how language changes and evolves over time.' },
      { word: 'pidgin', phonetic: '/ˈpɪdʒ.ɪn/', meaning: 'Ngôn ngữ bồi', example: 'A pidgin develops as a contact language when speakers share no common tongue.' },
      { word: 'dialect', phonetic: '/ˈdaɪ.ə.lekt/', meaning: 'Phương ngữ, tiếng địa phương', example: 'Regional dialects reflect the cultural and historical diversity within a language.' },
      { word: 'connotation', phonetic: '/ˌkɒn.əˈteɪ.ʃən/', meaning: 'Hàm ý, nghĩa ngầm', example: 'The word "slim" has a positive connotation while "skinny" can carry a negative one.' },
      { word: 'ambiguity', phonetic: '/ˌæm.bɪˈɡjuː.ɪ.ti/', meaning: 'Sự mơ hồ về nghĩa', example: 'Syntactic ambiguity arises when a sentence can be interpreted in more than one way.' },
      { word: 'bilingualism', phonetic: '/ˌbaɪˈlɪŋ.ɡwəl.ɪ.z(ə)m/', meaning: 'Chủ nghĩa song ngữ', example: 'Research suggests that bilingualism may enhance cognitive flexibility and executive function.' },
      { word: 'creole', phonetic: '/ˈkriː.oʊl/', meaning: 'Ngôn ngữ creole', example: 'Haitian Creole developed from French and African languages spoken by enslaved populations.' },
      { word: 'sociolinguistics', phonetic: '/ˌsoʊ.si.oʊ.lɪŋˈɡwɪs.tɪks/', meaning: 'Xã hội ngôn ngữ học', example: 'Sociolinguistics examines how language use varies across different social groups.' },
      { word: 'phoneme', phonetic: '/ˈfəʊ.niːm/', meaning: 'Âm vị', example: 'English has approximately 44 phonemes, though only 26 letters to represent them.' },
      { word: 'metonymy', phonetic: '/mɪˈtɒn.ɪ.mi/', meaning: 'Phép hoán dụ', example: '"The White House announced" is a metonymy for the US presidential administration.' },
      { word: 'transliteration', phonetic: '/trænsˌlɪt.ərˈeɪ.ʃən/', meaning: 'Phiên âm, chuyển tự', example: 'Transliteration converts text from one writing system into another phonetically.' },
    ]
  },
  {
    id: 'c2_economics', name: 'Economic Theory', nameVi: 'Kinh tế học',
    icon: '📊', color: '#0284C7',
    words: [
      { word: 'macroeconomics', phonetic: '/ˌmæk.roʊ.iːkəˈnɒm.ɪks/', meaning: 'Kinh tế vĩ mô', example: 'Macroeconomics examines the behavior of entire national and global economies.' },
      { word: 'oligopoly', phonetic: '/ˌɒl.ɪˈɡɒp.ə.li/', meaning: 'Độc quyền nhóm', example: 'The telecommunications sector in many countries operates as an oligopoly.' },
      { word: 'arbitrage', phonetic: '/ˈɑː.bɪ.trɑːʒ/', meaning: 'Kinh doanh chênh lệch giá', example: 'Arbitrage exploits price differences across markets to generate risk-free profits.' },
      { word: 'liquidity', phonetic: '/lɪˈkwɪd.ɪ.ti/', meaning: 'Tính thanh khoản', example: 'A liquidity crisis occurs when institutions cannot meet their short-term obligations.' },
      { word: 'elasticity', phonetic: '/ɪˌlæs.tɪˈsɪt.i/', meaning: 'Độ co giãn (cung-cầu)', example: 'Price elasticity measures how strongly demand responds to changes in price.' },
      { word: 'mercantilism', phonetic: '/ˈmɜː.kən.tɪ.lɪ.z(ə)m/', meaning: 'Chủ nghĩa trọng thương', example: 'Mercantilism favored maximizing exports and accumulating national wealth through trade.' },
      { word: 'stagflation', phonetic: '/stæɡˈfleɪ.ʃən/', meaning: 'Lạm phát đình trệ', example: 'The 1970s saw prolonged stagflation combining high inflation with economic stagnation.' },
      { word: 'austerity', phonetic: '/ɒˈster.ɪ.ti/', meaning: 'Chính sách thắt lưng buộc bụng', example: 'Austerity measures cut public spending but deepened the recession\'s social impact.' },
      { word: 'depreciation', phonetic: '/dɪˌpriː.ʃiˈeɪ.ʃən/', meaning: 'Sự mất giá (tiền tệ/tài sản)', example: 'Currency depreciation makes exports cheaper but increases the cost of imports.' },
      { word: 'fiscal', phonetic: '/ˈfɪs.kəl/', meaning: 'Thuộc về ngân sách, tài khóa', example: 'Fiscal policy uses government spending and taxation to manage economic growth.' },
      { word: 'collateral', phonetic: '/kəˈlæt.ər.əl/', meaning: 'Tài sản thế chấp', example: 'The bank required property as collateral before approving the mortgage.' },
      { word: 'speculative', phonetic: '/ˈspek.jʊ.lə.tɪv/', meaning: 'Đầu cơ, mang tính rủi ro', example: 'Speculative investment in volatile assets carries significant financial risk.' },
      { word: 'recession', phonetic: '/rɪˈseʃ.ən/', meaning: 'Suy thoái kinh tế', example: 'The global recession of 2008 caused widespread unemployment and financial hardship.' },
      { word: 'derivatives', phonetic: '/dɪˈrɪv.ə.tɪvz/', meaning: 'Công cụ tài chính phái sinh', example: 'Financial derivatives allow investors to hedge against market risks.' },
      { word: 'monetarism', phonetic: '/ˈmʌn.ɪ.tər.ɪ.z(ə)m/', meaning: 'Chủ nghĩa tiền tệ', example: 'Monetarism argues that controlling the money supply is the key to price stability.' },
      { word: 'microeconomics', phonetic: '/ˌmaɪ.krəʊ.iːkəˈnɒm.ɪks/', meaning: 'Kinh tế vi mô', example: 'Microeconomics analyzes how individuals and firms make decisions about scarce resources.' },
      { word: 'equilibrium', phonetic: '/ˌiː.kwɪˈlɪb.ri.əm/', meaning: 'Trạng thái cân bằng', example: 'The market reaches equilibrium when supply exactly matches demand.' },
      { word: 'protectionism', phonetic: '/prəˈtek.ʃən.ɪ.z(ə)m/', meaning: 'Chủ nghĩa bảo hộ thương mại', example: 'Protectionism uses tariffs and quotas to shield domestic industries from foreign competition.' },
      { word: 'laissez-faire', phonetic: '/ˌles.eɪˈfeər/', meaning: 'Chính sách tự do kinh tế', example: 'A laissez-faire approach leaves markets largely free from government intervention.' },
      { word: 'hyperinflation', phonetic: '/ˌhaɪ.pər.ɪnˈfleɪ.ʃən/', meaning: 'Siêu lạm phát', example: 'Zimbabwe experienced devastating hyperinflation in the late 2000s.' },
      { word: 'capitalism', phonetic: '/ˈkæp.ɪ.təl.ɪ.zəm/', meaning: 'Chủ nghĩa tư bản, hệ thống kinh tế sở hữu tư nhân', example: 'Modern capitalism has shaped the structure of the global economy.' },
      { word: 'capitalist', phonetic: '/ˈkæp.ɪ.təl.ɪst/', meaning: 'Liên quan đến chủ nghĩa tư bản', example: 'They adopted a capitalist model after decades of state control.' },
      { word: 'surplus', phonetic: '/ˈsɜːp.ləs/', meaning: 'Lượng dư thừa vượt quá nhu cầu', example: 'The country ran a large trade surplus for the third consecutive year.' },
      { word: 'thriving', phonetic: '/ˈθraɪ.vɪŋ/', meaning: 'Phát triển mạnh mẽ và thành công', example: 'The city has a thriving economy driven by technology and finance.' },
      { word: 'incur', phonetic: '/ɪnˈkɜːr/', meaning: 'Gánh chịu khoản nợ hoặc tổn thất tài chính', example: 'The company incurred huge losses as a result of its failed investments.' },
      { word: 'indicator', phonetic: '/ˈɪn.dɪ.keɪ.tər/', meaning: 'Chỉ số phản ánh tình trạng kinh tế', example: 'Commodity prices can be a useful indicator of inflationary trends.' },
      { word: 'dynamic', phonetic: '/daɪˈnæm.ɪk/', meaning: 'Thay đổi liên tục và đầy năng lượng', example: 'A dynamic economy adapts quickly to technological disruption.' },
      { word: 'monetary', phonetic: '/ˈmʌn.ɪ.tri/', meaning: 'Liên quan đến tiền tệ', example: 'The central bank adjusted its monetary policy to control inflation.' },
      { word: 'deepen', phonetic: '/ˈdiː.pən/', meaning: 'Trở nên tồi tệ hơn hoặc mạnh hơn', example: 'The economic crisis deepened as unemployment rose sharply.' },
      { word: 'trader', phonetic: '/ˈtreɪ.dər/', meaning: 'Người mua và bán hàng hóa', example: 'Currency traders reacted quickly to the central bank\'s announcement.' },
    ]
  },
  {
    id: 'c2_cognition', name: 'Cognition & Neuroscience', nameVi: 'Thần kinh học',
    icon: '🧬', color: '#EA580C',
    words: [
      { word: 'neuroplasticity', phonetic: '/ˌnjʊər.oʊ.plæˈstɪs.ɪ.ti/', meaning: 'Tính dẻo thần kinh', example: 'Neuroplasticity allows the brain to reorganize and adapt in response to new experiences.' },
      { word: 'metacognition', phonetic: '/ˌmet.ə.kɒɡˈnɪʃ.ən/', meaning: 'Siêu nhận thức', example: 'Metacognition refers to the ability to reflect on and regulate one\'s own thinking processes.' },
      { word: 'heuristic', phonetic: '/hjʊˈrɪs.tɪk/', meaning: 'Phép phát hiện; lối tư duy rút gọn', example: 'Cognitive heuristics are mental shortcuts that simplify complex decision-making.' },
      { word: 'schema', phonetic: '/ˈskiː.mə/', meaning: 'Sơ đồ nhận thức', example: 'We use mental schemas to organize and interpret new information about the world.' },
      { word: 'neurotransmitter', phonetic: '/ˌnjʊər.oʊˌtræns.ˈmɪt.ər/', meaning: 'Chất dẫn truyền thần kinh', example: 'Dopamine is a neurotransmitter associated with reward, motivation, and pleasure.' },
      { word: 'synaptic', phonetic: '/sɪˈnæp.tɪk/', meaning: 'Thuộc về xi-náp thần kinh', example: 'Synaptic connections between neurons strengthen through repeated activation.' },
      { word: 'volition', phonetic: '/vəˈlɪʃ.ən/', meaning: 'Ý chí, sự tự quyết', example: 'The study debates whether human volition is constrained by neurological determinism.' },
      { word: 'prefrontal', phonetic: '/ˌpriːˈfrʌn.tl/', meaning: 'Thuộc vỏ não trước trán', example: 'The prefrontal cortex governs complex decision-making and impulse control.' },
      { word: 'limbic', phonetic: '/ˈlɪm.bɪk/', meaning: 'Thuộc hệ viền não', example: 'The limbic system plays a central role in processing emotions and forming memories.' },
      { word: 'priming', phonetic: '/ˈpraɪ.mɪŋ/', meaning: 'Hiệu ứng kích hoạt nhận thức', example: 'Priming occurs when exposure to one stimulus influences the response to a later stimulus.' },
      { word: 'confabulation', phonetic: '/kənˌfæb.jʊˈleɪ.ʃən/', meaning: 'Bịa chuyện vô thức (bệnh lý)', example: 'Patients with amnesia sometimes engage in confabulation, generating plausible but false memories.' },
      { word: 'lateralization', phonetic: '/ˌlæt.ər.əl.aɪˈzeɪ.ʃən/', meaning: 'Sự phân vùng chức năng não', example: 'Brain lateralization refers to each hemisphere\'s tendency to specialize in certain functions.' },
      { word: 'introspection', phonetic: '/ˌɪn.trəˈspek.ʃən/', meaning: 'Nội tâm, tự quan sát', example: 'Introspection involves examining one\'s own thoughts, feelings, and mental states.' },
      { word: 'dopamine', phonetic: '/ˈdoʊ.pə.miːn/', meaning: 'Dopamine, chất dẫn thần kinh', example: 'Low dopamine levels are associated with reduced motivation and symptoms of depression.' },
      { word: 'cortex', phonetic: '/ˈkɔː.teks/', meaning: 'Vỏ não', example: 'The cerebral cortex is responsible for higher cognitive functions such as language and reasoning.' },
      { word: 'serotonin', phonetic: '/ˌser.əˈtoʊ.nɪn/', meaning: 'Serotonin (chất dẫn truyền thần kinh)', example: 'Serotonin plays a key role in regulating mood, sleep, and appetite.' },
      { word: 'proprioception', phonetic: '/ˌprəʊ.pri.əˈsep.ʃən/', meaning: 'Cảm giác vị trí cơ thể', example: 'Proprioception allows us to sense the position and movement of our own limbs without looking.' },
      { word: 'amygdala', phonetic: '/əˈmɪɡ.də.lə/', meaning: 'Hạch hạnh nhân (não)', example: 'The amygdala is responsible for processing fear and other strong emotional responses.' },
      { word: 'mnemonics', phonetic: '/nɪˈmɒn.ɪks/', meaning: 'Kỹ thuật/phương pháp ghi nhớ', example: 'Students use mnemonics such as acronyms to memorize complex information.' },
      { word: 'neurogenesis', phonetic: '/ˌnjʊər.əˈdʒen.ɪ.sɪs/', meaning: 'Sự hình thành nơ-ron thần kinh mới', example: 'Research suggests that regular exercise promotes neurogenesis in the hippocampus.' },
      { word: 'detached', phonetic: '/dɪˈtætʃt/', meaning: 'Không bị ảnh hưởng về mặt cảm xúc, khách quan', example: 'A good therapist tries to remain detached when listening to clients.' },
      { word: 'detrimental', phonetic: '/ˌdet.rɪˈmen.təl/', meaning: 'Gây hại hoặc tổn hại', example: 'Excessive screen time can have a detrimental effect on concentration.' },
      { word: 'discreet', phonetic: '/dɪˈskriːt/', meaning: 'Cẩn thận không gây xấu hổ hoặc thu hút sự chú ý', example: 'Can I trust you to be discreet about what I\'ve told you?' },
      { word: 'disturbed', phonetic: '/dɪˈstɜːbd/', meaning: 'Không suy nghĩ hoặc hành xử bình thường vì vấn đề tâm lý', example: 'The therapist worked with deeply disturbed children.' },
      { word: 'engrossed', phonetic: '/ɪnˈgrəʊst/', meaning: 'Tập trung hoàn toàn vào điều gì đó', example: 'She was so engrossed in the book that she missed her stop.' },
      { word: 'conscious', phonetic: '/ˈkɒn.tʃəs/', meaning: 'Cố ý, có nhận thức; quyết định có chủ đích', example: 'Did you make a conscious decision to change your behaviour?' },
      { word: 'unconscious', phonetic: '/ʌnˈkɒn.tʃəs/', meaning: 'Suy nghĩ hoặc cảm xúc mà bạn không ý thức được', example: 'Many of our biases operate at an unconscious level.' },
      { word: 'perception', phonetic: '/pəˈsep.ʃən/', meaning: 'Nhận thức, quan điểm về ai đó hoặc điều gì đó', example: 'Public perception of the crisis shifted dramatically overnight.' },
      { word: 'intuition', phonetic: '/ˌɪn.tjuˈɪ.ʃən/', meaning: 'Cảm giác biết điều gì đó mà không giải thích được', example: 'Her approach to leadership is based on both data and intuition.' },
    ]
  },
  {
    id: 'c2_ecology', name: 'Ecology & Earth Sciences', nameVi: 'Sinh thái học',
    icon: '🌿', color: '#15803D',
    words: [
      { word: 'biomass', phonetic: '/ˈbaɪ.oʊ.mæs/', meaning: 'Sinh khối', example: 'Biomass energy is derived from organic materials such as wood and crop waste.' },
      { word: 'trophic', phonetic: '/ˈtrɒf.ɪk/', meaning: 'Thuộc chuỗi dinh dưỡng sinh thái', example: 'Energy is transferred between trophic levels as organisms consume one another.' },
      { word: 'symbiosis', phonetic: '/ˌsɪm.baɪˈoʊ.sɪs/', meaning: 'Quan hệ cộng sinh', example: 'The relationship between bees and flowering plants is a classic example of symbiosis.' },
      { word: 'lithosphere', phonetic: '/ˈlɪθ.ə.sfɪər/', meaning: 'Thạch quyển', example: 'Tectonic plate movement originates within the rigid outer layer known as the lithosphere.' },
      { word: 'biome', phonetic: '/ˈbaɪ.oʊm/', meaning: 'Quần xã sinh vật', example: 'The tropical rainforest is the most biologically diverse biome on Earth.' },
      { word: 'permafrost', phonetic: '/ˈpɜː.mə.frɒst/', meaning: 'Đất đóng băng vĩnh cửu', example: 'Thawing permafrost releases vast quantities of methane, accelerating climate change.' },
      { word: 'eutrophication', phonetic: '/juːˌtrɒf.ɪˈkeɪ.ʃən/', meaning: 'Sự phú dưỡng', example: 'Agricultural runoff causes eutrophication, depleting oxygen levels in lakes and rivers.' },
      { word: 'anthropogenic', phonetic: '/ˌæn.θrə.pəˈdʒen.ɪk/', meaning: 'Do con người gây ra', example: 'The scientific consensus holds that recent climate change is primarily anthropogenic.' },
      { word: 'sequestration', phonetic: '/ˌsiː.kwɪˈstreɪ.ʃən/', meaning: 'Sự cô lập (carbon)', example: 'Carbon sequestration by forests helps offset greenhouse gas emissions significantly.' },
      { word: 'glaciation', phonetic: '/ˌɡleɪ.siˈeɪ.ʃən/', meaning: 'Sự băng hà', example: 'Evidence of past glaciation can be seen in the U-shaped valleys of highland regions.' },
      { word: 'phenology', phonetic: '/fɪˈnɒl.ə.dʒi/', meaning: 'Vật hậu học', example: 'Phenology tracks how seasonal cycles in plant and animal behavior respond to climate.' },
      { word: 'biodegradable', phonetic: '/ˌbaɪ.oʊ.dɪˈɡreɪ.də.bəl/', meaning: 'Có thể phân hủy sinh học', example: 'Using biodegradable packaging is a simple step toward reducing environmental waste.' },
      { word: 'stratosphere', phonetic: '/ˈstræt.ə.sfɪər/', meaning: 'Tầng bình lưu', example: 'The protective ozone layer is located in the stratosphere above the troposphere.' },
      { word: 'leaching', phonetic: '/ˈliːtʃ.ɪŋ/', meaning: 'Sự rửa trôi (khoáng chất)', example: 'Acid rain causes leaching of vital nutrients from the soil, harming plant growth.' },
      { word: 'savanna', phonetic: '/səˈvæn.ə/', meaning: 'Đồng cỏ nhiệt đới', example: 'The annual wildebeest migration across the African savanna is one of nature\'s greatest spectacles.' },
      { word: 'rewilding', phonetic: '/riːˈwaɪl.dɪŋ/', meaning: 'Tái hoang dã hóa', example: 'Rewilding projects aim to restore natural habitats and reintroduce native species.' },
      { word: 'salinization', phonetic: '/ˌsæl.ɪ.naɪˈzeɪ.ʃən/', meaning: 'Sự nhiễm mặn đất', example: 'Salinization of farmland is reducing agricultural productivity in arid regions.' },
      { word: 'afforestation', phonetic: '/əˌfɒr.ɪˈsteɪ.ʃən/', meaning: 'Trồng rừng ở vùng đất mới', example: 'Afforestation programs are planting millions of trees to combat desertification.' },
      { word: 'microbiome', phonetic: '/ˌmaɪ.krəʊˈbaɪ.oʊm/', meaning: 'Hệ vi sinh vật', example: 'The soil microbiome plays a crucial role in nutrient cycling and plant health.' },
      { word: 'benthic', phonetic: '/ˈben.θɪk/', meaning: 'Thuộc đáy đại dương/hồ', example: 'Benthic organisms live on or near the bottom of oceans, lakes, and rivers.' },
    ]
  },
  {
    id: 'c2_history', name: 'History & Civilization', nameVi: 'Lịch sử & Văn minh',
    icon: '🏺', color: '#92400E',
    words: [
      { word: 'antiquity', phonetic: '/ænˈtɪk.wɪ.ti/', meaning: 'Thời cổ đại', example: 'Many foundational philosophical ideas trace their origins to classical antiquity.' },
      { word: 'imperialism', phonetic: '/ɪmˈpɪər.i.ə.lɪ.z(ə)m/', meaning: 'Chủ nghĩa đế quốc', example: 'European imperialism profoundly shaped the political landscape of Asia and Africa.' },
      { word: 'feudalism', phonetic: '/ˈfjuː.dəl.ɪ.z(ə)m/', meaning: 'Chế độ phong kiến', example: 'Feudalism organized medieval European society around land ownership and military service.' },
      { word: 'renaissance', phonetic: '/ˈren.ɪ.sɑːns/', meaning: 'Thời kỳ Phục Hưng', example: 'The Renaissance marked a profound renewal of interest in classical art, science, and learning.' },
      { word: 'totalitarianism', phonetic: '/toʊˌtæl.ɪˈteər.i.ə.nɪ.z(ə)m/', meaning: 'Chủ nghĩa toàn trị', example: 'Totalitarianism exerts absolute control over all aspects of public and private life.' },
      { word: 'colonialism', phonetic: '/kəˈloʊ.ni.ə.lɪ.z(ə)m/', meaning: 'Chủ nghĩa thực dân', example: 'Colonialism created lasting economic and cultural inequalities that persist to this day.' },
      { word: 'genocide', phonetic: '/ˈdʒen.ə.saɪd/', meaning: 'Tội diệt chủng', example: 'The international community has a responsibility to prevent and prosecute genocide.' },
      { word: 'apartheid', phonetic: '/əˈpɑːt.heɪt/', meaning: 'Chế độ phân biệt chủng tộc', example: 'Apartheid in South Africa was dismantled after decades of resistance and international pressure.' },
      { word: 'dynasty', phonetic: '/ˈdɪn.ə.sti/', meaning: 'Triều đại', example: 'The Han Dynasty remains one of the most influential periods in all of Chinese history.' },
      { word: 'caste', phonetic: '/kɑːst/', meaning: 'Đẳng cấp xã hội', example: 'India\'s ancient caste system is one of the world\'s most enduring social hierarchies.' },
      { word: 'theocracy', phonetic: '/θiˈɒk.rə.si/', meaning: 'Thần quyền chính trị', example: 'A theocracy governs society according to religious law and claims of divine authority.' },
      { word: 'schism', phonetic: '/ˈskɪ.z(ə)m/', meaning: 'Sự ly giáo, chia rẽ', example: 'The Great Schism of 1054 permanently divided Christianity into Eastern and Western branches.' },
      { word: 'manifesto', phonetic: '/ˌmæn.ɪˈfes.toʊ/', meaning: 'Tuyên ngôn, cương lĩnh', example: 'The Communist Manifesto outlined a radical vision for a classless, egalitarian society.' },
      { word: 'emancipation', phonetic: '/ɪˌmæn.sɪˈpeɪ.ʃən/', meaning: 'Sự giải phóng', example: 'The Emancipation Proclamation of 1863 was a landmark step toward abolishing slavery.' },
      { word: 'absolutism', phonetic: '/ˈæb.sə.luː.tɪ.z(ə)m/', meaning: 'Chủ nghĩa chuyên chế tuyệt đối', example: 'Absolutism vested all political power in a single monarch without constitutional limits.' },
      { word: 'historiography', phonetic: '/hɪˌstɒr.iˈɒɡ.rə.fi/', meaning: 'Sử học, phương pháp viết lịch sử', example: 'Historiography examines how historical narratives are constructed and interpreted over time.' },
      { word: 'irredentism', phonetic: '/ˌɪr.ɪˈden.tɪ.z(ə)m/', meaning: 'Chủ nghĩa thống nhất lãnh thổ', example: 'Irredentism drives political movements seeking to reunite ethnic groups divided by borders.' },
      { word: 'revisionism', phonetic: '/rɪˈvɪʒ.ən.ɪ.z(ə)m/', meaning: 'Chủ nghĩa xét lại lịch sử', example: 'Historical revisionism challenges established interpretations of past events and their causes.' },
      { word: 'annexation', phonetic: '/ˌæn.ekˈseɪ.ʃən/', meaning: 'Sự sáp nhập lãnh thổ', example: 'The annexation of Crimea in 2014 drew widespread international condemnation.' },
      { word: 'suffrage', phonetic: '/ˈsʌf.rɪdʒ/', meaning: 'Quyền bầu cử', example: 'The suffrage movement fought for decades before women were granted the right to vote.' },
      { word: 'casualty', phonetic: '/ˈkæʒ.ju.əl.ti/', meaning: 'Người bị thương hoặc tử vong trong chiến tranh', example: 'Both sides in the conflict promised to minimise civilian casualties.' },
      { word: 'combat', phonetic: '/ˈkɒm.bæt/', meaning: 'Chiến đấu, đặc biệt trong chiến tranh', example: 'The aircraft was shot down in combat over enemy territory.' },
      { word: 'exile', phonetic: '/ˈek.saɪl/', meaning: 'Bị buộc phải rời khỏi đất nước và sống ở nơi khác', example: 'He spent the war years in exile in New York before returning home.' },
      { word: 'memorial', phonetic: '/məˈmɔː.ri.əl/', meaning: 'Công trình tưởng niệm người hoặc sự kiện lịch sử', example: 'A new war memorial was unveiled in the town square.' },
      { word: 'hostility', phonetic: '/hɒsˈtɪl.ə.ti/', meaning: 'Thái độ thù địch, không thân thiện', example: 'There was open hostility between the two factions throughout the talks.' },
      { word: 'brink', phonetic: '/brɪŋk/', meaning: 'Ngay trước thời điểm điều gì quan trọng xảy ra', example: 'The two countries were on the brink of war.' },
      { word: 'occupation', phonetic: '/ˌɒk.jəˈpeɪ.ʃən/', meaning: 'Sự chiếm đóng của quân đội', example: 'The resistance movement continued to fight throughout the occupation.' },
    ]
  },
  {
    id: 'c2_medicine', name: 'Medicine & Bioethics', nameVi: 'Y học & Đạo đức sinh học',
    icon: '💉', color: '#E11D48',
    words: [
      { word: 'pathogen', phonetic: '/ˈpæθ.ə.dʒen/', meaning: 'Mầm bệnh', example: 'Pathogens include bacteria, viruses, and fungi that invade the body and cause disease.' },
      { word: 'prognosis', phonetic: '/prɒɡˈnoʊ.sɪs/', meaning: 'Tiên lượng bệnh', example: 'The doctor gave a cautious prognosis and recommended continued monitoring.' },
      { word: 'biopsy', phonetic: '/ˈbaɪ.ɒp.si/', meaning: 'Sinh thiết', example: 'A biopsy was taken from the suspicious tissue to determine whether it was malignant.' },
      { word: 'carcinogen', phonetic: '/kɑːˈsɪn.ə.dʒen/', meaning: 'Chất gây ung thư', example: 'Tobacco smoke contains dozens of known carcinogens that damage DNA over time.' },
      { word: 'immunotherapy', phonetic: '/ɪˌmjuː.noʊˈθer.ə.pi/', meaning: 'Liệu pháp miễn dịch', example: 'Immunotherapy has revolutionized treatment outcomes for certain aggressive cancers.' },
      { word: 'genome', phonetic: '/ˈdʒiː.noʊm/', meaning: 'Hệ gen, bộ gene', example: 'Sequencing the human genome has opened new possibilities in personalized medicine.' },
      { word: 'mutation', phonetic: '/mjuːˈteɪ.ʃən/', meaning: 'Đột biến', example: 'A genetic mutation in the BRCA1 gene significantly increases the risk of breast cancer.' },
      { word: 'oncology', phonetic: '/ɒŋˈkɒl.ə.dʒi/', meaning: 'Ung thư học', example: 'Advances in oncology have dramatically improved survival rates for many types of cancer.' },
      { word: 'iatrogenic', phonetic: '/ˌaɪ.æt.rəˈdʒen.ɪk/', meaning: 'Do can thiệp y tế gây ra', example: 'Iatrogenic infections occur when medical procedures inadvertently introduce harmful pathogens.' },
      { word: 'euthanasia', phonetic: '/ˌjuː.θəˈneɪ.zi.ə/', meaning: 'Cái chết êm ái (an tử)', example: 'The ethics of euthanasia are debated across medical, legal, and religious communities.' },
      { word: 'surrogacy', phonetic: '/ˈsʌr.ə.ɡə.si/', meaning: 'Mang thai hộ', example: 'Surrogacy raises profound legal and ethical questions about parenthood and bodily autonomy.' },
      { word: 'placebo', phonetic: '/pləˈsiː.boʊ/', meaning: 'Thuốc giả; hiệu ứng giả dược', example: 'The placebo effect demonstrates the powerful connection between expectation and physical outcome.' },
      { word: 'triage', phonetic: '/ˈtriː.ɑːʒ/', meaning: 'Phân loại bệnh nhân ưu tiên', example: 'Emergency triage ensures the most critically injured patients receive immediate care.' },
      { word: 'anesthesia', phonetic: '/ˌæn.ɪsˈθiː.zi.ə/', meaning: 'Gây mê, gây tê', example: 'Modern anesthesia has made complex surgical procedures safe and essentially painless.' },
      { word: 'palliative', phonetic: '/ˈpæl.i.ə.tɪv/', meaning: 'Giảm nhẹ triệu chứng (không chữa khỏi)', example: 'Palliative care prioritizes comfort and dignity for patients with terminal illness.' },
      { word: 'telemedicine', phonetic: '/ˈtel.ɪ.med.ɪ.sɪn/', meaning: 'Y tế từ xa', example: 'Telemedicine allows patients to consult doctors remotely via video calls.' },
      { word: 'epidemiology', phonetic: '/ˌep.ɪ.diː.miˈɒl.ə.dʒi/', meaning: 'Dịch tễ học', example: 'Epidemiology studies the distribution and determinants of disease in populations.' },
      { word: 'nosocomial', phonetic: '/ˌnɒs.əˈkəʊ.mi.əl/', meaning: 'Nhiễm khuẩn bệnh viện', example: 'Nosocomial infections acquired in hospitals pose a serious challenge to public health.' },
      { word: 'prophylaxis', phonetic: '/ˌprəʊ.fɪˈlæk.sɪs/', meaning: 'Dự phòng bệnh', example: 'Pre-exposure prophylaxis significantly reduces the risk of HIV infection.' },
      { word: 'comorbidity', phonetic: '/ˌkəʊ.mɔːˈbɪd.ɪ.ti/', meaning: 'Đa bệnh tật đồng thời', example: 'Patients with comorbidities such as diabetes face higher risks from respiratory infections.' },
      { word: 'complication', phonetic: '/ˌkɒm.plɪˈkeɪ.ʃən/', meaning: 'Vấn đề y tế mới phát sinh khi đã bệnh', example: 'Eye problems can be a complication of poorly controlled diabetes.' },
      { word: 'contraceptive', phonetic: '/ˌkɒn.trəˈsep.tɪv/', meaning: 'Thuốc hoặc dụng cụ ngừa thai', example: 'Access to contraceptives is essential for reproductive health.' },
      { word: 'frail', phonetic: '/freɪl/', meaning: 'Yếu ớt, không khỏe mạnh', example: 'The elderly patient was too frail to undergo major surgery.' },
      { word: 'incurable', phonetic: '/ɪnˈkjʊə.rə.bl̩/', meaning: 'Không thể chữa khỏi', example: 'The diagnosis revealed an incurable progressive disease.' },
      { word: 'infectious', phonetic: '/ɪnˈfek.ʃəs/', meaning: 'Có thể lây từ người này sang người khác', example: 'Hepatitis B is highly infectious and can survive outside the body.' },
      { word: 'immune system', phonetic: '/ɪˈmjuːnˌsɪs.təm/', meaning: 'Hệ thống miễn dịch bảo vệ cơ thể', example: 'A healthy diet strengthens the immune system against infections.' },
      { word: 'injection', phonetic: '/ɪnˈdʒek.ʃən/', meaning: 'Tiêm thuốc vào cơ thể bằng kim tiêm', example: 'The patient required a daily injection of insulin.' },
      { word: 'antibiotic', phonetic: '/ˌæn.tɪ.baɪˈɒ.tɪk/', meaning: 'Thuốc kháng sinh tiêu diệt vi khuẩn gây bệnh', example: 'Antibiotic resistance is one of the greatest threats to public health.' },
    ]
  },

  // ── 2 new C2 topics ───────────────────────────────────────────
  {
    id: 'c2_religion', name: 'Religion & Belief Systems', nameVi: 'Tôn giáo & Hệ thống niềm tin',
    icon: '🕌', color: '#FFB300',
    words: [
      { word: 'secular', phonetic: '/ˈsek.jʊ.lər/', meaning: 'Phi tôn giáo, thế tục', example: 'France operates as a secular state with a strict separation of church and government.' },
      { word: 'doctrine', phonetic: '/ˈdɒk.trɪn/', meaning: 'Giáo lý, học thuyết', example: 'Church doctrine on this issue has remained unchanged for centuries.' },
      { word: 'pilgrimage', phonetic: '/ˈpɪl.ɡrɪ.mɪdʒ/', meaning: 'Hành hương, chuyến đi đến nơi linh thiêng', example: 'Millions of Muslims undertake a pilgrimage to Mecca every year.' },
      { word: 'monotheism', phonetic: '/ˈmɒn.ə.θiː.ɪz.əm/', meaning: 'Thuyết nhất thần, thờ một thần', example: 'Christianity, Islam and Judaism are all examples of monotheism.' },
      { word: 'ritual', phonetic: '/ˈrɪtʃ.u.əl/', meaning: 'Nghi lễ, nghi thức tôn giáo', example: 'The ritual of prayer is performed five times a day in Islamic tradition.' },
      { word: 'clergy', phonetic: '/ˈklɜː.dʒi/', meaning: 'Giới tăng lữ, chức sắc tôn giáo', example: 'The clergy played a central role in education during the medieval period.' },
      { word: 'atheism', phonetic: '/ˈeɪ.θi.ɪz.əm/', meaning: 'Chủ nghĩa vô thần', example: 'Atheism has become more widespread in many Western countries.' },
      { word: 'orthodox', phonetic: '/ˈɔː.θə.dɒks/', meaning: 'Chính thống, tuân theo giáo lý truyền thống', example: 'Orthodox communities often resist changes to traditional religious practices.' },
      { word: 'heresy', phonetic: '/ˈher.ɪ.si/', meaning: 'Dị giáo, tà thuyết', example: 'In the Middle Ages, heresy was punishable by death in parts of Europe.' },
      { word: 'agnostic', phonetic: '/æɡˈnɒs.tɪk/', meaning: 'Người theo thuyết bất khả tri', example: 'She describes herself as agnostic rather than either religious or atheist.' },
      { word: 'fundamentalism', phonetic: '/ˌfʌn.dəˈmen.tə.lɪz.əm/', meaning: 'Chủ nghĩa cực đoan tôn giáo', example: 'Religious fundamentalism can lead to intolerance towards other belief systems.' },
      { word: 'syncretic', phonetic: '/sɪŋˈkret.ɪk/', meaning: 'Hỗn hợp tín ngưỡng, pha trộn nhiều tôn giáo', example: 'Vietnamese folk religion is largely syncretic, blending Buddhism, Taoism and local beliefs.' },
      { word: 'scripture', phonetic: '/ˈskrɪp.tʃər/', meaning: 'Kinh sách tôn giáo', example: 'Scholars continue to debate the interpretation of ancient religious scriptures.' },
      { word: 'proselytise', phonetic: '/ˈprɒs.ɪ.lɪ.taɪz/', meaning: 'Truyền đạo, cố gắng cải đạo người khác', example: 'Some governments restrict the right to proselytise in public spaces.' },
      { word: 'sacred', phonetic: '/ˈseɪ.krɪd/', meaning: 'Thiêng liêng, linh thiêng', example: 'The river is considered sacred by millions of Hindus across India.' },
      { word: 'convert', phonetic: '/kənˈvɜːt/', meaning: 'Cải đạo sang tôn giáo hoặc niềm tin khác', example: 'He converted to Islam after years of spiritual searching.' },
      { word: 'extremist', phonetic: '/ɪkˈstriː.mɪst/', meaning: 'Người có quan điểm cực đoan mà hầu hết không đồng ý', example: 'Religious extremists reject dialogue with those of different beliefs.' },
      { word: 'fanatic', phonetic: '/fəˈnæt.ɪk/', meaning: 'Người có sự nhiệt tình cực đoan về tôn giáo', example: 'A religious fanatic bombed the embassy in the name of his beliefs.' },
      { word: 'intolerance', phonetic: '/ɪnˈtɒl.ər.ənts/', meaning: 'Không chấp nhận quan điểm hoặc niềm tin khác', example: 'Religious intolerance has caused some of history\'s worst conflicts.' },
      { word: 'intolerant', phonetic: '/ɪnˈtɒl.ər.ənt/', meaning: 'Từ chối chấp nhận ý kiến hoặc phong tục khác', example: 'Some fundamentalist groups are deeply intolerant of other faiths.' },
      { word: 'materialism', phonetic: '/məˈtɪə.ri.əl.ɪ.zəm/', meaning: 'Niềm tin rằng tiền bạc và vật chất là quan trọng nhất', example: 'Many spiritual traditions explicitly reject materialism and greed.' },
      { word: 'reconcile', phonetic: '/ˈrek.ən.saɪl/', meaning: 'Làm cho hai quan điểm hoặc niềm tin mâu thuẫn hòa hợp', example: 'It is sometimes difficult to reconcile scientific evidence with religious faith.' },
      { word: 'worship', phonetic: '/ˈwɜː.ʃɪp/', meaning: 'Thờ phụng Thượng đế thông qua cầu nguyện hoặc hát thánh ca', example: 'Daily acts of worship are central to life in the monastery.' },
      { word: 'chapel', phonetic: '/ˈtʃæp.əl/', meaning: 'Nhà thờ nhỏ hoặc phòng dùng như nhà thờ', example: 'There is a small chapel in the grounds of the historic manor house.' },
      { word: 'revelation', phonetic: '/ˌrev.əlˈeɪ.ʃən/', meaning: 'Thông tin được tiết lộ bất ngờ; trong tôn giáo: điều Chúa mặc khải', example: 'The book of Revelation describes the end of the world.' },
    ]
  },
  {
    id: 'c2_geoscience', name: 'Physical Geography & Earth Science', nameVi: 'Địa lý tự nhiên & Khoa học Trái đất',
    icon: '🌐', color: '#29B6F6',
    words: [
      { word: 'precipitation', phonetic: '/prɪˌsɪp.ɪˈteɪ.ʃən/', meaning: 'Lượng mưa, giáng thủy', example: 'Annual precipitation in the rainforest exceeds 2,000 millimetres.' },
      { word: 'topography', phonetic: '/təˈpɒɡ.rə.fi/', meaning: 'Địa hình, cấu trúc bề mặt trái đất', example: 'The region\'s topography includes mountains, valleys and coastal plains.' },
      { word: 'tectonic', phonetic: '/tekˈtɒn.ɪk/', meaning: 'Liên quan đến kiến tạo địa tầng', example: 'Earthquakes in the region are caused by the movement of tectonic plates.' },
      { word: 'permafrost', phonetic: '/ˈpɜː.mə.frɒst/', meaning: 'Lớp đất đóng băng vĩnh cửu', example: 'The melting of permafrost in Siberia releases large quantities of methane.' },
      { word: 'watershed', phonetic: '/ˈwɔː.tər.ʃed/', meaning: 'Lưu vực sông, đường phân thủy', example: 'The river divides the watershed between two different drainage basins.' },
      { word: 'fault line', phonetic: '/ˈfɔːlt laɪn/', meaning: 'Đứt gãy địa chất', example: 'The city is built along a major fault line, making it vulnerable to earthquakes.' },
      { word: 'glacier', phonetic: '/ˈɡlæs.i.ər/', meaning: 'Sông băng', example: 'Climate change is causing glaciers to retreat at an alarming rate.' },
      { word: 'arid', phonetic: '/ˈær.ɪd/', meaning: 'Khô hạn, cằn cỗi', example: 'Very little vegetation grows in the arid regions of the Sahara Desert.' },
      { word: 'monsoon', phonetic: '/ˌmɒnˈsuːn/', meaning: 'Mùa mưa, gió mùa', example: 'The monsoon season brings heavy rainfall across South and Southeast Asia.' },
      { word: 'delta', phonetic: '/ˈdel.tə/', meaning: 'Đồng bằng châu thổ', example: 'The Mekong Delta is one of the most productive agricultural regions in Asia.' },
      { word: 'savanna', phonetic: '/səˈvæn.ə/', meaning: 'Thảo nguyên nhiệt đới', example: 'The African savanna supports some of the world\'s most iconic wildlife.' },
      { word: 'erosion', phonetic: '/ɪˈrəʊ.ʒən/', meaning: 'Sự xói mòn', example: 'Coastal erosion is threatening several villages along the cliff edge.' },
      { word: 'temperate', phonetic: '/ˈtem.pər.ɪt/', meaning: 'Ôn đới, khí hậu ôn hòa', example: 'The UK has a temperate climate with mild winters and cool summers.' },
      { word: 'prevailing wind', phonetic: '/prɪˈveɪ.lɪŋ wɪnd/', meaning: 'Gió thịnh hành, hướng gió chủ đạo', example: 'The prevailing westerly winds bring moisture-laden air from the Atlantic.' },
      { word: 'geomorphology', phonetic: '/ˌdʒiː.əʊ.mɔːˈfɒl.ə.dʒi/', meaning: 'Địa mạo học, khoa học nghiên cứu địa hình', example: 'Geomorphology examines how rivers, wind and ice shape the Earth\'s surface over time.' },
      { word: 'erupt', phonetic: '/ɪˈrʌpt/', meaning: 'Phun trào (núi lửa)', example: 'The volcano erupted without warning, sending ash clouds across the region.' },
      { word: 'unsustainable', phonetic: '/ˌʌn.səˈsteɪ.nə.bl̩/', meaning: 'Gây hại môi trường do dùng nhiều hơn mức có thể tái tạo', example: 'Unsustainable fishing methods are depleting ocean stocks worldwide.' },
      { word: 'erode', phonetic: '/ɪˈrəʊd/', meaning: 'Đất, đá bị bào mòn dần bởi biển hoặc mưa gió', example: 'The coastline is slowly being eroded by the action of the sea.' },
    ]
  },
  {
    id: 'c2_other', name: 'General Academic Vocabulary', nameVi: 'Từ vựng học thuật tổng hợp',
    icon: '📖', color: '#64748B',
    words: [
      { word: 'accountable', phonetic: '/əˈkaʊn.tə.bl̩/', meaning: 'Có trách nhiệm giải trình về hành động của mình', example: 'Hospitals must be held accountable for their mistakes.' },
      { word: 'adolescent', phonetic: '/ˌæd.əlˈe.sənt/', meaning: 'Người trẻ trong giai đoạn từ trẻ em đến người lớn', example: 'Adolescents are particularly susceptible to peer pressure.' },
      { word: 'albeit', phonetic: '/ɔːlˈbiː.ɪt/', meaning: 'Mặc dù, dù rằng', example: 'He made some progress, albeit slowly and with great difficulty.' },
      { word: 'allocation', phonetic: '/ˌæl.əˈkeɪ.ʃən/', meaning: 'Lượng tiền, thời gian hoặc tài nguyên được phân bổ', example: 'There was controversy over the allocation of research funding.' },
      { word: 'amend', phonetic: '/əˈmend/', meaning: 'Sửa đổi nhỏ nội dung của tài liệu', example: 'Parliament voted to amend the bill before passing it into law.' },
      { word: 'anonymous', phonetic: '/əˈnɒn.ɪ.məs/', meaning: 'Không nêu tên, giấu danh tính', example: 'An anonymous donor gave one million pounds to the charity.' },
      { word: 'appalling', phonetic: '/əˈpɔː.lɪŋ/', meaning: 'Gây sốc và rất tệ', example: 'The report revealed appalling conditions in some care homes.' },
      { word: 'aspire', phonetic: '/əˈspaɪər/', meaning: 'Mong muốn đạt được điều gì đó cao hơn', example: 'Many young people aspire to careers in science and technology.' },
      { word: 'finite', phonetic: '/ˈfaɪ.naɪt/', meaning: 'Có giới hạn, có điểm kết thúc', example: 'The earth\'s natural resources are finite and must be carefully managed.' },
      { word: 'plausible', phonetic: '/ˈplɔː.zə.bl̩/', meaning: 'Có thể đúng hoặc có lý', example: 'The defendant offered a plausible explanation for his whereabouts.' },
      { word: 'assault', phonetic: '/əˈsɔːlt/', meaning: 'Cuộc tấn công bạo lực vào một người', example: 'He was charged with assault after the altercation outside the bar.' },
      { word: 'anticipation', phonetic: '/ænˌtɪ.sɪˈpeɪ.ʃən/', meaning: 'Sự mong đợi, hồi hộp chờ điều gì sắp xảy ra', example: 'There was great anticipation ahead of the landmark court ruling.' },
      { word: 'accumulation', phonetic: '/əˌkjuː.mjəˈleɪ.ʃən/', meaning: 'Lượng tích lũy thu thập được theo thời gian', example: 'The accumulation of evidence against him was overwhelming.' },
      { word: 'deprivation', phonetic: '/ˌdep.rɪˈveɪ.ʃən/', meaning: 'Tình trạng thiếu thốn những thứ cần thiết', example: 'Childhood deprivation has long-lasting effects on life outcomes.' },
      { word: 'desperation', phonetic: '/ˌdes.pəˈreɪ.ʃən/', meaning: 'Trạng thái tuyệt vọng vì không có lựa chọn', example: 'In desperation, she turned to an online forum for advice.' },
    ]
  },

];
