// ═══════════════════════════════════════════════════════════
//  VocabMaster — B2 Vocabulary Database
// ═══════════════════════════════════════════════════════════
const TOPICS = [
  {
    id: 'travel', name: 'Travel & Tourism', nameVi: 'Du lịch', icon: '✈️', color: '#4FC3F7',
    words: [
      { word: 'itinerary', phonetic: '/aɪˈtɪn.ər.ər.i/', meaning: 'Lịch trình', example: 'We planned a detailed itinerary for our trip.' },
      { word: 'accommodation', phonetic: '/əˌkɒm.əˈdeɪ.ʃən/', meaning: 'Chỗ ở', example: 'The accommodation was comfortable and affordable.' },
      { word: 'excursion', phonetic: '/ɪkˈskɜː.ʒən/', meaning: 'Chuyến tham quan', example: 'We went on an excursion to the ancient temple.' },
      { word: 'destination', phonetic: '/ˌdes.tɪˈneɪ.ʃən/', meaning: 'Điểm đến', example: 'Paris is a popular tourist destination.' },
      { word: 'departure', phonetic: '/dɪˈpɑː.tʃər/', meaning: 'Sự khởi hành', example: 'The departure was delayed by two hours.' },
      { word: 'customs', phonetic: '/ˈkʌs.təmz/', meaning: 'Hải quan', example: 'We had to declare goods at customs.' },
      { word: 'currency', phonetic: '/ˈkʌr.ən.si/', meaning: 'Tiền tệ', example: 'You should exchange currency before traveling.' },
      { word: 'reservation', phonetic: '/ˌrez.əˈveɪ.ʃən/', meaning: 'Đặt chỗ', example: 'I made a reservation at the hotel.' },
      { word: 'layover', phonetic: '/ˈleɪ.oʊ.vər/', meaning: 'Quá cảnh', example: 'We had a long layover in Singapore.' },
      { word: 'scenic', phonetic: '/ˈsiː.nɪk/', meaning: 'Có cảnh đẹp', example: 'We took the scenic route along the coast.' },
      { word: 'embark', phonetic: '/ɪmˈbɑːrk/', meaning: 'Bắt đầu hành trình', example: 'They embarked on a journey across Europe.' },
      { word: 'wander', phonetic: '/ˈwɒn.dər/', meaning: 'Lang thang', example: 'We wandered through the old streets of Hanoi.' },
      { word: 'visa', phonetic: '/ˈviː.zə/', meaning: 'Thị thực, visa', example: 'You need a valid visa to enter the country.' },
      { word: 'fare', phonetic: '/feər/', meaning: 'Giá vé (phương tiện)', example: 'The taxi fare to the airport was quite expensive.' },
      { word: 'overseas', phonetic: '/ˌoʊ.vərˈsiːz/', meaning: 'Ở nước ngoài, hải ngoại', example: 'She studied overseas for two years before returning home.' },
      { word: 'backpack', phonetic: '/ˈbæk.pæk/', meaning: 'Ba lô; đi du lịch bụi', example: 'She traveled across Southeast Asia with just a backpack.' },
      { word: 'souvenir', phonetic: '/ˌsuː.vəˈnɪər/', meaning: 'Quà lưu niệm', example: 'He bought a souvenir from every country he visited.' },
      { word: 'passport', phonetic: '/ˈpɑːs.pɔːt/', meaning: 'Hộ chiếu', example: 'Make sure your passport is valid before booking international travel.' },
      { word: 'sightseeing', phonetic: '/ˈsaɪtˌsiː.ɪŋ/', meaning: 'Tham quan danh lam thắng cảnh', example: 'We spent the first day sightseeing around the old city.' },
      { word: 'hostel', phonetic: '/ˈhɒs.təl/', meaning: 'Nhà trọ giá rẻ cho khách du lịch', example: 'Staying in a hostel is a great way to meet fellow travelers.' },
    ]
  },
  {
    id: 'work', name: 'Work & Career', nameVi: 'Công việc', icon: '💼', color: '#FFB74D',
    words: [
      { word: 'deadline', phonetic: '/ˈded.laɪn/', meaning: 'Hạn chót', example: 'We must finish the project before the deadline.' },
      { word: 'collaborate', phonetic: '/kəˈlæb.ə.reɪt/', meaning: 'Hợp tác', example: 'The two teams collaborated on the project.' },
      { word: 'negotiate', phonetic: '/nɪˈɡoʊ.ʃi.eɪt/', meaning: 'Đàm phán', example: 'She negotiated a higher salary.' },
      { word: 'promotion', phonetic: '/prəˈmoʊ.ʃən/', meaning: 'Thăng chức', example: 'He received a promotion after two years.' },
      { word: 'resign', phonetic: '/rɪˈzaɪn/', meaning: 'Từ chức', example: 'She resigned from her position last month.' },
      { word: 'expertise', phonetic: '/ˌek.spɜːˈtiːz/', meaning: 'Chuyên môn', example: 'Her expertise in marketing is well known.' },
      { word: 'delegate', phonetic: '/ˈdel.ɪ.ɡeɪt/', meaning: 'Ủy quyền', example: 'A good manager knows how to delegate tasks.' },
      { word: 'initiative', phonetic: '/ɪˈnɪʃ.ə.tɪv/', meaning: 'Sáng kiến', example: 'She took the initiative to solve the problem.' },
      { word: 'productivity', phonetic: '/ˌprɒd.ʌkˈtɪv.ə.ti/', meaning: 'Năng suất', example: 'Remote work increased our productivity.' },
      { word: 'entrepreneur', phonetic: '/ˌɒn.trə.prəˈnɜːr/', meaning: 'Doanh nhân', example: 'The young entrepreneur started three companies.' },
      { word: 'benchmark', phonetic: '/ˈbentʃ.mɑːrk/', meaning: 'Tiêu chuẩn', example: 'This report sets a new benchmark for quality.' },
      { word: 'stakeholder', phonetic: '/ˈsteɪkˌhoʊl.dər/', meaning: 'Bên liên quan', example: 'All stakeholders approved the new plan.' },
      { word: 'applicant', phonetic: '/ˈæp.lɪ.kənt/', meaning: 'Người nộp đơn, ứng viên', example: 'Over two hundred applicants applied for the position.' },
      { word: 'workforce', phonetic: '/ˈwɜːk.fɔːs/', meaning: 'Lực lượng lao động', example: 'The company plans to expand its workforce next year.' },
      { word: 'workplace', phonetic: '/ˈwɜːk.pleɪs/', meaning: 'Nơi làm việc', example: 'A positive workplace culture improves employee satisfaction.' },
      { word: 'interview', phonetic: '/ˈɪn.tə.vjuː/', meaning: 'Phỏng vấn', example: 'She prepared thoroughly for the job interview.' },
      { word: 'supervisor', phonetic: '/ˈsuː.pə.vaɪ.zər/', meaning: 'Người giám sát, quản lý trực tiếp', example: 'My supervisor gave me useful feedback on my work.' },
      { word: 'contract', phonetic: '/ˈkɒn.trækt/', meaning: 'Hợp đồng', example: 'Always read the contract carefully before signing it.' },
      { word: 'redundant', phonetic: '/rɪˈdʌn.dənt/', meaning: 'Bị sa thải do dôi dư', example: 'Over fifty workers were made redundant when the factory closed.' },
      { word: 'freelance', phonetic: '/ˈfriː.lɑːns/', meaning: 'Làm việc tự do, freelance', example: 'She works freelance as a graphic designer from home.' },
    ]
  },
  {
    id: 'food', name: 'Food & Cuisine', nameVi: 'Ẩm thực', icon: '🍽️', color: '#EF5350',
    words: [
      { word: 'cuisine', phonetic: '/kwɪˈziːn/', meaning: 'Ẩm thực', example: 'Vietnamese cuisine is famous worldwide.' },
      { word: 'appetizer', phonetic: '/ˈæp.ə.taɪ.zər/', meaning: 'Món khai vị', example: 'We ordered spring rolls as an appetizer.' },
      { word: 'seasoning', phonetic: '/ˈsiː.zən.ɪŋ/', meaning: 'Gia vị', example: 'The seasoning gave the dish a rich flavor.' },
      { word: 'nutrition', phonetic: '/njuːˈtrɪʃ.ən/', meaning: 'Dinh dưỡng', example: 'Good nutrition is essential for health.' },
      { word: 'ingredient', phonetic: '/ɪnˈɡriː.di.ənt/', meaning: 'Nguyên liệu', example: 'Fresh ingredients make the best meals.' },
      { word: 'gourmet', phonetic: '/ɡʊrˈmeɪ/', meaning: 'Sành ăn', example: 'The gourmet restaurant serves exquisite dishes.' },
      { word: 'delicacy', phonetic: '/ˈdel.ɪ.kə.si/', meaning: 'Đặc sản', example: 'Pho is considered a Vietnamese delicacy.' },
      { word: 'beverage', phonetic: '/ˈbev.ər.ɪdʒ/', meaning: 'Đồ uống', example: 'Would you like a hot or cold beverage?' },
      { word: 'garnish', phonetic: '/ˈɡɑːr.nɪʃ/', meaning: 'Trang trí món ăn', example: 'The chef garnished the plate with herbs.' },
      { word: 'savory', phonetic: '/ˈseɪ.vər.i/', meaning: 'Đậm đà, mặn', example: 'I prefer savory snacks over sweet ones.' },
      { word: 'simmer', phonetic: '/ˈsɪm.ər/', meaning: 'Hầm nhỏ lửa', example: 'Let the soup simmer for thirty minutes.' },
      { word: 'organic', phonetic: '/ɔːrˈɡæn.ɪk/', meaning: 'Hữu cơ', example: 'We buy organic vegetables from the market.' },
      { word: 'flavour', phonetic: '/ˈfleɪ.vər/', meaning: 'Hương vị, mùi vị', example: 'The dish has a rich and complex flavour.' },
      { word: 'portion', phonetic: '/ˈpɔː.ʃən/', meaning: 'Phần ăn, khẩu phần', example: 'The portion sizes at this restaurant are very generous.' },
      { word: 'herb', phonetic: '/hɜːb/', meaning: 'Rau thơm, thảo mộc', example: 'Fresh herbs add flavour to any dish.' },
      { word: 'recipe', phonetic: '/ˈres.ɪ.pi/', meaning: 'Công thức nấu ăn', example: 'She followed an online recipe to bake the perfect cake.' },
      { word: 'spicy', phonetic: '/ˈspaɪ.si/', meaning: 'Cay, có nhiều gia vị', example: 'He loves spicy food, the hotter the better.' },
      { word: 'tender', phonetic: '/ˈten.dər/', meaning: 'Mềm (thịt), dễ cắn', example: 'The slow-cooked lamb was incredibly tender.' },
      { word: 'roast', phonetic: '/rəʊst/', meaning: 'Nướng (lò); món nướng', example: 'They had a traditional roast dinner every Sunday.' },
      { word: 'marinate', phonetic: '/ˈmær.ɪ.neɪt/', meaning: 'Ướp (thịt, cá)', example: 'Marinate the chicken overnight for the best flavour.' },
    ]
  },
  {
    id: 'tech', name: 'Technology', nameVi: 'Công nghệ', icon: '💻', color: '#66BB6A',
    words: [
      { word: 'algorithm', phonetic: '/ˈæl.ɡə.rɪ.ðəm/', meaning: 'Thuật toán', example: 'The algorithm processes data efficiently.' },
      { word: 'bandwidth', phonetic: '/ˈbænd.wɪdθ/', meaning: 'Băng thông', example: 'Video streaming requires high bandwidth.' },
      { word: 'cybersecurity', phonetic: '/ˌsaɪ.bər.sɪˈkjʊr.ə.ti/', meaning: 'An ninh mạng', example: 'Cybersecurity is crucial for online businesses.' },
      { word: 'encryption', phonetic: '/ɪnˈkrɪp.ʃən/', meaning: 'Mã hóa', example: 'Encryption protects sensitive information.' },
      { word: 'interface', phonetic: '/ˈɪn.tər.feɪs/', meaning: 'Giao diện', example: 'The user interface is clean and intuitive.' },
      { word: 'prototype', phonetic: '/ˈproʊ.t̬ə.taɪp/', meaning: 'Nguyên mẫu', example: 'We built a prototype to test the concept.' },
      { word: 'compatible', phonetic: '/kəmˈpæt.ə.bəl/', meaning: 'Tương thích', example: 'The app is compatible with all devices.' },
      { word: 'innovate', phonetic: '/ˈɪn.ə.veɪt/', meaning: 'Đổi mới', example: 'Companies must innovate to stay competitive.' },
      { word: 'automate', phonetic: '/ˈɔː.t̬ə.meɪt/', meaning: 'Tự động hóa', example: 'We automated the testing process.' },
      { word: 'debug', phonetic: '/ˌdiːˈbʌɡ/', meaning: 'Gỡ lỗi', example: 'It took hours to debug the code.' },
      { word: 'deploy', phonetic: '/dɪˈplɔɪ/', meaning: 'Triển khai', example: 'We will deploy the update next week.' },
      { word: 'scalable', phonetic: '/ˈskeɪ.lə.bəl/', meaning: 'Có thể mở rộng', example: 'The system is designed to be scalable.' },
      { word: 'database', phonetic: '/ˈdeɪ.tə.beɪs/', meaning: 'Cơ sở dữ liệu', example: 'The database stores millions of customer records.' },
      { word: 'innovation', phonetic: '/ˌɪn.əˈveɪ.ʃən/', meaning: 'Đổi mới sáng tạo', example: 'Technological innovation is driving economic growth.' },
      { word: 'interaction', phonetic: '/ˌɪn.tərˈæk.ʃən/', meaning: 'Sự tương tác', example: 'The app was designed for seamless user interaction.' },
      { word: 'software', phonetic: '/ˈsɒft.weər/', meaning: 'Phần mềm', example: 'The software was updated to fix several security vulnerabilities.' },
      { word: 'hardware', phonetic: '/ˈhɑːd.weər/', meaning: 'Phần cứng máy tính', example: 'The hardware upgrade significantly improved the computer\'s performance.' },
      { word: 'wireless', phonetic: '/ˈwaɪər.ləs/', meaning: 'Không dây', example: 'The office has fast wireless internet throughout the building.' },
      { word: 'digital', phonetic: '/ˈdɪdʒ.ɪ.təl/', meaning: 'Kỹ thuật số, số hóa', example: 'The company is undergoing a full digital transformation.' },
      { word: 'server', phonetic: '/ˈsɜː.vər/', meaning: 'Máy chủ', example: 'The server crashed, taking the entire website offline.' },
    ]
  },
  {
    id: 'health', name: 'Health & Wellness', nameVi: 'Sức khỏe', icon: '🏥', color: '#AB47BC',
    words: [
      { word: 'symptom', phonetic: '/ˈsɪmp.təm/', meaning: 'Triệu chứng', example: 'Fever is a common symptom of the flu.' },
      { word: 'diagnosis', phonetic: '/ˌdaɪ.əɡˈnoʊ.sɪs/', meaning: 'Chẩn đoán', example: 'The doctor made an accurate diagnosis.' },
      { word: 'prescription', phonetic: '/prɪˈskrɪp.ʃən/', meaning: 'Đơn thuốc', example: 'You need a prescription for this medicine.' },
      { word: 'immunity', phonetic: '/ɪˈmjuː.nə.ti/', meaning: 'Miễn dịch', example: 'Exercise helps boost your immunity.' },
      { word: 'chronic', phonetic: '/ˈkrɒn.ɪk/', meaning: 'Mãn tính', example: 'He suffers from chronic back pain.' },
      { word: 'therapy', phonetic: '/ˈθer.ə.pi/', meaning: 'Liệu pháp', example: 'Physical therapy helped her recover.' },
      { word: 'metabolism', phonetic: '/məˈtæb.əl.ɪ.zəm/', meaning: 'Trao đổi chất', example: 'A fast metabolism helps burn calories.' },
      { word: 'contagious', phonetic: '/kənˈteɪ.dʒəs/', meaning: 'Lây nhiễm', example: 'The disease is highly contagious.' },
      { word: 'vaccination', phonetic: '/ˌvæk.sɪˈneɪ.ʃən/', meaning: 'Tiêm chủng', example: 'Vaccination prevents many diseases.' },
      { word: 'insomnia', phonetic: '/ɪnˈsɒm.ni.ə/', meaning: 'Mất ngủ', example: 'Stress can cause insomnia.' },
      { word: 'allergy', phonetic: '/ˈæl.ər.dʒi/', meaning: 'Dị ứng', example: 'She has a severe allergy to peanuts.' },
      { word: 'holistic', phonetic: '/hoʊˈlɪs.tɪk/', meaning: 'Toàn diện', example: 'She takes a holistic approach to wellness.' },
      { word: 'medication', phonetic: '/ˌmed.ɪˈkeɪ.ʃən/', meaning: 'Thuốc, liệu trình dùng thuốc', example: 'The doctor prescribed new medication for his condition.' },
      { word: 'recovery', phonetic: '/rɪˈkʌv.ər.i/', meaning: 'Sự hồi phục', example: 'His recovery from surgery was faster than expected.' },
      { word: 'obesity', phonetic: '/əʊˈbiː.sɪ.ti/', meaning: 'Bệnh béo phì', example: 'Obesity is a growing health concern worldwide.' },
      { word: 'surgery', phonetic: '/ˈsɜː.dʒər.i/', meaning: 'Phẫu thuật', example: 'He underwent emergency surgery after the accident.' },
      { word: 'dosage', phonetic: '/ˈdoʊ.sɪdʒ/', meaning: 'Liều lượng thuốc', example: 'Always follow the recommended dosage on the medicine label.' },
      { word: 'disorder', phonetic: '/dɪˈsɔː.dər/', meaning: 'Rối loạn (sức khỏe)', example: 'Anxiety disorder affects millions of people worldwide.' },
      { word: 'physician', phonetic: '/fɪˈzɪʃ.ən/', meaning: 'Bác sĩ', example: 'You should consult a physician before starting any new medication.' },
      { word: 'supplement', phonetic: '/ˈsʌp.lɪ.mənt/', meaning: 'Thực phẩm bổ sung, vitamin', example: 'Many athletes take protein supplements to support muscle recovery.' },
    ]
  },
  {
    id: 'environment', name: 'Environment', nameVi: 'Môi trường', icon: '🌍', color: '#26A69A',
    words: [
      { word: 'sustainability', phonetic: '/səˌsteɪ.nəˈbɪl.ə.ti/', meaning: 'Bền vững', example: 'Sustainability is key to our future.' },
      { word: 'biodiversity', phonetic: '/ˌbaɪ.oʊ.daɪˈvɜː.sə.ti/', meaning: 'Đa dạng sinh học', example: 'Rainforests have incredible biodiversity.' },
      { word: 'emission', phonetic: '/ɪˈmɪʃ.ən/', meaning: 'Khí thải', example: 'We must reduce carbon emissions.' },
      { word: 'renewable', phonetic: '/rɪˈnjuː.ə.bəl/', meaning: 'Tái tạo', example: 'Solar power is a renewable energy source.' },
      { word: 'conservation', phonetic: '/ˌkɒn.sərˈveɪ.ʃən/', meaning: 'Bảo tồn', example: 'Wildlife conservation is important.' },
      { word: 'ecosystem', phonetic: '/ˈiː.koʊˌsɪs.təm/', meaning: 'Hệ sinh thái', example: 'Coral reefs are fragile ecosystems.' },
      { word: 'deforestation', phonetic: '/diːˌfɒr.ɪˈsteɪ.ʃən/', meaning: 'Phá rừng', example: 'Deforestation threatens many species.' },
      { word: 'pollution', phonetic: '/pəˈluː.ʃən/', meaning: 'Ô nhiễm', example: 'Air pollution is a serious problem in cities.' },
      { word: 'endangered', phonetic: '/ɪnˈdeɪn.dʒərd/', meaning: 'Có nguy cơ tuyệt chủng', example: 'The panda is an endangered species.' },
      { word: 'habitat', phonetic: '/ˈhæb.ɪ.tæt/', meaning: 'Môi trường sống', example: 'Deforestation destroys natural habitats.' },
      { word: 'erosion', phonetic: '/ɪˈroʊ.ʒən/', meaning: 'Xói mòn', example: 'Soil erosion is caused by heavy rainfall.' },
      { word: 'drought', phonetic: '/draʊt/', meaning: 'Hạn hán', example: 'The drought lasted for three months.' },
      { word: 'carbon', phonetic: '/ˈkɑː.bən/', meaning: 'Carbon, nguyên tố cacbon', example: 'Reducing carbon emissions is essential to fight climate change.' },
      { word: 'sustainable', phonetic: '/səˈsteɪ.nə.bəl/', meaning: 'Bền vững', example: 'We need sustainable solutions to protect the planet.' },
      { word: 'fossil', phonetic: '/ˈfɒs.əl/', meaning: 'Hóa thạch; (nhiên liệu) hóa thạch', example: 'Fossil fuels are a major cause of air pollution and climate change.' },
      { word: 'climate', phonetic: '/ˈklaɪ.mɪt/', meaning: 'Khí hậu', example: 'Climate change is one of the greatest challenges of our time.' },
      { word: 'recycle', phonetic: '/ˌriːˈsaɪ.kəl/', meaning: 'Tái chế', example: 'It is important to recycle paper, glass, and plastic waste.' },
      { word: 'toxic', phonetic: '/ˈtɒk.sɪk/', meaning: 'Độc hại', example: 'The factory was fined for releasing toxic chemicals into the river.' },
      { word: 'greenhouse', phonetic: '/ˈɡriːn.haʊs/', meaning: 'Nhà kính; khí gây hiệu ứng nhà kính', example: 'Greenhouse gas emissions must be cut to slow global warming.' },
      { word: 'species', phonetic: '/ˈspiː.ʃiːz/', meaning: 'Loài sinh vật', example: 'Many species are threatened with extinction due to habitat loss.' },
    ]
  },
  {
    id: 'education', name: 'Education & Learning', nameVi: 'Giáo dục', icon: '📚', color: '#F59E0B',
    words: [
      { word: 'curriculum', phonetic: '/kəˈrɪk.jʊ.ləm/', meaning: 'Chương trình học', example: 'The curriculum covers a wide range of subjects from science to the arts.' },
      { word: 'semester', phonetic: '/sɪˈmes.tər/', meaning: 'Học kỳ', example: 'The final exam will be held at the end of the spring semester.' },
      { word: 'scholarship', phonetic: '/ˈskɒl.ə.ʃɪp/', meaning: 'Học bổng', example: 'She won a scholarship to study at a top university abroad.' },
      { word: 'tuition', phonetic: '/tjuːˈɪʃ.ən/', meaning: 'Học phí', example: 'University tuition fees have risen sharply in recent years.' },
      { word: 'graduate', phonetic: '/ˈɡrædʒ.u.ɪt/', meaning: 'Tốt nghiệp đại học', example: 'She graduated with honours from the faculty of law.' },
      { word: 'assignment', phonetic: '/əˈsaɪn.mənt/', meaning: 'Bài tập được giao', example: 'The teacher gave us a research assignment due next week.' },
      { word: 'campus', phonetic: '/ˈkæm.pəs/', meaning: 'Khuôn viên trường đại học', example: 'The university campus has beautiful gardens and modern facilities.' },
      { word: 'lecture', phonetic: '/ˈlek.tʃər/', meaning: 'Bài giảng đại học', example: 'The professor gave a fascinating lecture on ancient history.' },
      { word: 'academic', phonetic: '/ˌæk.əˈdem.ɪk/', meaning: 'Thuộc về học thuật', example: 'Her academic record was impressive enough to earn a top scholarship.' },
      { word: 'certificate', phonetic: '/səˈtɪf.ɪ.kɪt/', meaning: 'Chứng chỉ', example: 'He received a certificate of completion after finishing the course.' },
      { word: 'discipline', phonetic: '/ˈdɪs.ɪ.plɪn/', meaning: 'Lĩnh vực học thuật; kỷ luật', example: 'Linguistics is a fascinating academic discipline.' },
      { word: 'thesis', phonetic: '/ˈθiː.sɪs/', meaning: 'Luận văn, khóa luận', example: 'She spent two years writing her undergraduate thesis.' },
      { word: 'enroll', phonetic: '/ɪnˈroʊl/', meaning: 'Ghi danh, đăng ký học', example: 'You must enroll before the start of the academic year.' },
      { word: 'tutorial', phonetic: '/tjuːˈtɔː.ri.əl/', meaning: 'Buổi học nhóm nhỏ', example: 'Students attend weekly tutorials with their subject tutor.' },
      { word: 'qualify', phonetic: '/ˈkwɒl.ɪ.faɪ/', meaning: 'Đủ điều kiện, đạt tiêu chuẩn', example: 'You need a degree to qualify for this teaching position.' },
      { word: 'examination', phonetic: '/ɪɡˌzæm.ɪˈneɪ.ʃən/', meaning: 'Kỳ thi, bài kiểm tra', example: 'Students must pass a final examination to graduate.' },
      { word: 'revise', phonetic: '/rɪˈvaɪz/', meaning: 'Ôn tập; chỉnh sửa', example: 'She spent the whole weekend revising for the history exam.' },
      { word: 'undergraduate', phonetic: '/ˌʌn.dəˈɡrædʒ.u.ɪt/', meaning: 'Sinh viên đại học (chưa tốt nghiệp)', example: 'The undergraduate program lasts three years at most universities.' },
      { word: 'postgraduate', phonetic: '/ˌpəʊstˈɡrædʒ.u.ɪt/', meaning: 'Sinh viên sau đại học', example: 'She enrolled in a postgraduate course in international relations.' },
      { word: 'faculty', phonetic: '/ˈfæk.əl.ti/', meaning: 'Khoa (trường đại học); giảng viên', example: 'The faculty of engineering has an excellent academic reputation.' },
    ]
  },
  {
    id: 'entertainment', name: 'Entertainment & Media', nameVi: 'Giải trí & Truyền thông', icon: '🎬', color: '#EC4899',
    words: [
      { word: 'broadcast', phonetic: '/ˈbrɔːd.kɑːst/', meaning: 'Phát sóng', example: 'The match was broadcast live on national television.' },
      { word: 'premiere', phonetic: '/prɪˈmɪər/', meaning: 'Buổi ra mắt, công chiếu lần đầu', example: 'The film had its world premiere at the Cannes Film Festival.' },
      { word: 'sequel', phonetic: '/ˈsiː.kwəl/', meaning: 'Phần tiếp theo', example: 'The sequel was even more successful than the original film.' },
      { word: 'celebrity', phonetic: '/səˈleb.rɪ.ti/', meaning: 'Người nổi tiếng', example: 'The celebrity appeared on the cover of several international magazines.' },
      { word: 'audience', phonetic: '/ˈɔː.di.əns/', meaning: 'Khán giả', example: 'The audience gave the performers a standing ovation.' },
      { word: 'episode', phonetic: '/ˈep.ɪ.soʊd/', meaning: 'Tập phim (series)', example: 'I watched three episodes of the drama series in one sitting.' },
      { word: 'documentary', phonetic: '/ˌdɒk.jʊˈmen.tər.i/', meaning: 'Phim tài liệu', example: 'The documentary about ocean pollution won several prestigious awards.' },
      { word: 'subscription', phonetic: '/səbˈskrɪp.ʃən/', meaning: 'Gói đăng ký dịch vụ', example: 'Monthly subscription fees for streaming services keep rising.' },
      { word: 'performance', phonetic: '/pərˈfɔː.məns/', meaning: 'Buổi biểu diễn; màn trình diễn', example: 'The actor\'s performance in the lead role was truly outstanding.' },
      { word: 'director', phonetic: '/dɪˈrek.tər/', meaning: 'Đạo diễn', example: 'The director\'s latest film received critical acclaim worldwide.' },
      { word: 'soundtrack', phonetic: '/ˈsaʊnd.træk/', meaning: 'Nhạc phim', example: 'The film\'s soundtrack became more popular than the film itself.' },
      { word: 'entertain', phonetic: '/ˌen.tərˈteɪn/', meaning: 'Giải trí, mua vui', example: 'The comedian entertained the crowd for over two hours.' },
      { word: 'fictional', phonetic: '/ˈfɪk.ʃən.əl/', meaning: 'Hư cấu', example: 'The story is fictional but loosely based on real historical events.' },
      { word: 'rating', phonetic: '/ˈreɪ.tɪŋ/', meaning: 'Mức độ phổ biến; xếp hạng', example: 'The show achieved record ratings on its premiere night.' },
      { word: 'review', phonetic: '/rɪˈvjuː/', meaning: 'Bài nhận xét, đánh giá', example: 'Critics gave the film mostly positive reviews.' },
      { word: 'stream', phonetic: '/striːm/', meaning: 'Phát/xem trực tuyến', example: 'Millions of people stream music and videos online every day.' },
      { word: 'plot', phonetic: '/plɒt/', meaning: 'Cốt truyện', example: 'The film\'s plot was full of unexpected twists.' },
      { word: 'cast', phonetic: '/kɑːst/', meaning: 'Dàn diễn viên', example: 'The film boasts an impressive cast of award-winning actors.' },
      { word: 'release', phonetic: '/rɪˈliːs/', meaning: 'Phát hành (phim, nhạc)', example: 'The album is scheduled for release next month.' },
      { word: 'animation', phonetic: '/ˌæn.ɪˈmeɪ.ʃən/', meaning: 'Hoạt hình', example: 'The animation studio produced some of the most beloved films of the decade.' },
    ]
  },
  {
    id: 'sports', name: 'Sports & Fitness', nameVi: 'Thể thao', icon: '⚽', color: '#10B981',
    words: [
      { word: 'tournament', phonetic: '/ˈtʊər.nə.mənt/', meaning: 'Giải đấu', example: 'The annual tennis tournament attracts players from around the world.' },
      { word: 'athlete', phonetic: '/ˈæθ.liːt/', meaning: 'Vận động viên', example: 'The athlete trained for six hours every day to prepare for the Olympics.' },
      { word: 'championship', phonetic: '/ˈtʃæm.pi.ən.ʃɪp/', meaning: 'Giải vô địch', example: 'The team won the national championship for the third consecutive time.' },
      { word: 'referee', phonetic: '/ˌref.əˈriː/', meaning: 'Trọng tài', example: 'The referee awarded a penalty kick to the home team.' },
      { word: 'spectator', phonetic: '/spekˈteɪ.tər/', meaning: 'Khán giả tại sân', example: 'Thousands of spectators cheered the athletes on from the stands.' },
      { word: 'endurance', phonetic: '/ɪnˈdjʊər.əns/', meaning: 'Sức bền', example: 'Marathon running requires exceptional physical endurance.' },
      { word: 'workout', phonetic: '/ˈwɜːk.aʊt/', meaning: 'Buổi tập thể dục', example: 'She does a morning workout every day before going to work.' },
      { word: 'tactics', phonetic: '/ˈtæk.tɪks/', meaning: 'Chiến thuật', example: 'The coach adjusted the team\'s tactics at halftime.' },
      { word: 'penalty', phonetic: '/ˈpen.əl.ti/', meaning: 'Phạt đền; hình phạt', example: 'The goalkeeper saved two penalties during the shoot-out.' },
      { word: 'stamina', phonetic: '/ˈstæm.ɪ.nə/', meaning: 'Sức bền, thể lực dẻo dai', example: 'Cyclists need incredible stamina to complete a mountain race.' },
      { word: 'competitive', phonetic: '/kəmˈpet.ɪ.tɪv/', meaning: 'Có tinh thần cạnh tranh', example: 'She has a highly competitive personality in everything she does.' },
      { word: 'trophy', phonetic: '/ˈtrəʊ.fi/', meaning: 'Cúp vô địch', example: 'The team lifted the trophy in front of their delighted supporters.' },
      { word: 'substitute', phonetic: '/ˈsʌb.stɪ.tjuːt/', meaning: 'Cầu thủ dự bị; thay thế', example: 'The coach brought on a substitute in the second half.' },
      { word: 'fitness', phonetic: '/ˈfɪt.nəs/', meaning: 'Sức khỏe, thể lực', example: 'Regular exercise is essential for maintaining good fitness.' },
      { word: 'intense', phonetic: '/ɪnˈtens/', meaning: 'Dữ dội, căng thẳng', example: 'The final match was one of the most intense in recent memory.' },
      { word: 'league', phonetic: '/liːɡ/', meaning: 'Giải bóng đá, liên đoàn', example: 'The team was promoted to the top league after a successful season.' },
      { word: 'coach', phonetic: '/kəʊtʃ/', meaning: 'Huấn luyện viên', example: 'The coach inspired the team with a powerful halftime speech.' },
      { word: 'sprint', phonetic: '/sprɪnt/', meaning: 'Chạy nước rút', example: 'He sprinted the last hundred metres to win the race.' },
      { word: 'defeat', phonetic: '/dɪˈfiːt/', meaning: 'Đánh bại; thất bại', example: 'The team suffered a humiliating defeat in the final.' },
      { word: 'medal', phonetic: '/ˈmed.əl/', meaning: 'Huy chương', example: 'She won a gold medal at the Olympic Games.' },
    ]
  },
  {
    id: 'lifestyle', name: 'Home & Lifestyle', nameVi: 'Cuộc sống gia đình', icon: '🏠', color: '#84CC16',
    words: [
      { word: 'household', phonetic: '/ˈhaʊs.hoʊld/', meaning: 'Hộ gia đình', example: 'Household chores were shared equally between all family members.' },
      { word: 'appliance', phonetic: '/əˈplaɪ.əns/', meaning: 'Thiết bị, đồ dùng gia dụng', example: 'New kitchen appliances can save a great deal of time and energy.' },
      { word: 'maintenance', phonetic: '/ˈmeɪn.tɪ.nəns/', meaning: 'Sự bảo trì, bảo dưỡng', example: 'Regular maintenance prevents costly repairs in the long run.' },
      { word: 'furnish', phonetic: '/ˈfɜː.nɪʃ/', meaning: 'Trang bị nội thất', example: 'The apartment was fully furnished when we moved in.' },
      { word: 'rent', phonetic: '/rent/', meaning: 'Thuê nhà; tiền thuê', example: 'The monthly rent for this apartment is very reasonable.' },
      { word: 'routine', phonetic: '/ruːˈtiːn/', meaning: 'Thói quen hàng ngày', example: 'She has a strict morning routine that keeps her productive.' },
      { word: 'neighborhood', phonetic: '/ˈneɪ.bər.hʊd/', meaning: 'Khu phố, khu dân cư', example: 'We live in a quiet and friendly neighborhood close to the park.' },
      { word: 'mortgage', phonetic: '/ˈmɔːɡ.ɪdʒ/', meaning: 'Thế chấp; khoản vay mua nhà', example: 'Getting a mortgage requires a stable income and a good credit history.' },
      { word: 'lease', phonetic: '/liːs/', meaning: 'Hợp đồng thuê (nhà, xe...)', example: 'The lease on our apartment expires at the end of the year.' },
      { word: 'utility', phonetic: '/juːˈtɪl.ɪ.ti/', meaning: 'Tiện ích công cộng (điện, nước, gas)', example: 'Utility bills have increased significantly this winter.' },
      { word: 'interior', phonetic: '/ɪnˈtɪər.i.ər/', meaning: 'Nội thất; bên trong', example: 'The interior designer transformed the living room completely.' },
      { word: 'spacious', phonetic: '/ˈspeɪ.ʃəs/', meaning: 'Rộng rãi, thoáng đãng', example: 'The new house has a spacious garden and an open-plan kitchen.' },
      { word: 'convenient', phonetic: '/kənˈviː.ni.ənt/', meaning: 'Tiện lợi, thuận tiện', example: 'The apartment is very convenient for public transport.' },
      { word: 'minimize', phonetic: '/ˈmɪn.ɪ.maɪz/', meaning: 'Giảm thiểu, tối thiểu hóa', example: 'We should minimize energy use to reduce our monthly bills.' },
      { word: 'clutter', phonetic: '/ˈklʌt.ər/', meaning: 'Đồ đạc lộn xộn; làm lộn xộn', example: 'She decided to declutter the house and donate unused items to charity.' },
      { word: 'organize', phonetic: '/ˈɔː.ɡə.naɪz/', meaning: 'Sắp xếp, tổ chức', example: 'She organized her wardrobe to make it easier to find things.' },
      { word: 'comfort', phonetic: '/ˈkʌm.fət/', meaning: 'Sự thoải mái, tiện nghi', example: 'After a long trip, there is nothing better than the comfort of home.' },
      { word: 'storage', phonetic: '/ˈstɔː.rɪdʒ/', meaning: 'Không gian lưu trữ, kho chứa', example: 'The apartment lacks adequate storage for all our belongings.' },
      { word: 'decorate', phonetic: '/ˈdek.ə.reɪt/', meaning: 'Trang trí', example: 'They decorated the living room with fresh flowers and plants.' },
      { word: 'relocate', phonetic: '/ˌriː.ləʊˈkeɪt/', meaning: 'Chuyển đến nơi ở mới', example: 'The company offered to help employees relocate to the new city.' },
    ]
  },
  {
    id: 'money', name: 'Money & Finance', nameVi: 'Tiền bạc & Tài chính', icon: '💰', color: '#F97316',
    words: [
      { word: 'budget', phonetic: '/ˈbʌdʒ.ɪt/', meaning: 'Ngân sách', example: 'We need to stick to the budget to avoid overspending this month.' },
      { word: 'investment', phonetic: '/ɪnˈvest.mənt/', meaning: 'Khoản đầu tư', example: 'Real estate remains a popular long-term investment strategy.' },
      { word: 'insurance', phonetic: '/ɪnˈʃɔː.rəns/', meaning: 'Bảo hiểm', example: 'Comprehensive travel insurance is essential before going abroad.' },
      { word: 'savings', phonetic: '/ˈseɪ.vɪŋz/', meaning: 'Tiền tiết kiệm', example: 'She put all her savings into a high-interest bank account.' },
      { word: 'debt', phonetic: '/det/', meaning: 'Khoản nợ', example: 'Many students graduate with significant student loan debt.' },
      { word: 'credit', phonetic: '/ˈkred.ɪt/', meaning: 'Tín dụng', example: 'A good credit score makes it much easier to get a loan.' },
      { word: 'salary', phonetic: '/ˈsæl.ər.i/', meaning: 'Lương tháng', example: 'Her salary increased significantly after she received the promotion.' },
      { word: 'expense', phonetic: '/ɪkˈspens/', meaning: 'Chi phí, khoản chi tiêu', example: 'Business expenses must be recorded and submitted monthly.' },
      { word: 'profit', phonetic: '/ˈprɒf.ɪt/', meaning: 'Lợi nhuận', example: 'The company made a record profit in the final quarter of the year.' },
      { word: 'transaction', phonetic: '/trænˈzæk.ʃən/', meaning: 'Giao dịch tài chính', example: 'All transactions are recorded automatically by the banking system.' },
      { word: 'loan', phonetic: '/loʊn/', meaning: 'Khoản vay', example: 'She took out a small loan to start her own business.' },
      { word: 'purchase', phonetic: '/ˈpɜː.tʃəs/', meaning: 'Mua; khoản mua sắm', example: 'Always keep your receipt as proof of purchase.' },
      { word: 'afford', phonetic: '/əˈfɔːd/', meaning: 'Có đủ khả năng tài chính', example: 'Not everyone can afford to buy a home in the city center.' },
      { word: 'income', phonetic: '/ˈɪŋ.kʌm/', meaning: 'Thu nhập', example: 'His monthly income is just enough to cover basic living expenses.' },
      { word: 'receipt', phonetic: '/rɪˈsiːt/', meaning: 'Biên lai, hóa đơn', example: 'You must show your receipt if you wish to get a refund.' },
      { word: 'withdraw', phonetic: '/wɪðˈdrɔː/', meaning: 'Rút tiền; rút lui', example: 'She withdrew some cash from the ATM before the trip.' },
      { word: 'deposit', phonetic: '/dɪˈpɒz.ɪt/', meaning: 'Gửi tiền; đặt cọc', example: 'You need to pay a deposit when you book the apartment.' },
      { word: 'tax', phonetic: '/tæks/', meaning: 'Thuế', example: 'Income tax is deducted automatically from most employees\' wages.' },
      { word: 'inflation', phonetic: '/ɪnˈfleɪ.ʃən/', meaning: 'Lạm phát', example: 'Rising inflation has reduced consumers\' purchasing power.' },
      { word: 'bankruptcy', phonetic: '/ˈbæŋk.rʌpt.si/', meaning: 'Sự phá sản', example: 'The company filed for bankruptcy after years of financial losses.' },
    ]
  },
  {
    id: 'society', name: 'Society & Community', nameVi: 'Xã hội & Cộng đồng', icon: '🤝', color: '#6366F1',
    words: [
      { word: 'volunteer', phonetic: '/ˌvɒl.ənˈtɪər/', meaning: 'Tình nguyện viên; làm tình nguyện', example: 'She volunteers at the local food bank every weekend.' },
      { word: 'campaign', phonetic: '/kæmˈpeɪn/', meaning: 'Chiến dịch', example: 'The environmental campaign raised awareness about single-use plastics.' },
      { word: 'charity', phonetic: '/ˈtʃær.ɪ.ti/', meaning: 'Tổ chức từ thiện; lòng hảo tâm', example: 'She donates a portion of her income to charity every month.' },
      { word: 'poverty', phonetic: '/ˈpɒv.ər.ti/', meaning: 'Đói nghèo', example: 'Many initiatives aim to reduce poverty in rural communities.' },
      { word: 'welfare', phonetic: '/ˈwel.feər/', meaning: 'Phúc lợi xã hội', example: 'The government increased spending on social welfare programs.' },
      { word: 'crime', phonetic: '/kraɪm/', meaning: 'Tội phạm', example: 'The local authority reported a significant decrease in crime rates.' },
      { word: 'equality', phonetic: '/ɪˈkwɒl.ɪ.ti/', meaning: 'Sự bình đẳng', example: 'Gender equality remains a challenge in many workplaces worldwide.' },
      { word: 'citizenship', phonetic: '/ˈsɪt.ɪ.zən.ʃɪp/', meaning: 'Quyền công dân; tinh thần công dân', example: 'Active citizenship involves participating fully in community life.' },
      { word: 'tradition', phonetic: '/trəˈdɪʃ.ən/', meaning: 'Truyền thống', example: 'This festival has been celebrated as a beloved local tradition for centuries.' },
      { word: 'immigrant', phonetic: '/ˈɪm.ɪ.ɡrənt/', meaning: 'Người nhập cư', example: 'Immigrants often contribute significantly to the culture of their new country.' },
      { word: 'protest', phonetic: '/ˈprəʊ.test/', meaning: 'Cuộc biểu tình; phản đối', example: 'Thousands gathered to protest against the proposed policy changes.' },
      { word: 'community', phonetic: '/kəˈmjuː.nɪ.ti/', meaning: 'Cộng đồng', example: 'The local community rallied together to support the flood victims.' },
      { word: 'belong', phonetic: '/bɪˈlɒŋ/', meaning: 'Thuộc về, là thành viên của', example: 'Everyone has a deep need to feel that they belong somewhere.' },
      { word: 'support', phonetic: '/səˈpɔːt/', meaning: 'Hỗ trợ, ủng hộ', example: 'Community support is crucial during difficult times.' },
      { word: 'awareness', phonetic: '/əˈweər.nəs/', meaning: 'Nhận thức, ý thức', example: 'Public awareness of mental health issues has grown significantly in recent years.' },
      { word: 'diversity', phonetic: '/daɪˈvɜː.sɪ.ti/', meaning: 'Sự đa dạng', example: 'The school celebrates cultural diversity with an annual festival.' },
      { word: 'prejudice', phonetic: '/ˈpredʒ.ʊ.dɪs/', meaning: 'Định kiến, thành kiến', example: 'Prejudice based on race or gender has no place in the workplace.' },
      { word: 'privilege', phonetic: '/ˈprɪv.ɪ.lɪdʒ/', meaning: 'Đặc quyền, ưu đãi', example: 'Not everyone has the privilege of access to quality education.' },
      { word: 'justice', phonetic: '/ˈdʒʌs.tɪs/', meaning: 'Công lý', example: 'The movement called for social justice and equal rights for all.' },
      { word: 'democracy', phonetic: '/dɪˈmɒk.rə.si/', meaning: 'Nền dân chủ', example: 'A healthy democracy requires an informed and engaged citizenry.' },
    ]
  },

  // ── 6 new topics ──────────────────────────────────────────────
  {
    id: 'crime', name: 'Crime & Punishment', nameVi: 'Tội phạm & Hình phạt',
    icon: '🔒', color: '#EF5350',
    words: [
      { word: 'perpetrator', phonetic: '/ˈpɜː.pɪ.treɪ.tər/', meaning: 'Kẻ thực hiện tội phạm', example: 'The perpetrator was caught on CCTV near the scene of the crime.' },
      { word: 'acquittal', phonetic: '/əˈkwɪt.əl/', meaning: 'Sự tha bổng, tuyên vô tội', example: 'The jury returned a verdict of acquittal after deliberating for two days.' },
      { word: 'incarceration', phonetic: '/ɪnˌkɑː.sərˈeɪ.ʃən/', meaning: 'Sự giam cầm, tù giam', example: 'Long-term incarceration can have severe effects on mental health.' },
      { word: 'deterrence', phonetic: '/dɪˈter.əns/', meaning: 'Sự răn đe', example: 'Stricter sentences are often proposed as a form of deterrence.' },
      { word: 'manslaughter', phonetic: '/ˈmæn.slɔː.tər/', meaning: 'Tội ngộ sát', example: 'He was convicted of manslaughter rather than murder as the act was unplanned.' },
      { word: 'embezzlement', phonetic: '/ɪmˈbez.əl.mənt/', meaning: 'Tội tham ô, biển thủ công quỹ', example: 'The accountant faced charges of embezzlement after stealing from company funds.' },
      { word: 'vandalism', phonetic: '/ˈvæn.dəl.ɪz.əm/', meaning: 'Hành vi phá hoại tài sản', example: 'Acts of vandalism in the city centre increased during the school holidays.' },
      { word: 'extortion', phonetic: '/ɪkˈstɔː.ʃən/', meaning: 'Tội tống tiền, cưỡng đoạt', example: 'The businessman was arrested for extortion after demanding payments from local shopkeepers.' },
      { word: 'rehabilitation', phonetic: '/ˌriː.həˌbɪl.ɪˈteɪ.ʃən/', meaning: 'Sự cải tạo, phục hồi nhân phẩm', example: 'The prison programme focuses on rehabilitation rather than punishment alone.' },
      { word: 'probation', phonetic: '/prəˈbeɪ.ʃən/', meaning: 'Án treo, thử thách ngoài xã hội', example: 'The offender was placed on probation for two years instead of being imprisoned.' },
      { word: 'culprit', phonetic: '/ˈkʌl.prɪt/', meaning: 'Người có lỗi, nghi phạm', example: 'Police are still searching for the culprit responsible for the break-in.' },
      { word: 'prosecution', phonetic: '/ˌprɒs.ɪˈkjuː.ʃən/', meaning: 'Sự truy tố, bên công tố', example: 'The prosecution presented compelling evidence during the trial.' },
      { word: 'fraud', phonetic: '/frɔːd/', meaning: 'Gian lận, lừa đảo', example: 'She was found guilty of fraud for falsifying financial documents.' },
      { word: 'custodial', phonetic: '/kʌˈstəʊ.di.əl/', meaning: 'Liên quan đến việc giam giữ', example: 'The judge imposed a custodial sentence of five years.' },
      { word: 'recidivism', phonetic: '/rɪˈsɪd.ɪ.vɪz.əm/', meaning: 'Tái phạm tội', example: 'High rates of recidivism suggest that current rehabilitation programmes are inadequate.' },
    ]
  },
  {
    id: 'family', name: 'Family & Relationships', nameVi: 'Gia đình & Các mối quan hệ',
    icon: '👨‍👩‍👧', color: '#EC407A',
    words: [
      { word: 'upbringing', phonetic: '/ˈʌpˌbrɪŋ.ɪŋ/', meaning: 'Cách nuôi dạy, quá trình lớn lên', example: 'Her upbringing in a rural community shaped her values greatly.' },
      { word: 'sibling', phonetic: '/ˈsɪb.lɪŋ/', meaning: 'Anh chị em ruột', example: 'Having a sibling teaches children important lessons about sharing.' },
      { word: 'estranged', phonetic: '/ɪˈstreɪndʒd/', meaning: 'Xa cách, bất hòa trong gia đình', example: 'He had been estranged from his father for over a decade.' },
      { word: 'nurture', phonetic: '/ˈnɜː.tʃər/', meaning: 'Nuôi dưỡng, vun đắp', example: 'Parents have a responsibility to nurture their children\'s emotional wellbeing.' },
      { word: 'dysfunctional', phonetic: '/dɪsˈfʌŋk.ʃən.əl/', meaning: 'Gia đình không lành mạnh, rối loạn', example: 'Growing up in a dysfunctional family can lead to long-term psychological issues.' },
      { word: 'custody', phonetic: '/ˈkʌs.tə.di/', meaning: 'Quyền nuôi con', example: 'After the divorce, the parents shared joint custody of their children.' },
      { word: 'reconciliation', phonetic: '/ˌrek.ənˌsɪl.iˈeɪ.ʃən/', meaning: 'Sự hòa giải', example: 'After years of conflict, the family achieved reconciliation through counselling.' },
      { word: 'breadwinner', phonetic: '/ˈbred.wɪn.ər/', meaning: 'Trụ cột kinh tế gia đình', example: 'Traditionally, the father was expected to be the breadwinner.' },
      { word: 'foster', phonetic: '/ˈfɒs.tər/', meaning: 'Nuôi dưỡng tạm thời (trẻ em), vun đắp', example: 'The couple decided to foster a child while waiting to adopt.' },
      { word: 'kinship', phonetic: '/ˈkɪn.ʃɪp/', meaning: 'Quan hệ họ hàng, sự gắn bó thân tộc', example: 'A strong sense of kinship holds many traditional communities together.' },
      { word: 'inheritance', phonetic: '/ɪnˈher.ɪ.təns/', meaning: 'Di sản thừa kế', example: 'The family disputed the inheritance after their grandmother passed away.' },
      { word: 'bonding', phonetic: '/ˈbɒn.dɪŋ/', meaning: 'Sự gắn kết', example: 'Shared activities are important for parent-child bonding.' },
      { word: 'filial', phonetic: '/ˈfɪl.i.əl/', meaning: 'Bổn phận con cái', example: 'Filial piety remains a central value in many Asian cultures.' },
      { word: 'cohabit', phonetic: '/ˌkəʊˈhæb.ɪt/', meaning: 'Sống chung không kết hôn', example: 'More couples are choosing to cohabit before getting married.' },
      { word: 'proximity', phonetic: '/prɒkˈsɪm.ɪ.ti/', meaning: 'Sự gần gũi về khoảng cách', example: 'Living in close proximity to extended family provides emotional support.' },
    ]
  },
  {
    id: 'fashion', name: 'Fashion & Clothing', nameVi: 'Thời trang & Trang phục',
    icon: '👗', color: '#AB47BC',
    words: [
      { word: 'bespoke', phonetic: '/bɪˈspəʊk/', meaning: 'May đo riêng theo yêu cầu', example: 'He wore a bespoke suit tailored to his exact measurements.' },
      { word: 'garment', phonetic: '/ˈɡɑː.mənt/', meaning: 'Trang phục, quần áo (trang trọng)', example: 'The garment was made from hand-woven silk imported from Vietnam.' },
      { word: 'silhouette', phonetic: '/ˌsɪl.uˈet/', meaning: 'Đường viền dáng trang phục', example: 'The designer favoured a slim silhouette for his spring collection.' },
      { word: 'textile', phonetic: '/ˈtek.staɪl/', meaning: 'Vải, hàng dệt may', example: 'The country exports textiles to markets across Europe and North America.' },
      { word: 'vintage', phonetic: '/ˈvɪn.tɪdʒ/', meaning: 'Đồ cổ điển có giá trị', example: 'She prefers vintage clothing over new items from high-street stores.' },
      { word: 'accessory', phonetic: '/əkˈses.ər.i/', meaning: 'Phụ kiện thời trang', example: 'The right accessory can completely transform an outfit.' },
      { word: 'trend', phonetic: '/trend/', meaning: 'Xu hướng thời trang', example: 'Sustainability has become a dominant trend in the fashion industry.' },
      { word: 'apparel', phonetic: '/əˈpær.əl/', meaning: 'Quần áo, trang phục (ngành công nghiệp)', example: 'The apparel industry employs millions of workers in developing countries.' },
      { word: 'embroidery', phonetic: '/ɪmˈbrɔɪ.dər.i/', meaning: 'Thêu thùa, hoa văn thêu', example: 'The traditional dress featured intricate embroidery along the hem.' },
      { word: 'fast fashion', phonetic: '/ˌfɑːst ˈfæʃ.ən/', meaning: 'Thời trang nhanh, sản xuất ồ ạt giá rẻ', example: 'Critics argue that fast fashion contributes significantly to environmental pollution.' },
      { word: 'sartorial', phonetic: '/sɑːˈtɔː.ri.əl/', meaning: 'Liên quan đến may mặc, thời trang', example: 'His sartorial choices reflected his confident and creative personality.' },
      { word: 'ethical fashion', phonetic: '/ˈeθ.ɪ.kəl ˈfæʃ.ən/', meaning: 'Thời trang đạo đức, sản xuất có trách nhiệm', example: 'Consumers are increasingly demanding ethical fashion from major brands.' },
      { word: 'atelier', phonetic: '/ˈæt.əl.jeɪ/', meaning: 'Xưởng thiết kế thời trang cao cấp', example: 'The young designer opened her own atelier in Paris after graduating.' },
      { word: 'haute couture', phonetic: '/ˌəʊt kuːˈtjʊər/', meaning: 'Thời trang cao cấp may đo', example: 'Haute couture garments can cost tens of thousands of pounds.' },
      { word: 'avant-garde', phonetic: '/ˌæv.ɒ̃ˈɡɑːd/', meaning: 'Tiên phong, phá cách trong thời trang', example: 'The designer was known for his avant-garde approach to menswear.' },
    ]
  },
  {
    id: 'animals', name: 'Animals & Biology', nameVi: 'Động vật & Sinh học',
    icon: '🦋', color: '#66BB6A',
    words: [
      { word: 'predator', phonetic: '/ˈpred.ə.tər/', meaning: 'Thú săn mồi', example: 'The lion is an apex predator at the top of the food chain.' },
      { word: 'endangered', phonetic: '/ɪnˈdeɪn.dʒəd/', meaning: 'Có nguy cơ tuyệt chủng', example: 'The pangolin is one of the world\'s most endangered animals.' },
      { word: 'biodiversity', phonetic: '/ˌbaɪ.əʊ.daɪˈvɜː.sɪ.ti/', meaning: 'Đa dạng sinh học', example: 'Protecting biodiversity is essential for maintaining healthy ecosystems.' },
      { word: 'migrate', phonetic: '/maɪˈɡreɪt/', meaning: 'Di cư (động vật)', example: 'Swallows migrate thousands of kilometres to Africa each winter.' },
      { word: 'camouflage', phonetic: '/ˈkæm.ə.flɑːʒ/', meaning: 'Ngụy trang', example: 'The stick insect uses camouflage to blend in with tree branches.' },
      { word: 'nocturnal', phonetic: '/nɒkˈtɜː.nəl/', meaning: 'Hoạt động về ban đêm', example: 'Owls are nocturnal hunters with excellent night vision.' },
      { word: 'vertebrate', phonetic: '/ˈvɜː.tɪ.brət/', meaning: 'Động vật có xương sống', example: 'Fish, amphibians, reptiles, birds and mammals are all vertebrates.' },
      { word: 'photosynthesis', phonetic: '/ˌfəʊ.təʊˈsɪn.θɪ.sɪs/', meaning: 'Quang hợp', example: 'Plants convert sunlight into energy through the process of photosynthesis.' },
      { word: 'symbiosis', phonetic: '/ˌsɪm.baɪˈəʊ.sɪs/', meaning: 'Quan hệ cộng sinh', example: 'The relationship between clownfish and sea anemones is a classic example of symbiosis.' },
      { word: 'carnivore', phonetic: '/ˈkɑː.nɪ.vɔːr/', meaning: 'Động vật ăn thịt', example: 'The wolf is a carnivore that hunts in coordinated packs.' },
      { word: 'dormant', phonetic: '/ˈdɔː.mənt/', meaning: 'Ngủ đông, trạng thái nghỉ', example: 'Many bears remain dormant throughout the coldest winter months.' },
      { word: 'ecosystem', phonetic: '/ˈiː.kəʊˌsɪs.təm/', meaning: 'Hệ sinh thái', example: 'Removing one species from an ecosystem can affect the entire food web.' },
      { word: 'domesticated', phonetic: '/dəˈmes.tɪ.keɪ.tɪd/', meaning: 'Đã được thuần hóa', example: 'Dogs were domesticated from wolves thousands of years ago.' },
      { word: 'poaching', phonetic: '/ˈpəʊ.tʃɪŋ/', meaning: 'Săn trộm động vật hoang dã', example: 'Poaching for ivory has dramatically reduced the elephant population.' },
      { word: 'habitat', phonetic: '/ˈhæb.ɪ.tæt/', meaning: 'Môi trường sống tự nhiên', example: 'Deforestation has destroyed the natural habitat of many species.' },
    ]
  },
  {
    id: 'digital_media', name: 'Digital Media & Social Networks', nameVi: 'Mạng xã hội & Truyền thông số',
    icon: '📱', color: '#26C6DA',
    words: [
      { word: 'algorithm', phonetic: '/ˈæl.ɡə.rɪ.ðəm/', meaning: 'Thuật toán điều khiển nội dung hiển thị', example: 'Social media algorithms prioritise content that generates the most engagement.' },
      { word: 'influencer', phonetic: '/ˈɪn.flu.ən.sər/', meaning: 'Người có tầm ảnh hưởng trên mạng xã hội', example: 'Brands now spend more on influencer marketing than on traditional advertising.' },
      { word: 'viral', phonetic: '/ˈvaɪ.rəl/', meaning: 'Lan truyền nhanh trên mạng', example: 'The video went viral within hours, amassing over ten million views.' },
      { word: 'echo chamber', phonetic: '/ˈek.əʊ ˌtʃeɪm.bər/', meaning: 'Buồng vang, môi trường quan điểm đồng nhất', example: 'Social media platforms can create echo chambers that reinforce existing beliefs.' },
      { word: 'cyberbullying', phonetic: '/ˈsaɪ.bəˌbʊl.i.ɪŋ/', meaning: 'Bắt nạt trên mạng', example: 'Cyberbullying has become a serious problem among teenagers who spend time online.' },
      { word: 'misinformation', phonetic: '/ˌmɪs.ɪn.fəˈmeɪ.ʃən/', meaning: 'Thông tin sai lệch (không cố ý)', example: 'Misinformation about health issues spreads rapidly on social media platforms.' },
      { word: 'engagement', phonetic: '/ɪnˈɡeɪdʒ.mənt/', meaning: 'Mức độ tương tác (thích, bình luận, chia sẻ)', example: 'Posts with strong visuals typically receive higher engagement on Instagram.' },
      { word: 'digital footprint', phonetic: '/ˈdɪdʒ.ɪ.təl ˈfʊt.prɪnt/', meaning: 'Dấu vết kỹ thuật số người dùng để lại', example: 'Every search and click leaves a digital footprint that companies can track.' },
      { word: 'data privacy', phonetic: '/ˈdeɪ.tə ˈprɪ.və.si/', meaning: 'Quyền riêng tư dữ liệu cá nhân', example: 'Concerns over data privacy have led to stricter regulations in the European Union.' },
      { word: 'clickbait', phonetic: '/ˈklɪk.beɪt/', meaning: 'Nội dung giật tít để thu hút nhấp chuột', example: 'Many online news sites rely on clickbait headlines to drive traffic.' },
      { word: 'monetise', phonetic: '/ˈmʌn.ɪ.taɪz/', meaning: 'Kiếm tiền từ nội dung số', example: 'YouTubers can monetise their channels once they reach a certain number of subscribers.' },
      { word: 'filter bubble', phonetic: '/ˈfɪl.tər ˌbʌb.əl/', meaning: 'Bong bóng lọc, thuật toán chỉ hiện nội dung phù hợp', example: 'A filter bubble can limit exposure to diverse perspectives and reinforce bias.' },
      { word: 'livestreaming', phonetic: '/ˈlaɪv.striː.mɪŋ/', meaning: 'Phát sóng trực tiếp', example: 'Livestreaming has transformed how artists, gamers and journalists reach their audiences.' },
      { word: 'content creator', phonetic: '/ˈkɒn.tent kriˌeɪ.tər/', meaning: 'Người tạo nội dung số', example: 'The rise of content creators has disrupted traditional media industries.' },
      { word: 'platform', phonetic: '/ˈplæt.fɔːm/', meaning: 'Nền tảng mạng xã hội', example: 'Different platforms attract different demographics and content styles.' },
    ]
  },
  {
    id: 'politics', name: 'Politics & Governance', nameVi: 'Chính trị & Quản trị nhà nước',
    icon: '🏛️', color: '#5C6BC0',
    words: [
      { word: 'constituency', phonetic: '/kənˈstɪtʃ.u.ən.si/', meaning: 'Khu vực bầu cử', example: 'The politician promised to improve public services in her constituency.' },
      { word: 'referendum', phonetic: '/ˌref.əˈren.dəm/', meaning: 'Trưng cầu dân ý', example: 'The country held a referendum on whether to remain part of the union.' },
      { word: 'incumbent', phonetic: '/ɪnˈkʌm.bənt/', meaning: 'Người đang đương chức', example: 'The incumbent president faces a strong challenge from the opposition.' },
      { word: 'coalition', phonetic: '/ˌkəʊ.əˈlɪʃ.ən/', meaning: 'Chính phủ liên minh', example: 'No single party won a majority, so a coalition government was formed.' },
      { word: 'lobby', phonetic: '/ˈlɒb.i/', meaning: 'Vận động hành lang', example: 'Oil companies spend millions lobbying against stricter environmental regulations.' },
      { word: 'mandate', phonetic: '/ˈmæn.deɪt/', meaning: 'Ủy nhiệm, quyền hành động từ sự ủng hộ của cử tri', example: 'The party claimed a strong mandate to implement its policies after winning the election.' },
      { word: 'bipartisan', phonetic: '/ˌbaɪˈpɑː.tɪ.zən/', meaning: 'Lưỡng đảng, được cả hai phe ủng hộ', example: 'The legislation received bipartisan support from both major political parties.' },
      { word: 'sovereignty', phonetic: '/ˈsɒv.rɪn.ti/', meaning: 'Chủ quyền quốc gia', example: 'The dispute centred on the question of national sovereignty over the territory.' },
      { word: 'amendment', phonetic: '/əˈmend.mənt/', meaning: 'Sửa đổi hiến pháp hoặc luật', example: 'Several amendments to the bill were proposed before it was passed.' },
      { word: 'accountability', phonetic: '/əˌkaʊn.tə.ˈbɪl.ɪ.ti/', meaning: 'Trách nhiệm giải trình', example: 'Citizens are demanding greater accountability from elected officials.' },
      { word: 'veto', phonetic: '/ˈviː.təʊ/', meaning: 'Quyền phủ quyết', example: 'The president used her veto to block the controversial new law.' },
      { word: 'authoritarian', phonetic: '/ɔːˌθɒr.ɪˈteər.i.ən/', meaning: 'Độc đoán, chuyên quyền', example: 'The authoritarian regime suppressed all forms of political opposition.' },
      { word: 'geopolitical', phonetic: '/ˌdʒiː.əʊ.pəˈlɪt.ɪ.kəl/', meaning: 'Địa chính trị', example: 'The conflict has significant geopolitical implications for the entire region.' },
      { word: 'bureaucracy', phonetic: '/bjʊˈrɒk.rə.si/', meaning: 'Bộ máy hành chính quan liêu', example: 'Critics argue that excessive bureaucracy slows down economic development.' },
      { word: 'electoral', phonetic: '/ɪˈlek.tər.əl/', meaning: 'Thuộc về bầu cử', example: 'Electoral reform has been debated for decades in this country.' },
    ]
  },
];
